### ISSUE TITLE
[PRE REVIEW]: nasapower: A NASA POWER Global Meteorology, Surface Solar Energy and Climatology Data Client for R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1034]
**Submitting author:** @adamhsparks (<a href="http://orcid.org/0000-0002-0061-8359">Adam H. Sparks</a>)
**Repository:** <a href="https://github.com/ropensci/nasapower" target ="_blank">https://github.com/ropensci/nasapower</a>
**Version:** v1.0.2
**Editor:** @karthik
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @adamhsparks. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@adamhsparks if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @karthik it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1034 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1b5849bd99c1/lib/whedon.rb:117:in `[]': no implicit conversion of String into Integer (TypeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1b5849bd99c1/lib/whedon.rb:117:in `block in parse_affiliations'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1b5849bd99c1/lib/whedon.rb:116:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1b5849bd99c1/lib/whedon.rb:116:in `parse_affiliations'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1b5849bd99c1/lib/whedon.rb:103:in `parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1b5849bd99c1/lib/whedon.rb:73:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1b5849bd99c1/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1b5849bd99c1/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1b5849bd99c1/bin/whedon:52:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1b5849bd99c1/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by adamhsparks** [comment]
@karthik, I've reformatted the YAML header and committed those changes just now, hopefully that helps with the PDF compilation error above?

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1034 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1b5849bd99c1/lib/whedon.rb:117:in `[]': no implicit conversion of String into Integer (TypeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1b5849bd99c1/lib/whedon.rb:117:in `block in parse_affiliations'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1b5849bd99c1/lib/whedon.rb:116:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1b5849bd99c1/lib/whedon.rb:116:in `parse_affiliations'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1b5849bd99c1/lib/whedon.rb:103:in `parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1b5849bd99c1/lib/whedon.rb:73:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1b5849bd99c1/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1b5849bd99c1/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1b5849bd99c1/bin/whedon:52:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1b5849bd99c1/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@adamhsparks - I think your `affiliations` block is the problem: 

```
affiliations:
  index: 1
  name: University of Southern Queensland, Centre for Crop Health, Toowoomba Queensland 4350, Australia
```

should be:

```
affiliations:
  - name: University of Southern Queensland, Centre for Crop Health, Toowoomba Queensland 4350, Australia
    index: 1
```

**Comment by adamhsparks** [comment]
Yes, I just figured that out and sent a commit. Thanks, @arfon

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01034/joss.01034/10.21105.joss.01034.pdf)

**Comment by arfon** [comment]
@whedon assign @arfon as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @arfon
