### ISSUE TITLE
[PRE REVIEW]: Cahn Hilliard CUDA (Phase-Field Simulation of Spinodal Decomposition)

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1058]
**Submitting author:** @myousefi2016 (<a href="http://orcid.org/0000-0002-6497-7166">Mehrdad Yousefi</a>)
**Repository:** <a href="https://github.com/myousefi2016/Cahn-Hilliard-CUDA" target ="_blank">https://github.com/myousefi2016/Cahn-Hilliard-CUDA</a>
**Version:** 1.0
**Editor:** @kyleniemeyer
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @myousefi2016. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@myousefi2016 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @kyleniemeyer it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1058 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
Hi @myousefi2016 - there doesn't seem to be a `paper.md` and `paper.bib` in this repository. Please review our [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements) to understand what is required of authors submitting to JOSS.

**Comment by myousefi2016** [comment]
The paper.md and paper.bib files are added to the repository.

Best,

**********************************************************************

Mehrdad Yousefi
PhD Student, Graduate Research Assistant
Department of Materials Science and Engineering
Clemson Cyber Infrastructure Technology Visualization
Clemson University
266 Sirrine Hall
2004 Barre Hall
Clemson, SC 29634-0971


Phone: 1-864-624-2839
e-mail: yousefi@clemson.edu

**********************************************************************

**Comment by myousefi2016** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Compile the paper
@whedon generate pdf

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper from a custom git branch
@whedon generate pdf from branch custom-branch-name

```

**Comment by myousefi2016** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1058 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon.rb:83:in `check_fields': Paper YAML header is missing expected fields: affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon.rb:69:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/bin/whedon:52:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by myousefi2016** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1058 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0    182      0 --:--:-- --:--:-- --:--:--   182
100    15    0    15    0     0    182      0 --:--:-- --:--:-- --:--:--   180
Error reading bibliography ./paper.bib (line 2, column 9):
unexpected "a"
expecting space or ","
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF
