### ISSUE TITLE
[PRE REVIEW]: strandCheckR: An R package for quantifying and removing double strand sequences for strand-specific RNA-seq

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1129]
**Submitting author:** @tothuhien (<a href="http://orcid.org/0000-0003-2902-3655">Thu-Hien To</a>)
**Repository:** <a href="https://github.com/UofABioinformaticsHub/strandCheckR" target ="_blank">https://github.com/UofABioinformaticsHub/strandCheckR</a>
**Version:** 1.0.0
**Editor:** @mgymrek
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @tothuhien. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@tothuhien if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @mgymrek it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@mgymrek) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
PDF failed to compile for issue #1129 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/lib/whedon.rb:83:in `check_fields': Paper YAML header is missing expected fields: tags, authors, affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/lib/whedon.rb:69:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/bin/whedon:52:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
:wave: @mgymrek - the submitting author suggested you as the handling editor.

**Comment by tothuhien** [comment]
Thanks Arfon! I've just changed the YAML header following the example. Hope
it works now.
Hien

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01129/joss.01129/10.21105.joss.01129.pdf)

**Comment by tothuhien** [comment]
Thanks for building it. I've checked the article proof and it's all good!
Hien

**Comment by mgymrek** [comment]
@rmflight @cbrueffer @nhejazi interested in reviewing this submission?

**Comment by rmflight** [comment]
I am interested in reviewing. Cannot review until after Jan 2, however.
