### ISSUE TITLE
[PRE REVIEW]: ArviZ a unified library for exploratory analysis of Bayesian models in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1142]
**Submitting author:** @canyon289 (<a href="http://orcid.org/0000-0003-0501-6098">Ravin Kumar</a>)
**Repository:** <a href="https://github.com/arviz-devs/arviz" target ="_blank">https://github.com/arviz-devs/arviz</a>
**Version:** v.31
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @canyon289. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@canyon289 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1142 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1142 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/lib/whedon/processor.rb:57:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/bin/whedon:47:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1142 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/lib/whedon/author.rb:23:in `strip_footnotes': undefined method `[]' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/lib/whedon/author.rb:13:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/lib/whedon.rb:109:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/lib/whedon.rb:109:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/lib/whedon.rb:106:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/lib/whedon.rb:106:in `parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/lib/whedon.rb:73:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/bin/whedon:52:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@canyon289 - this PR should fix the paper metadata: https://github.com/arviz-devs/arviz/pull/460

**Comment by canyon289** [comment]
@arfon Thank you for the help

**Comment by canyon289** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01142/joss.01142/10.21105.joss.01142.pdf)

**Comment by canyon289** [comment]
@mattpitkin @lindemann09 @malmaud 

Whedon recommended I find reviewers in this Google doc
https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit#gid=856801822

Found rows listed both Bayesian Statistics and Python and was wondering if you'd like to review

**Comment by canyon289** [comment]
@mattpitkin  We don't _need_ a faster review, but certainly would take one of anyone else is up for it!

I appreciate the quick response

**Comment by malmaud** [comment]
I'd be happy to review this in the next few days.

**Comment by canyon289** [comment]
@malmaud Thank you

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by arfon** [comment]
@whedon assign @canyon289 as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @canyon289

**Comment by arfon** [comment]
@whedon add @mattpitkin as reviewer

**Comment by whedon** [comment]
OK, @mattpitkin is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1143. Feel free to close this issue now!

**Comment by arfon** [comment]
Oops, I set up the review with @canyon289 as a reviewer of their own package. I'll fix this now...
