### ISSUE TITLE
[PRE REVIEW]: GPU-Accelerated LArge-scale MOlecular Simulation Toolkit

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1553]
**Submitting author:** @ (<a href="http://orcid.org/0000-0002-9561-0770">You-Liang Zhu</a>)
**Repository:** <a href="https://bitbucket.org/galamostdevelopergroup/source-code" target ="_blank">https://bitbucket.org/galamostdevelopergroup/source-code</a>
**Version:** v4.0.1
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @. **Currently, there isn't an JOSS editor assigned** to your paper.

@ if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1553 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/1553/galamost-4.0.1/paper/paper.md): found a tab character that violate intendation while scanning a plain scalar at line 5 column 18 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon.rb:95:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon.rb:78:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by arfon** [comment]
We don't have the submitting author's GitHub username yet (I've sent them an email to ask for it) but when they do get here there are a few issues.

**The paper YAML header is malformed**

Please update the paper to match the [example paper](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography) and note that YAML is whitespace sensitive.

```
title: 'GALAMOST: GPU-accelerated large-scale molecular simulation toolkit'
authors:
  - name: You-Liang Zhu
    affiliation: 1
	orcid: 0000-0002-9561-0770
tags:
  - GPUs
  - Molecular dynamics 
  - Soft matters	
affiliations:
 - name: State Key Laboratory of Polymer Physics and Chemistry, Changchun Institute of Applied Chemistry, Chinese Academy of Sciences, Changchun 130022, China.
   index: 1
date: 8 July 2019
output: pdf_document
bibliography: paper.bib
```

**The paper format**

The paper as it currently stands has a lot of bullet points and not much else. Please review the [submission guidelines](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) for what your paper should contain and reformat as necessary.

**Open source license**

Even though a license is mentioned in the README, there needs to be a separate plain text `LICENSE` file with an [OSI approved license](https://opensource.org/licenses) within.

Given the problems with this submission and my challenges contacting the submitting author I'm marking this as paused until we hear back from them.

**Comment by zhuyouliang** [comment]
Many thanks. I have updated files again including the paper and license file.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01553/joss.01553/10.21105.joss.01553.pdf)

**Comment by arfon** [comment]
Hi @zhuyouliang - this paper could still do with some work. It currently reads mostly as a list of functionalities. Please review our guidelines on [what your paper should contain](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain)

**Comment by arfon** [comment]
@kyleniemeyer - would you be willing to edit this submission for JOSS?

**Comment by zhuyouliang** [comment]
The paper is revised according to your suggestion.  Many thanks!

Best Regards,
Youliang



zhuyouliang12345@163.com
 
From: Arfon Smith
Date: 2019-07-09 19:44
To: openjournals/joss-reviews
CC: zhuyouliang; Mention
Subject: Re: [openjournals/joss-reviews] [PRE REVIEW]: GPU-Accelerated LArge-scale MOlecular Simulation Toolkit (#1553)
@kyleniemeyer - would you be willing to edit this submission for JOSS?

**Comment by kyleniemeyer** [comment]
@arfon ok, will take this.

**Comment by kyleniemeyer** [comment]
@whedon assign @kyleniemeyer as editor

**Comment by whedon** [comment]
OK, the editor is @kyleniemeyer

**Comment by kyleniemeyer** [comment]
Hello @zhuyouliang, before trying to find some reviewers, there are some major issues that I see:

- as @arfon pointed out, the paper is still missing some of what is expected, as described in https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain 
- There is very little documentation; all I can see is a README, which does not really explain how to build or use the software. Examples are also very helpful.
- Research software needs tests of some kind; I do not see any sort of test suite.
- There are no community guidelines

Please review our [checklist of review items](https://joss.readthedocs.io/en/latest/review_criteria.html); reviewers will go through this list and try to find evidence of your software satisfying them. Before we try to find reviewers, I would like to see that you have addressed the majority of these in some way. This will allow reviewers to give more useful feedback to improve your software, rather than just saying that the basic things are missing.

I'm going to pause this submission until we see that these things have been addressed.

**Comment by zhuyouliang** [comment]
I reorganize the depository and rewrite the README.md file. Documentation and examples are given in docs and examples files, respectively.
Test suite are also given in tests file. Community guidelines is given in README.md.
Many thanks for your kind help.



zhuyouliang12345@163.com
 
From: Kyle Niemeyer
Date: 2019-07-11 05:29
To: openjournals/joss-reviews
CC: zhuyouliang; Mention
Subject: Re: [openjournals/joss-reviews] [PRE REVIEW]: GPU-Accelerated LArge-scale MOlecular Simulation Toolkit (#1553)
Hello @zhuyouliang, before trying to find some reviewers, there are some major issues that I see:
as @arfon pointed out, the paper is still missing some of what is expected, as described in https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain
There is very little documentation; all I can see is a README, which does not really explain how to build or use the software. Examples are also very helpful.
Research software needs tests of some kind; I do not see any sort of test suite.
There are no community guidelines
Please review our checklist of review items; reviewers will go through this list and try to find evidence of your software satisfying them. Before we try to find reviewers, I would like to see that you have addressed the majority of these in some way. This will allow reviewers to give more useful feedback to improve your software, rather than just saying that the basic things are missing.
I'm going to pause this submission until we see that these things have been addressed.

**Comment by kyleniemeyer** [comment]
@zhuyouliang thank you for making those changes.

However, I noticed that you already published a full paper about your software in the Journal of Computational Chemistry. Would this submission (if accepted) amount to a duplicate publication of the same work?

**Comment by zhuyouliang** [comment]
In that paper, we actually introduced the methods and algorithms that we developed and described little about codes. 
And I didn't open source codes along with that paper.  As far as I know, JOSS is a professional journal to publish codes. 
I believe you will help me a lot to improve the quality of this software.

Best Regards,
Youliang




zhuyouliang12345@163.com
 
From: Kyle Niemeyer
Date: 2019-07-12 05:37
To: openjournals/joss-reviews
CC: zhuyouliang; Mention
Subject: Re: [openjournals/joss-reviews] [PRE REVIEW]: GPU-Accelerated LArge-scale MOlecular Simulation Toolkit (#1553)
@zhuyouliang thank you for making those changes.
However, I noticed that you already published a full paper about your software in the Journal of Computational Chemistry. Would this submission (if accepted) amount to a duplicate publication of the same work?

**Comment by kyleniemeyer** [comment]
@zhuyouliang thank you for clarifying. I think the focus of the original article is sufficiently different to proceed.

Can you suggest a few domain-specific reviewers for us to contact?

**Comment by zhuyouliang** [comment]
Here are some candidates who are developing GPU MD softwares or leading the projects. Many thanks for your kind help!

Prof. Ross C. Walker, San Diego Supercomputer Center, University of California San Diego, 9500 Gilman Drive MC0505, La Jolla, California 92093, United States, E-mail: ross@rosswalker.co.uk, the author of AMBER    
Prof. W. Michael Brown, National Center for Computational Sciences, Oak Ridge National Laboratory, Oak Ridge, TN, USA,  E-mail: brownw@ornl.gov, the author of LAMMPS      
Prof. Yuji Sugita, RIKEN Theoretical Molecular Science Laboratory, 2-1 Hirosawa, Wako, Saitama 351-0198, Japan, E-mail: sugita@riken.jp, the author of GENESIS        
Prof. Peter H. Colberg, Arnold Sommerfeld Center for Theoretical Physics and Center for NanoScience (CeNS), Fakultät für Physik, Ludwig-Maximilians-Universität München, Theresienstraße 37, 80333 München, Germany, E-mail: peter.colberg@utoronto.ca, the author of HALMD



zhuyouliang12345@163.com
 
From: Kyle Niemeyer
Date: 2019-07-22 05:02
To: openjournals/joss-reviews
CC: zhuyouliang; Mention
Subject: Re: [openjournals/joss-reviews] [PRE REVIEW]: GPU-Accelerated LArge-scale MOlecular Simulation Toolkit (#1553)
@zhuyouliang thank you for clarifying. I think the focus of the original article is sufficiently different to proceed.
Can you suggest a few domain-specific reviewers for us to contact?

**Comment by kyleniemeyer** [comment]
Hi @keipertk @mabraham @jeffhammond would any of you be able to review this submission?

**Comment by jeffhammond** [comment]
Forgive me, but this submission has less detail than a decent project README file. Have the editors determined that this submission meets the requirements for a publishable artifact and thus is worth reviewing for technical correctness?

**Comment by kyleniemeyer** [comment]
@jeffhammond I do see a [README](https://bitbucket.org/galamostdevelopergroup/source-code/src/master/README.md) with a description, installation steps, and at least one example, and there are some [documentation source files](https://bitbucket.org/galamostdevelopergroup/source-code/src/master/docs/usage.rst), though I don't see where the compiled documentation lives. If this isn't sufficient for a new user to get started, then that would certainly be feedback during a review, but I do see enough to at least begin a review.

**Comment by kyleniemeyer** [comment]
@jeffhammond I would add that technical correctness is not the primary focus of reviews—ensuring the functional claims of the software are confirmed is certainly one item, but the rest focus on things like documentation, usage, testing, etc.: https://joss.readthedocs.io/en/latest/review_checklist.html

**Comment by zhuyouliang** [comment]
The README file is updated with the links of compiled documentation and tutorials. Please find them. Thanks again.



zhuyouliang12345@163.com
 
From: Jeff Hammond
Date: 2019-07-29 01:09
To: openjournals/joss-reviews
CC: zhuyouliang; Mention
Subject: Re: [openjournals/joss-reviews] [PRE REVIEW]: GPU-Accelerated LArge-scale MOlecular Simulation Toolkit (#1553)
Forgive me, but this submission has less detail than a decent project README file. Have the editors determined that this submission meets the requirements for a publishable artifact and thus is worth reviewing for technical correctness?

**Comment by mabraham** [comment]
Per the guidelines, we should assess "Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution."

There is a hand-written configure script, which I tried. It told me it didn't find boost_thread. I looked at the configure script, and it seems to be hard wired to search in a few system paths. This is unsuitable for HPC software, e.g. on clusters where software is provided by modules. There needs to be a way to provide dependencies from locations that are not system paths - particularly because users may need to install software themselves without support from their administrators. I strongly suggest the use of a automated solution for generated such build files, such as CMake (which has first-class support for CUDA for several years now).

I guess by the contents of the README.md file that there are dependencies/requirements on any or all of CUDA SDK, CUDA device architecture, some C++ compiler, boost, python. The supported and/or minimum required versions of all of these need to be documented.

There is a list of GPUs and their architecture, but there is no text to describe the content. Those are all fairly recent GPUs, but the example for the configure --cuda option refers to sm version 20, which is nearly a decade old. I presume the authors don't want me to infer that they are supporting Kepler hardware! :-) The mentions of sm_20 in the configure script code are very surprising.

configure assumes that devices are available on the machine upon which configure is run. The check that is run should be made optional, because users will often need to build on e.g. the head node of a cluster, which does not have any GPUs, or at least not the ones that might be run on the compute nodes.

There should be guidance on how to interface with python - are header files needed? The configure script looks like it supports python2, and seems to be hard-coded in some way to python 2.4. As python 2.4 is long out of support, and python 2.7 is going out of support at the end of this year, this software will not be usable unless it supports python 3 - I suggest 3.5 or 3.6 as an earliest supported version.

There should be guidance on the use of double or lower precision. Which calculations are shown to require double? Which are suitable with less? Is it full single precision? (No other major MD code has found a way to implement correct code, so the reason this is workable should be documented, and would perhaps be worth a publication in its own right.)

**Comment by kyleniemeyer** [comment]
@mabraham thanks for the quick comments! But, I actually haven't begun the review itself yet; we use this pre-review issue just to assign reviewers, before moving to a separate review issue that includes a checklist (some items you've already commented on). Can I formally assign you as a reviewer? I can copy all of that into the review issue when it's created.

**Comment by zhuyouliang** [comment]
Thanks for your carefull examination.  I have listed the dependencies/requirements in documentation (https://galamost.readthedocs.io/en/latest/installation.html). I will add them to REDAME later.
The configuration file is indeed written by my hand. However, I have tested it in several HPC. Most times, it could work well. The sm_20 in Makefile is the one to be replaced by configuration according to the GPU in machine.
The configuration could detect the compute capability through a small program(\src\compile\compute-capability.cu).  If there is no GPU in your machine, you could set the compute capability by, such as "./configure --cuda_arch=71".
In your case that the boost library can not be found, you could try to set the libray path by "--boost=". 
More options for MPI, precision(double or single floats) are also given in REDAME file. It indeed only support python2. I will fix it later. I know that the Cmake is better for generating build files. However, I am not an expert of Cmake. 


zhuyouliang12345@163.com
 
From: Mark Abraham
Date: 2019-07-29 14:31
To: openjournals/joss-reviews
CC: zhuyouliang; Mention
Subject: Re: [openjournals/joss-reviews] [PRE REVIEW]: GPU-Accelerated LArge-scale MOlecular Simulation Toolkit (#1553)
Per the guidelines, we should assess "Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution."
There is a hand-written configure script, which I tried. It told me it didn't find boost_thread. I looked at the configure script, and it seems to be hard wired to search in a few system paths. This is unsuitable for HPC software, e.g. on clusters where software is provided by modules. There needs to be a way to provide dependencies from locations that are not system paths - particularly because users may need to install software themselves without support from their administrators. I strongly suggest the use of a automated solution for generated such build files, such as CMake (which has first-class support for CUDA for several years now).
I guess by the contents of the README.md file that there are dependencies/requirements on any or all of CUDA SDK, CUDA device architecture, some C++ compiler, boost, python. The supported and/or minimum required versions of all of these need to be documented.
There is a list of GPUs and their architecture, but there is no text to describe the content. Those are all fairly recent GPUs, but the example for the configure --cuda option refers to sm version 20, which is nearly a decade old. I presume the authors don't want me to infer that they are supporting Kepler hardware! :-) The mentions of sm_20 in the configure script code are very surprising.
configure assumes that devices are available on the machine upon which configure is run. The check that is run should be made optional, because users will often need to build on e.g. the head node of a cluster, which does not have any GPUs, or at least not the ones that might be run on the compute nodes.
There should be guidance on how to interface with python - are header files needed? The configure script looks like it supports python2, and seems to be hard-coded in some way to python 2.4. As python 2.4 is long out of support, and python 2.7 is going out of support at the end of this year, this software will not be usable unless it supports python 3 - I suggest 3.5 or 3.6 as an earliest supported version.
There should be guidance on the use of double or lower precision. Which calculations are shown to require double? Which are suitable with less? Is it full single precision? (No other major MD code has found a way to implement correct code, so the reason this is workable should be documented, and would perhaps be worth a publication in its own right.)

**Comment by mabraham** [comment]
Kyle, sure thing.

**Comment by kyleniemeyer** [comment]
@whedon add @mabraham as reviewer

**Comment by whedon** [comment]
OK, @mabraham is now a reviewer

**Comment by kyleniemeyer** [comment]
Just for transparency, I am still seeking out a second reviewer, via email.

**Comment by kyleniemeyer** [comment]
@whedon add @jiajiexiao as reviewer

**Comment by whedon** [comment]
OK, @jiajiexiao is now a reviewer

**Comment by jiajiexiao** [comment]
As I don't have a suitable personal device to test the toolkit, I just went through the repository, documentation and some of the references. Here are some of my comments based on what I have read. 

The simulation toolkit doesn't seem to support any QM/MM methods that simulate the enzymatic reactions. Therefore, I suggest the author be more specific when he mentions the word "reaction" in the description.

Although the author showed an example of how to prepare the configuration XML file for a simple system via ```molgen``` plugin, it is still not clear how to set up a more complex system (e.g. monomers in TIP3P water or DNA and polymerase). Tutorials for these complex examples can be helpful for users. 

It will be more accessible if the cases in the [repository](https://bitbucket.org/galamostdevelopergroup/source-code/src/master/examples/) are presented via markdown rather than .docx files. Bitbucket or GitHub don't directly display the docx file on the website. 

Additionally, the documentation website should add a tutorial section to illustrate how to set up, run, and analysis a system that requires the unique and common functionality of the simulation toolkit. 

It looks that the parameters of the force field have to be hard-coded every time before running the simulation. Is there a way to import and export the force-field settings? Is there a way to call any customed biomolecular force fields such as CHARMM, Amber in the toolkit? 

It would be good if there could be some benchmark comparisons between the GPU/non-GPU version of the package.
