### ISSUE TITLE
[PRE REVIEW]: PyUoI: The Union of Intersections Framework in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1786]
**Submitting author:** @pssachdeva (<a href="http://orcid.org/0000-0002-6809-2437">Pratik Sachdeva</a>)
**Repository:** <a href="https://github.com/BouchardLab/pyuoi" target ="_blank">https://github.com/BouchardLab/pyuoi</a>
**Version:** 1.0.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @pssachdeva. **Currently, there isn't an JOSS editor assigned** to your paper.

@pssachdeva if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1786 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-efe915e61673/lib/whedon.rb:135:in `check_fields': Paper YAML header is missing expected fields: date (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-efe915e61673/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-efe915e61673/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-efe915e61673/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-efe915e61673/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-efe915e61673/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by kyleniemeyer** [comment]
Hi @pssachdeva, thanks for your interest in JOSS! It looks like the article has one or two problems preventing compilation:
- in the YAML header, please add a date field: `date: 5 August 2019` (e.g.)
- author entries with multiple affiliations need those wrapped in quotation marks, so please wrap the affiliations for authors 1, 2, and 4 (e.g., `affiliation: 1, 2, 3` -> `affiliation: "1, 2, 3"`)

**Comment by pssachdeva** [comment]
OK, thanks for pointing that out. Hopefully things should work out now.

**Comment by pssachdeva** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1786 with the following error: 

 Error producing PDF.
! LaTeX Error: File `algorithm.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.263 \usepackage

Looks like we failed to compile the PDF

**Comment by kyleniemeyer** [comment]
@pssachdeva ah, unfortunately I don't believe our template supports the `header-includes:` command.

@arfon, can you confirm? It looks like they want to use an `algorithm` LaTeX environment:
```latex
\begin{algorithm}[t]
    \caption{\textsc{UoI-Lasso}}
    \label{alg:uoi}
    \hspace*{\algorithmicindent} \textbf{Input}:
    $X \in \mathbb{R}^{N\times p}$ design matrix \\
    \hspace*{4.5em} $y \in \mathbb{R}^{N}$ response variable \\
    \hspace*{4.5em} Regularization strengths $\left\{\lambda_j \right\}_{j=1}^{q}$ \\
    \hspace*{4.5em} Number of resamples $N_S$ and $N_E$ \\
    \hspace*{4.5em} Loss function $L(\beta; X, y)$

    \begin{algorithmic}[1]
        \Statex \textit{Model Selection}
        \For{$k = 1$ to $N_S$}
            \State Generate resample $X^k$, $y^k$
            \For{$j=1$ to $q$}
                \State $\hat{\beta}^{jk}\leftarrow$ Lasso regression (penalty $\lambda_j$) of $y^k$ on $X^k$
                \State $S_j^k \leftarrow \left\{i\right\}$ where $\hat{\beta}^{jk}_i \neq 0$
            \EndFor
        \EndFor
        \For{$j = 1$ to $q$}
            \State $\displaystyle S_j \leftarrow \bigcap_{k=1}^{N_S}S_j^k$ \hfill $\triangleright$ \textit{ Intersection}
        \EndFor
        \State \textit{Model Estimation}
        \For{$k=1$ to $N_E$}
            \State Generate training $\left(X_T^k, y_T^k\right)$ and evaluation $\left(X_E^k, y_E^k\right)$ resamples
            \For{$j=1$ to $q$}
                \State $X_{T, j}^k, X_{E, j}^k \leftarrow $ $X_T^k, X_E^k$ with features $S_j$ extracted.
                \State $\hat{\beta}^{jk} \leftarrow$ OLS Regression of $y_T^k$ on $X_{T,j}^k$
                \State $\ell^{jk} \leftarrow L(\hat{\beta}^{jk}; X^k_{E, j}, y_E^k)$
            \EndFor
            \State $\hat{\beta}^k \leftarrow \underset{\hat{\beta}^{jk}}{\text{argmin}} \ \ell^{jk}$
        \EndFor
        \State $\hat{\beta}^* = \underset{k}{\text{median}}\left(\hat{\beta}^k\right)$ \hfill $\triangleright$ \textit{ Union} \\
        \Return $\hat{\beta}^*$
    \end{algorithmic}
\end{algorithm}
```

**Comment by pssachdeva** [comment]
@kyleniemeyer Hm, OK. If we definitely can't use the `algorithm` package, perhaps we could include a picture of the pseudocode instead?

**Comment by arfon** [comment]
@pssachdeva is it just the `algorithms` package you need here?

**Comment by pssachdeva** [comment]
Right now it's using `algorithms` and `algpseudocode`, but we could switch to something else if that would make it easier.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01786/joss.01786/10.21105.joss.01786.pdf)

**Comment by arfon** [comment]
OK,  looks like that's working now ☝️

**Comment by pssachdeva** [comment]
Perfect! Thanks for your help!

**Comment by kyleniemeyer** [comment]
@terrytangyuan apologies for another editing request, but this one looks like it well matches your expertise. Can you take on another?

**Comment by terrytangyuan** [comment]
@whedon assign @terrytangyuan as editor

**Comment by whedon** [comment]
OK, the editor is @terrytangyuan

**Comment by kyleniemeyer** [comment]
Thanks @terrytangyuan!

**Comment by terrytangyuan** [comment]
@pssachdeva  if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Comment by pssachdeva** [comment]
Sure thing, here are some suggestions:

mdehollander
alessandroBombelli
yzhao062
puolival
standage

**Comment by terrytangyuan** [comment]
Hi 👋  @mdehollander @alessandroBombelli @yzhao062 @puolival @standage, if you would like to review for this submission, please let us know here and we need at least two reviewers!

**Comment by puolival** [comment]
Hi @terrytangyuan, I would be happy to review this submission!

**Comment by yzhao062** [comment]
@terrytangyuan I should be able to review it but may need some extra time. Could you confirm the deadline to turn the review back?

**Comment by terrytangyuan** [comment]
@whedon assign @puolival as reviewer

**Comment by whedon** [comment]
OK, @yzhao062 is now a reviewer

**Comment by terrytangyuan** [comment]
@yzhao062 there is no deadline but I’ll try to remind every once a while so we can move forward faster

**Comment by terrytangyuan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1799. Feel free to close this issue now!

**Comment by terrytangyuan** [comment]
@yzhao062 @puolival Thanks! Look forward to your review!
