### ISSUE TITLE
[PRE REVIEW]: CapacityExpansion: A capacity expansion modeling framework in Julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1892]
**Submitting author:** @YoungFaithful (<a href="http://orcid.org/0000-0002-1992-310X">Lucas Elias Kuepper</a>)
**Repository:** <a href="https://github.com/YoungFaithful/CapacityExpansion.jl/tree/paper" target ="_blank">https://github.com/YoungFaithful/CapacityExpansion.jl/tree/paper</a>
**Version:** v0.2.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @YoungFaithful. **Currently, there isn't an JOSS editor assigned** to your paper.

@YoungFaithful if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1892 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1892 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-74bc29a6a731/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-74bc29a6a731/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-74bc29a6a731/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by labarba** [comment]
@arfon — I could not find (again) the name of the team to ping for tech issues. Help!

**Comment by labarba** [comment]
I think maybe the authors provided the wrong repository URL. They provided `https://github.com/YoungFaithful/CapacityExpansion.jl/tree/paper`.

I will change it to `https://github.com/YoungFaithful/CapacityExpansion.jl/tree/paper` and try to re-compile.

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1892 with the following error: 

 Can't find any papers to compile :-(

**Comment by labarba** [comment]
@YoungFaithful — Where is your JOSS paper? I poked around in the repo but could not find it.

**Comment by arfon** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by arfon** [comment]
> @YoungFaithful — Where is your JOSS paper? I poked around in the repo but could not find it.

Looks like it's in the `paper` branch @labarba.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01892/joss.01892/10.21105.joss.01892.pdf)

**Comment by labarba** [comment]
👋  @katyhuff — Could you handle this submission as editor? It is in the area of energy systems management.

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/j.apenergy.2018.01.023 is OK
- 10.21105/joss.01573 is OK
- 10.1137/15M1020575 is OK
- 10.1137/141000671 is OK
- 10.3390/en12061153 is OK
- 10.21105/joss.00825 is OK
- 10.1016/j.rser.2018.08.043 is OK
- 10.1016/j.apenergy.2019.02.012 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by labarba** [comment]
@whedon assign @katyhuff as editor

**Comment by whedon** [comment]
OK, the editor is @katyhuff

**Comment by labarba** [comment]
@katyhuff — I have assigned this submission for you to edit, in view of the topic and current editor loads. Let me know if you see any issues.

**Comment by YoungFaithful** [comment]
I think that @sjpfenninger would be a great reviewer.

**Comment by sjpfenninger** [comment]
Happy to review; but would probably only get to it in the 1st week of December.

**Comment by YoungFaithful** [comment]
@katyhuff thanks for being the editor. What are the next steps that I can do?

**Comment by katyhuff** [comment]
Sorry for the delay in getting this one moving. 

Thanks for agreeing to review @sjpfenninger .  

@lheagy or @ali-ramadhan , would either of you be available to review this submission?

**Comment by katyhuff** [comment]
@whedon assign @sjpfenninger as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @sjpfenninger

**Comment by ali-ramadhan** [comment]
Hi @katyhuff sorry for the very slow reply.

I wasn't sure if I'd have enough time to review this submission but I can do it today.

I'll write up my comments then fill in the reviewer checklist when the review issue is opened.

**Comment by sjpfenninger** [comment]
@katyhuff This seems to be ready to move to review but has stalled?

**Comment by katyhuff** [comment]
Ah! I'm sorry. Yes. This fell completely off of my radar. Thank you for the ping.

**Comment by katyhuff** [comment]
@whedon add @ali-ramadhan as reviewer

**Comment by whedon** [comment]
OK, @ali-ramadhan is now a reviewer

**Comment by katyhuff** [comment]
@ali-ramadhan ,  I hope you are still able to conduct this review. Thank you for agreeing. Apologies for the oversight.

**Comment by katyhuff** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2034. Feel free to close this issue now!
