### ISSUE TITLE
[PRE REVIEW]: graphsim: An R package for simulating gene expression data from graph structures of biological pathways

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2137]
**Submitting author:** @TomKellyGenetics (<a href="http://orcid.org/0000-0003-3904-6690">S. Thomas Kelly</a>)
**Repository:** <a href="https://github.com/TomKellyGenetics/graphsim" target ="_blank">https://github.com/TomKellyGenetics/graphsim</a>
**Version:** 0.1.2
**Editor:** @majensen
**Reviewers:** @rcannood, @corybrunson
**Managing EiC:** Kevin M. Moerman

**Author instructions**

Thanks for submitting your paper to JOSS @TomKellyGenetics. **Currently, there isn't an JOSS editor assigned** to your paper.

@TomKellyGenetics if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2137 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2137 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev can you see what is preventing paper compilation here?

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1186/gb-2014-15-2-r29 is OK
- 10.1186/1752-0509-3-41 is OK
- 10.1093/bioinformatics/btm639 is OK
- 10.1515/jib-2017-0027 is OK
- 10.1093/imanum/22.3.329 is OK
- 10.1186/s13062-015-0086-1 is OK
- 10.1101/gad.11.13.1748 is OK
- 10.1093/bioinformatics/btp174 is OK
- 10.1093/bioinformatics/btu736 is OK
- 10.1093/hmg/ddu309 is OK
- 10.1007/BF01386390 is OK
- 10.1177/1558689812454457 is OK
- 10.1111/j.1651-2227.2006.00178.x is OK
- 10.1124/jpet.103.064824 is OK
- 10.1016/j.cell.2009.02.024 is OK
- 10.1103/PhysRevLett.87.198701 is OK
- 10.1039/C3MB25589A is OK
- 10.1186/gb-2010-11-3-r25 is OK
- 10.1186/1471-2407-14-552 is OK
- 10.1016/j.fob.2012.04.003 is OK
- 10.1200/JCO.2008.18.1370 is OK
- 10.1093/nar/gkt1102 is OK
- 10.1093/bioinformatics/btl633 is OK
- 10.1093/annonc/mdg486 is OK
- 10.1093/hmg/ddp046 is OK
- 10.1001/jama.297.21.2360 is OK
- 10.1371/journal.pgen.1003254 is OK
- 10.1186/1479-5876-7-43 is OK
- 10.1038/nrd3374 is OK
- 10.1158/1078-0432.ccr-13-3116 is OK
- 10.1016/j.ddtec.2013.12.002 is OK
- 10.1038/nrg3899 is OK
- 10.1016/j.cell.2015.11.015 is OK
- 10.1186/gb-2004-5-10-r80 is OK

MISSING DOIs

- https://doi.org/10.1038/nrg2934 may be missing for title: RNA sequencing: advances, challenges and opportunities
- https://doi.org/10.1101/227033 may be missing for title: Gene expression distribution deconvolution in single-cell RNA sequencing
- https://doi.org/10.3389/fgene.2019.00535 may be missing for title: Inferring Interaction Networks From Multi-Omics Data
- https://doi.org/10.1186/1471-2105-8-s6-s5 may be missing for title: Inferring cellular networks–a review
- https://doi.org/10.1038/nprot.2017.149 may be missing for title: Exponential scaling of single-cell RNA-seq in the past decade
- https://doi.org/10.1038/nrg.2016.87 may be missing for title: Network biology concepts in complex disease comorbidities
- https://doi.org/10.1186/s12859-015-0778-7 may be missing for title: Comparing the normalization methods for the differential analysis of Illumina high-throughput RNA-Seq data
- https://doi.org/10.1109/msp.2007.273053 may be missing for title: Finding module-based gene networks with state-space models - Mining high-dimensional and short time-course gene expression data
- https://doi.org/10.3892/ijo.2012.1744 may be missing for title: Molecular features of triple negative breast cancer cells by genome-wide gene expression profiling analysis
- https://doi.org/10.1186/s12967-017-1197-5 may be missing for title: Transcriptomic profiling and quantitative high-throughput (qHTS) drug screening of CDH1 deficient hereditary diffuse gastric cancer (HDGC) cells identify treatment leads for familial gastric cancer
- https://doi.org/10.1109/csb.2003.1227309 may be missing for title: Combining microarrays and biological knowledge for estimating gene networks via bayesian networks
- https://doi.org/10.1126/science.1087361 may be missing for title: A Bayesian networks approach for predicting protein-protein interactions from genomic data
- https://doi.org/10.1371/journal.pcbi.1002110 may be missing for title: Bayesian inference for genomic data integration reduces misclassification rate in predicting protein-protein interactions
- https://doi.org/10.1186/bcr2887 may be missing for title: Three interrelated themes in current breast cancer research: gene addiction, phenotypic plasticity, and cancer stem cells
- https://doi.org/10.1007/s10555-016-9626-0 may be missing for title: Thrombin-unique coagulation system protein with multifaceted impacts on cancer and metastasis
- https://doi.org/10.1093/bioinformatics/btp692 may be missing for title: RNA-Seq gene expression estimation with read mapping uncertainty
- https://doi.org/10.1093/nar/gkl811 may be missing for title: CancerGenes: a gene selection resource for cancer genome projects
- https://doi.org/10.1111/1567-1364.12094 may be missing for title: The expanding role of yeast in cancer research and diagnosis: insights into the function of the oncosuppressors p53 and BRCA1/2
- https://doi.org/10.3390/ijms10062763 may be missing for title: Yeast two-hybrid, a powerful tool for systems biology
- https://doi.org/10.1002/path.4842 may be missing for title: Cancer predisposition syndromes: lessons for truly precision medicine
- https://doi.org/10.3322/caac.21329 may be missing for title: Translating cancer genomes and transcriptomes for precision oncology
- https://doi.org/10.1038/nrg.2016.49 may be missing for title: Coming of age: ten years of next-generation sequencing technologies
- https://doi.org/10.1038/79120 may be missing for title: Methylation of the CDH1 promoter as the second genetic hit in hereditary diffuse gastric cancer
- https://doi.org/10.1038/aps.2012.30 may be missing for title: E-cadherin promotes proliferation of human ovarian cancer cells in vitro via activating MEK/ERK pathway
- https://doi.org/10.1038/onc.2012.563 may be missing for title: Soluble E-cadherin: a critical oncogene modulating receptor tyrosine kinases, MAPK and PI3K/Akt/mTOR signaling
- https://doi.org/10.1038/onc.2008.470 may be missing for title: E-cadherin directly contributes to PI3K/AKT activation by engaging the PI3K-p85 regulatory subunit to adherens junctions of ovarian carcinoma cells
- https://doi.org/10.1038/onc.2008.343 may be missing for title: Cadherins and cancer: how does cadherin dysfunction promote tumor progression?
- https://doi.org/10.1371/journal.pone.0046665 may be missing for title: Down-regulation of CDH1 is associated with expression of SNAI1 in colorectal adenomas
- https://doi.org/10.1038/sj.bjc.6604560 may be missing for title: Reduced expression of a gene proliferation signature is associated with enhanced malignancy in colon cancer
- https://doi.org/10.1186/gb-2013-14-4-r34 may be missing for title: Interactions between immunity, proliferation and molecular subtype in breast cancer prognosis
- https://doi.org/10.1038/ng.2984 may be missing for title: Recurrent gain-of-function mutations of RHOA in diffuse-type gastric carcinoma
- https://doi.org/10.1038/ng.2983 may be missing for title: Whole-genome sequencing and comprehensive molecular profiling identify new driver mutations in gastric cancer
- https://doi.org/10.1038/ng.3073 may be missing for title: An integrated genomics approach identifies drivers of proliferation in luminal-subtype human breast cancer
- https://doi.org/10.1186/bcr2899 may be missing for title: Analysis of tumor environmental response and oncogenic pathway activation identifies distinct basal and luminal features in HER2-related breast tumor subtypes
- https://doi.org/10.1016/0020-0190(89)90102-6 may be missing for title: An algorithm for drawing general undirected graphs
- https://doi.org/10.1093/nar/gkv1108 may be missing for title: SynLethDB: synthetic lethality database toward discovery of selective and sensitive anticancer drug targets
- https://doi.org/10.1038/nature03001 may be missing for title: Finishing the euchromatic sequence of the human genome
- https://doi.org/10.1038/ejhg.2012.247 may be missing for title: Clinical utility gene card for: Hereditary diffuse gastric cancer (HDGC)
- https://doi.org/10.1038/nature14129 may be missing for title: Comprehensive genomic characterization of head and neck squamous cell carcinomas
- https://doi.org/10.1038/nature12222 may be missing for title: Comprehensive molecular characterization of clear cell renal cell carcinoma
- https://doi.org/10.1038/nature21386 may be missing for title: Integrated genomic and molecular characterization of cervical cancer
- https://doi.org/10.1038/nature11252 may be missing for title: Comprehensive molecular characterization of human colon and rectal cancer
- https://doi.org/10.1038/ng.2764 may be missing for title: The Cancer Genome Atlas Pan-Cancer analysis project
- https://doi.org/10.1126/science.1084564 may be missing for title: The Human Genome Project: lessons from large-scale biology
- https://doi.org/10.1038/nbt1485 may be missing for title: The development and impact of 454 sequencing
- https://doi.org/10.1093/bioinformatics/btv733 may be missing for title: PaxtoolsR: pathway analysis in R using Pathway Commons
- https://doi.org/10.1371/journal.pcbi.1003194 may be missing for title: Using biological pathway data with Paxtools
- https://doi.org/10.1093/nar/gkq1039 may be missing for title: Pathway Commons, a web resource for biological pathway data
- https://doi.org/10.1093/bioinformatics/bti623 may be missing for title: ROCR: visualizing classifier performance in R
- https://doi.org/10.1093/clinchem/39.4.561 may be missing for title: Receiver-operating characteristic (ROC) plots: a fundamental evaluation tool in clinical medicine.
- https://doi.org/10.1186/gb-2009-10-3-r25 may be missing for title: Ultrafast and memory-efficient alignment of short DNA sequences to the human genome
- https://doi.org/10.1093/nar/gkq622 may be missing for title: MapSplice: accurate mapping of RNA-seq reads for splice junction discovery
- https://doi.org/10.1038/ncomms11908 may be missing for title: Erratum: The somatic mutation profiles of 2,433 breast cancers refine their genomic and transcriptomic landscapes
- https://doi.org/10.1038/nature10983 may be missing for title: The genomic and transcriptomic architecture of 2,000 breast tumours reveals novel subgroups
- https://doi.org/10.1038/nbt.1637 may be missing for title: Comparative assessment of methods for aligning multiple genome sequences
- https://doi.org/10.1093/bib/bbl026 may be missing for title: Open source tools and toolkits for bioinformatics: significance, and where are we?
- https://doi.org/10.1038/nrg3394 may be missing for title: Reuse of public genome-wide gene expression data
- https://doi.org/10.1093/nar/gks1174 may be missing for title: ArrayExpress update–trends in database growth and links to data analysis tools
- https://doi.org/10.1016/j.ctrv.2011.11.005 may be missing for title: Molecular biology in breast cancer: intrinsic subtypes and signaling pathways
- https://doi.org/10.1200/jco.20.5.1260 may be missing for title: Outcome of preventive surgery and screening for breast and ovarian cancer in BRCA mutation carriers
- https://doi.org/10.1186/gb-2007-8-5-r76 may be missing for title: Identification of conserved gene expression features between murine mammary carcinoma models and human breast tumors
- https://doi.org/10.1634/theoncologist.2010-s5-39 may be missing for title: Molecular stratification of triple-negative breast cancers
- https://doi.org/10.1261/rna.1947110 may be missing for title: Systematic comparison of microarray profiling, real-time PCR, and next-generation sequencing technologies for measuring differential microRNA expression
- https://doi.org/10.1373/clinchem.2015.249623 may be missing for title: Systematic Evaluation of Sanger Validation of Next-Generation Sequencing Variants
- https://doi.org/10.1371/journal.pone.0103917 may be missing for title: A method for quantitative analysis of standard and high-throughput qPCR expression data based on input sample quantity
- https://doi.org/10.1126/science.1105136 may be missing for title: The ENCODE (ENCyclopedia Of DNA Elements) Project
- https://doi.org/10.14343/jcscr.2016.4e1003 may be missing for title: Cancer incidence and mortality worldwide: sources, methods and major patterns in GLOBOCAN 2012
- https://doi.org/10.1200/jco.2006.09.1066 may be missing for title: Meta-analysis of BRCA1 and BRCA2 penetrance
- https://doi.org/10.1093/carcin/21.5.857 may be missing for title: Disorders in cell circuitry during multistage carcinogenesis: the role of homeostasis
- https://doi.org/10.1093/nar/gku1179 may be missing for title: Gene Ontology Consortium: going forward
- https://doi.org/10.1186/bcr326 may be missing for title: Update on HER-2 as a target for cancer therapy: herceptin in the clinical setting
- https://doi.org/10.1016/j.yane.2012.02.046 may be missing for title: Hallmarks of cancer: the next generation
- https://doi.org/10.1038/452788b may be missing for title: James Watson’s genome sequenced at high speed
- https://doi.org/10.1038/44413 may be missing for title: Wellcome funds cancer database
- https://doi.org/10.1073/pnas.70.12.3581 may be missing for title: The Nucleotide Sequence of the lac Operator
- https://doi.org/10.1158/1535-7163.mct-14-0845 may be missing for title: Functional Genetic Screen Identifies Increased Sensitivity to WEE1 Inhibition in Cells with Defects in Fanconi Anemia and HR Pathways
- https://doi.org/10.1371/journal.pcbi.1000817 may be missing for title: Revisiting Date and Party Hubs: Novel Approaches to Role Assignment in Protein Interaction Networks
- https://doi.org/10.1200/jco.2008.16.0812 may be missing for title: A synthetic lethal therapeutic approach: poly(ADP) ribose polymerase inhibitors for the treatment of cancers deficient in DNA double-strand break repair
- https://doi.org/10.1016/j.cell.2011.03.020 may be missing for title: Genetic interactions in cancer progression and treatment
- https://doi.org/10.1371/journal.pgen.1004120 may be missing for title: Quantitative genome-wide genetic interaction screens reveal global epistatic relationships of protein complexes in Escherichia coli
- https://doi.org/10.1097/00006842-200405000-00021 may be missing for title: What you see may not be what you get: a brief, nontechnical introduction to overfitting in regression-type models
- https://doi.org/10.1515/9781400841356.321 may be missing for title: On the properties of small-world network models
- https://doi.org/10.1016/s0076-6879(10)70007-0 may be missing for title: Synthetic genetic array (SGA) analysis in Saccharomyces cerevisiae and Schizosaccharomyces pombe
- https://doi.org/10.1186/1471-2164-15-158 may be missing for title: High throughput synthetic lethality screen reveals a tumorigenic role of adenylate cyclase in fumarate hydratase-deficient cancer cells
- https://doi.org/10.1038/nrg2085 may be missing for title: Exploring genetic interactions and networks with yeast
- https://doi.org/10.3389/fgene.2013.00290 may be missing for title: Genetic interaction networks: better understand to better predict
- https://doi.org/10.1038/ng0806-862 may be missing for title: From worm genetic networks to complex human diseases
- https://doi.org/10.1186/1471-2105-10-17 may be missing for title: Predicting genetic interactions with random walks on biological networks
- https://doi.org/10.1016/j.copbio.2010.11.001 may be missing for title: Charting the genetic interaction map of a cell
- https://doi.org/10.1038/ng1640 may be missing for title: The synthetic genetic interaction spectrum of essential genes
- https://doi.org/10.1158/0008-5472.can-12-3956 may be missing for title: A comparative genomic approach for identifying synthetic lethal interactions in human cancer
- https://doi.org/10.4161/cib.7501 may be missing for title: Exploring the conservation of synthetic lethal genetic interaction networks
- https://doi.org/10.1073/pnas.0806261105 may be missing for title: Significant conservation of synthetic lethal genetic interaction networks between distantly related eukaryotes
- https://doi.org/10.1017/s0080456800012163 may be missing for title: XV.—The Correlation between Relatives on the Supposition of Mendelian Inheritance
- https://doi.org/10.1038/sj.onc.1208044 may be missing for title: Towards full employment: using RNAi to find roles for the redundant
- https://doi.org/10.1002/widm.1055 may be missing for title: Mining high-throughput screens for cancer drug targets-lessons from yeast chemical-genomic profiling and synthetic lethality
- https://doi.org/10.1371/journal.pone.0060847 may be missing for title: Systematic Analysis of Experimental Phenotype Data Reveals Gene Functions
- https://doi.org/10.1103/physreve.65.026107 may be missing for title: Growing scale-free networks with tunable clustering
- https://doi.org/10.1038/nchembio.118 may be missing for title: Network pharmacology: the next paradigm in drug discovery
- https://doi.org/10.1016/j.cell.2014.07.027 may be missing for title: Predicting Cancer-Specific Vulnerability via Data-Driven Detection of Synthetic Lethality
- https://doi.org/10.1038/nbt1096 may be missing for title: Systematic interpretation of genetic interactions using protein networks
- https://doi.org/10.1038/nmeth.2436 may be missing for title: Mapping genetic interactions in human cancer cells with RNAi and multiparametric phenotyping
- https://doi.org/10.1371/journal.pone.0010624 may be missing for title: Searching for Signaling Balance through the Identification of Genetic Interactors of the Rab Guanine-Nucleotide Dissociation Inhibitor gdi-1
- https://doi.org/10.1101/gr.102749.109 may be missing for title: Predicting genetic modifier loci using functional gene networks
- https://doi.org/10.1007/978-1-59745-243-4_20 may be missing for title: Effects of functional bias on supervised learning of a gene network model
- https://doi.org/10.1016/j.cell.2012.03.031 may be missing for title: Sequential application of anticancer drugs enhances cell death by rewiring apoptotic signaling networks
- https://doi.org/10.1186/1752-0509-5-73 may be missing for title: Understanding and predicting synthetic lethal genetic interactions in Saccharomyces cerevisiae using domain genetic interactions
- https://doi.org/10.1109/bibm.2013.6732609 may be missing for title: Syn-Lethality: An Integrative Knowledge Base of Synthetic Lethality towards Discovery of Selective Anticancer Therapies
- https://doi.org/10.1038/ncomms3124 may be missing for title: Genome evolution predicts genetic interactions in protein complexes and reveals cancer drug targets
- https://doi.org/10.1037/e400002009-005 may be missing for title: The Small World Problem
- https://doi.org/10.1038/ng1258 may be missing for title: DNA helicase gene interaction network defined using synthetic lethality analyzed by microarray
- https://doi.org/10.1186/1471-2105-9-426 may be missing for title: Mining protein networks for synthetic genetic interactions
- https://doi.org/10.1371/journal.pcbi.1000928 may be missing for title: An integrative multi-network and multi-classifier approach to predict genetic interactions
- https://doi.org/10.1101/gr.077693.108 may be missing for title: Finding friends and enemies in an enemies-only network: A graph diffusion kernel for predicting novel genetic interactions and co-complex membership from yeast genetic interactions
- https://doi.org/10.1126/science.1162609 may be missing for title: Conservation and rewiring of functional modules revealed by an epistasis map in fission yeast
- https://doi.org/10.1038/nmeth1098 may be missing for title: High-throughput genetic interaction mapping in the fission yeast Schizosaccharomyces pombe
- https://doi.org/10.1016/j.ymeth.2006.07.034 may be missing for title: Quantitative genetic analysis in Saccharomyces cerevisiae using epistatic miniarray profiles (E-MAPs) and its application to chromatin functions
- https://doi.org/10.1016/j.neo.2014.04.007 may be missing for title: CSNK1E/CTNNB1 are synthetic lethal to TP53 in colorectal cancer and are markers for prognosis
- https://doi.org/10.1038/ng.114 may be missing for title: Evolutionary plasticity of genetic interaction networks
- https://doi.org/10.1515/9781400841356.130 may be missing for title: An Experimental Study of the Small World Problem
- https://doi.org/10.1089/104303404322959515 may be missing for title: Novel integrase-defective lentiviral episomal vectors for gene transfer
- https://doi.org/10.1093/nar/gku1075 may be missing for title: COSMIC: exploring the world’s knowledge of somatic mutations in human cancer
- https://doi.org/10.1038/msb.2013.54 may be missing for title: A negative genetic interaction map in isogenic cancer cell lines reveals cancer cell vulnerabilities
- https://doi.org/10.1186/s12864-016-2375-1 may be missing for title: Multi-omic measurement of mutually exclusive loss-of-function enriches for candidate synthetic lethal gene pairs
- https://doi.org/10.1515/9781400841356.301 may be missing for title: Collective dynamics of ’small-world’ networks
- https://doi.org/10.1073/pnas.0406614101 may be missing for title: Combining biological networks to predict genetic interactions
- https://doi.org/10.4137/cin.s14026 may be missing for title: In silico prediction of synthetic lethality by meta-analysis of genetic interactions, functions, and pathways in yeast and human cancer
- https://doi.org/10.1142/s0219720015410024 may be missing for title: Predicting essential genes and synthetic lethality via influence propagation in signaling pathways of cancer cell fates
- https://doi.org/10.1371/journal.pcbi.1003637 may be missing for title: Essential Plasticity and Redundancy of Metabolism Unveiled by Synthetic Lethality Analysis
- https://doi.org/10.3390/biom2040635 may be missing for title: Strategies for the Use of Poly(adenosine diphosphate ribose) Polymerase (PARP) Inhibitors in Cancer Therapy
- https://doi.org/10.1515/9781400841356.349 may be missing for title: Emergence of scaling in random networks
- https://doi.org/10.1038/nrg1272 may be missing for title: Network biology: understanding the cell’s functional organization
- https://doi.org/10.1038/nrg2918 may be missing for title: Network medicine: a network-based approach to human disease
- https://doi.org/10.1093/bib/bbr012 may be missing for title: Travelling the world of gene–gene interactions
- https://doi.org/10.1016/s0306-4379(97)00021-5 may be missing for title: A New and Versatile Method for Association Generation
- https://doi.org/10.1111/j.2517-6161.1995.tb02031.x may be missing for title: Controlling the False Discovery Rate: A Practical and Powerful Approach to Multiple Testing
- https://doi.org/10.1093/biostatistics/kxj037 may be missing for title: Adjusting batch effects in microarray expression data using empirical Bayes methods
- https://doi.org/10.1038/nrc1691 may be missing for title: The concept of synthetic lethality in the context of anticancer therapy
- https://doi.org/10.1186/gm99 may be missing for title: Synthetic Lethality: a framework for the development of wiser cancer therapeutics
- https://doi.org/10.1371/journal.pone.0125795 may be missing for title: Predicting human genetic interactions from cancer genome evolution
- https://doi.org/10.1002/emmm.201100150 may be missing for title: Combined genomic and phenotype screening reveals secretory factor SPINK1 as an invasion and survival factor associated with patient prognosis in breast cancer
- https://doi.org/10.1158/1535-7163.mct-14-1092 may be missing for title: Synthetic lethal screens identify vulnerabilities in GPCR signalling and cytoskeletal organization in E-cadherin-deficient cells
- https://doi.org/10.1016/j.neo.2014.04.007 may be missing for title: CSNK1E/CTNNB1 are synthetic lethal to TP53 in colorectal cancer and are markers for prognosis
- https://doi.org/10.1186/1755-8794-6-30 may be missing for title: Identification of potential synthetic lethal genes to p53 using a computational biology approach
- https://doi.org/10.1093/nar/gkv007 may be missing for title: limma powers differential expression analyses for RNA-sequencing and microarray studies
- https://doi.org/10.1083/jcb.200212033 may be missing for title: Adhesion-independent mechanism for suppression of tumor cell invasion by E-cadherin
- https://doi.org/10.1002/j.1460-2075.1995.tb00301.x may be missing for title: E-cadherin is a tumour/invasion suppressor gene mutated in human lobular breast cancers
- https://doi.org/10.1016/j.ccr.2014.08.008 may be missing for title: DAISY: Picking Synthetic Lethals from Cancer Genomes
- https://doi.org/10.1038/bjc.1997.523 may be missing for title: E-cadherin inactivation in lobular carcinoma in situ of the breast: an early event in tumorigenesis
- https://doi.org/10.1101/cshperspect.a003129 may be missing for title: Involvement of Members of the Cadherin Superfamily in Cancer
- https://doi.org/10.1002/(sici)1096-9896(199712)183:4<404::aid-path1148>3.0.co;2-9 may be missing for title: Simultaneous loss of E-cadherin and catenins in invasive lobular breast cancer and lobular carcinoma in situ
- https://doi.org/10.1038/nrc2620 may be missing for title: Transitions between epithelial and mesenchymal states: acquisition of malignant and stem cell traits

INVALID DOIs

- https://doi.org/10.1016/j.copbio.2007.11.005 is INVALID because of 'https://doi.org/' prefix
- http://dx.doi.org/10.1016/0022-2836(75)90213-2 is INVALID because of 'https://doi.org/' prefix
- http://dx.doi.org/10.1016/j.socnet.2004.11.008 is INVALID because of 'https://doi.org/' prefix
- http://dx.doi.org/10.1016/j.patrec.2005.10.010 is INVALID because of 'https://doi.org/' prefix
- http://dx.doi.org/10.1016/S0169-7552(98)00110-X is INVALID because of 'https://doi.org/' prefix
- http://dx.doi.org/10.1016/S0968-0004(98)01343-7 is INVALID because of 'https://doi.org/' prefix
- http://dx.doi.org/10.1016/S1357-4310(99)01461-6 is INVALID because of 'https://doi.org/' prefix
- http://dx.doi.org/10.1016/S0959-8049(00)00158-1 is INVALID because of 'https://doi.org/' prefix
- http://dx.doi.org/10.1053/gast.2001.29611 is INVALID because of 'https://doi.org/' prefix
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@csoneson @majensen @will-rowe are you able to edit this submission?

**Comment by TomKellyGenetics** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by TomKellyGenetics** [comment]
References corrected.

@whedon generate pdf

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02137/joss.02137/10.21105.joss.02137.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@TomKellyGenetics I think you need to use only the command message text and no other text.

**Comment by TomKellyGenetics** [comment]
@Kevin-Mattheus-Moerman Thanks, I was thinking to try that. Wasn't sure how long it was meant to take. That's fixed the bibliography.

**Comment by TomKellyGenetics** [comment]
Suggested reviewers (by appropriate expertise):

biswapriyamisra
kozo2
camillescott
rcannood
corybrunson

**Comment by Kevin-Mattheus-Moerman** [comment]
@csoneson @majensen @will-rowe can you edit this one?

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @csoneson as editor

**Comment by whedon** [comment]
@csoneson has been invited to edit this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @majensen as editor

**Comment by whedon** [comment]
@majensen has been invited to edit this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedeon invite @will-rowe as editor

**Comment by majensen** [comment]
@whedon assign @majensen as editor

**Comment by whedon** [comment]
OK, the editor is @majensen

**Comment by majensen** [comment]
@corybrunson would you be able to review [this submission](#2137) to [JOSS](https://joss.theoj.org)? Thanks for considering!

**Comment by majensen** [comment]
@rcannood would appreciate your review of [this submission]() to [JOSS](https://joss.theoj.org). Please let me know -- thanks!

**Comment by rcannood** [comment]
Sure!

**Comment by majensen** [comment]
@whedon assign @rcannood as reviewer

**Comment by whedon** [comment]
OK, @rcannood is now a reviewer

**Comment by corybrunson** [comment]
@majensen not this week, but i would be able to next week! If that's OK, then i'm glad to be assigned.

**Comment by arfon** [comment]
@TomKellyGenetics - you might want to truncate your bibtex entries to only those that are cited in the JOSS paper to prevent Whedon responses like this one: https://github.com/openjournals/joss-reviews/issues/2137#issuecomment-594413402

**Comment by majensen** [comment]
> @majensen not this week, but i would be able to next week! If that's OK, then i'm glad to be assigned.

That would be excellent @corybrunson -- very much appreciated!

**Comment by majensen** [comment]
@whedon add @corybrunson as reviewer

**Comment by whedon** [comment]
OK, @corybrunson is now a reviewer

**Comment by majensen** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2161.

**Comment by majensen** [comment]
Thanks @rcannood and @corybrunson for stepping up to review this interesting work by @TomKellyGenetics - please join us at #2161!
