### ISSUE TITLE
[REVIEW]: Surprise: A Python library for recommender systems

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2174]
**Submitting author:** @NicolasHug (<a href="http://orcid.org/0000-0003-1360-704X">Nicolas Hug</a>)
**Repository:** <a href="https://github.com/NicolasHug/Surprise" target ="_blank">https://github.com/NicolasHug/Surprise</a>
**Version:** v1.1.0
**Editor:** @terrytangyuan
**Reviewer:** @sara-02, @ejhigson
**Archive:** Pending

## Status

[![status](https://joss.theoj.org/papers/cd8a6f153e9111fb41142a797b82d53b/status.svg)](https://joss.theoj.org/papers/cd8a6f153e9111fb41142a797b82d53b)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/cd8a6f153e9111fb41142a797b82d53b"><img src="https://joss.theoj.org/papers/cd8a6f153e9111fb41142a797b82d53b/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/cd8a6f153e9111fb41142a797b82d53b/status.svg)](https://joss.theoj.org/papers/cd8a6f153e9111fb41142a797b82d53b)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/NicolasHug/Surprise" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@sara-02 & @ejhigson, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @terrytangyuan know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [ ] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [ ] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/NicolasHug/Surprise">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Contribution and authorship:** Has the submitting author (@NicolasHug) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [ ] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [ ] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/NicolasHug/Surprise">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Contribution and authorship:** Has the submitting author (@NicolasHug) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @sara-02, @ejhigson it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2174 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf from branch joss_paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss_paper. Reticulating splines etc...
```

**Comment by arfon** [comment]
@sara-02, @ejhigson - please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

Any questions/concerns please let @terrytangyuan know.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02174/joss.02174/10.21105.joss.02174.pdf)

**Comment by ejhigson** [comment]
Hi @NicolasHug - congratulations on making a really awesome and very popular software package!

The install and examples all worked perfectly for me. The API documentation is very thorough too. I have couple of questions:

1) are there any similar other existing software packages for recommender systems? One of the review criteria is "Do the authors describe how this software compares to other commonly-used packages?" and I don't see any such comparison in your paper, but if no such packages exist then this is fine.

2) are there any instructions on how to run the unit tests? I can't see any such instructions in the documentation (sorry if I have missed them). When I try running the tests with ``nosetests`` I get an import error for some module called 'similarities' on every test - I include an example below. Do you know what I need to do to fix this?
```
$ nosetests
EEEEEEEEEEEEEEEEEE
======================================================================
ERROR: Failure: ImportError (cannot import name 'similarities')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ed/.local/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/ed/.local/lib/python3.6/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/ed/.local/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/ed/.local/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.6/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.6/imp.py", line 217, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ed/code/surprise/surprise/__init__.py", line 3, in <module>
    from .prediction_algorithms import AlgoBase
  File "/home/ed/code/surprise/surprise/prediction_algorithms/__init__.py", line 23, in <module>
    from .algo_base import AlgoBase
  File "/home/ed/code/surprise/surprise/prediction_algorithms/algo_base.py", line 10, in <module>
    from .. import similarities as sims
ImportError: cannot import name 'similarities'
```

**Comment by NicolasHug** [comment]
Thanks for the review @ejhigson 

I didn't include a comparison with other similar packages. Should I?
It's a bit tricky because recommendation has a very wide range of applications and usually, each library targets a specific one. That I know of, surprise is the only library that focuses on rating prediction and that is still maintained, in Python. There are also openrec, Spotlight and LightFM but they target different applications.

There are instructions to run the tests in the contributing guidelines: https://github.com/NicolasHug/Surprise/blob/master/CONTRIBUTING.md . Also note that a CI instance is ran at every commit, there's a "build passing badge in the [readme](https://github.com/NicolasHug/Surprise).

**Comment by sara-02** [comment]
@NicolasHug If not an exhaustive comparison then even an overview would do. I assume most projects on Recommendation Systems have been written as part of research projects and not maintained after that. 
I recently found this markdown that is trying to curate a list of RecSys available for use, maybe you this to curate your related work section of the paper.
https://github.com/grahamjenson/list_of_recommender_systems

**Comment by ejhigson** [comment]
@NicolasHug :
> I didn't include a comparison with other similar packages. Should I?

I agree with @sara-02 that an overview would be useful.

> recommendation has a very wide range of applications and usually, each library targets a specific one. That I know of, surprise is the only library that focuses on rating prediction and that is still maintained, in Python. There are also openrec, Spotlight and LightFM but they target different applications.

I think this is useful information to include in the paper.

> There are instructions to run the tests in the contributing guidelines: https://github.com/NicolasHug/Surprise/blob/master/CONTRIBUTING.md . Also note that a CI instance is ran at every commit, there's a "build passing badge in the [readme](https://github.com/NicolasHug/Surprise).

Aha sorry I missed this! With these instructions all the tests work perfectly for me.

**Comment by arfon** [comment]
:wave: @NicolasHug - today we [reopened JOSS](https://blog.joss.theoj.org/2020/05/reopening-joss) for new submissions and are checking in on our existing reviews. How are you getting on making these updates to your paper?

**Comment by sara-02** [comment]
@terrytangyuan I have updated my reviews, waiting for @NicolasHug to update the paper w.r.t ` State of the field: Do the authors describe how this software compares to other commonly-used packages?`

**Comment by NicolasHug** [comment]
Thank you for the reviews so far and apologies for the silence!

I'm still short on time ATM but it will get better soon and should be able to address the reviews by mid August.

**Comment by NicolasHug** [comment]
@whedon generate pdf from branch joss_paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss_paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02174/joss.02174/10.21105.joss.02174.pdf)

**Comment by NicolasHug** [comment]
@whedon generate pdf from branch joss_paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss_paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02174/joss.02174/10.21105.joss.02174.pdf)

**Comment by NicolasHug** [comment]
Thanks again everyone! I have updated the paper with a section on related libraries, as suggested by @sara-02 .

**Comment by terrytangyuan** [comment]
👋 @sara-02 Could you review again when you get a chance? Thanks!

**Comment by sara-02** [comment]
@terrytangyuan @NicolasHug LGTM :partying_face:

**Comment by sara-02** [comment]
@NicolasHug Minor suggestion for the first line for the first line of the paper can we replace the phrase `items that the system has to offer` to `items that the platform/service has to offer` so as not to confuse the word `system` from the RecSys we refer to in the beginning of the sentence.

**Comment by NicolasHug** [comment]
Thanks @sara-02 , and good catch. I have modified the first sentence accordingly.

**Comment by NicolasHug** [comment]
@whedon generate pdf from branch joss_paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss_paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02174/joss.02174/10.21105.joss.02174.pdf)

**Comment by terrytangyuan** [comment]
@whedon check references

**Comment by terrytangyuan** [comment]
@whedon check references

**Comment by terrytangyuan** [comment]
@arfon Could you take a look? That doesn't seem to work.

**Comment by NicolasHug** [comment]
@whedon check references from branch joss_paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss_paper
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1145/3159652.3159681 is OK

MISSING DOIs

- https://doi.org/10.25080/majora-92bf1922-00a may be missing for title:  Data Structures for Statistical Computing in Python 
- https://doi.org/10.1109/mcse.2010.118 may be missing for title: Cython: The best of both worlds
- https://doi.org/10.1109/mcse.2011.37 may be missing for title: The NumPy array: a structure for efficient numerical computation
- https://doi.org/10.1002/9781119102779.ch2 may be missing for title: Recommender systems

INVALID DOIs

- None
```

**Comment by NicolasHug** [comment]
@whedon check references from branch joss_paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss_paper
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.25080/Majora-92bf1922-00a is OK
- 10.1109/MCSE.2010.118 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1007/978-3-319-29659-3 is OK
- 10.1145/3159652.3159681 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by terrytangyuan** [comment]
Thanks! 

At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:
- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors
I can then move forward with accepting the submission.

**Comment by NicolasHug** [comment]
Thanks @terrytangyuan , I created an archive on zenodo and the doi is 

10.5281/zenodo.3959188

**Comment by terrytangyuan** [comment]
@whedon set 10.5281/zenodo.3959188 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3959188" target="_blank">10.5281/zenodo.3959188</a> is the archive.

**Comment by terrytangyuan** [comment]
@whedon set v1.1.0 as version

**Comment by whedon** [comment]
OK. v1.1.0 is the version.

**Comment by terrytangyuan** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2174 with the following error: 

 Can't find any papers to compile :-(

**Comment by NicolasHug** [comment]
@terrytangyuan version that I published on zenodo is 1.1.1, not 1.1.0 (not sure if that matters?)

**Comment by terrytangyuan** [comment]
@whedon set v1.1.1 as version

**Comment by whedon** [comment]
OK. v1.1.1 is the version.

**Comment by terrytangyuan** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2174 with the following error: 

 Can't find any papers to compile :-(

**Comment by terrytangyuan** [comment]
@NicolasHug Could you move the paper to master branch?

**Comment by NicolasHug** [comment]
Isn't there a way to accept the paper from another branch? Ideally I'd rather keep the master branch away from non-code related files.

**Comment by terrytangyuan** [comment]
@openjournals/joss-eics Any suggestions on the above issue? This paper looks good to me so I am handing over to you now.

**Comment by arfon** [comment]
@whedon accept from branch joss_paper

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.25080/Majora-92bf1922-00a is OK
- 10.1109/MCSE.2010.118 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1007/978-3-319-29659-3 is OK
- 10.1145/3159652.3159681 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1589

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1589, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true from branch joss_paper 
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@NicolasHug these are some additional comments on your paper: 

- [ ] Please make the affiliation complete and make sure it includes department, city, and country (write United States of America in full). 
- [ ] Remove additional space after bracket last bracket in `(Buitinck et al., 2013; Pedregosa et al., 2011) , ...`

Once you made these changes use `@whedon generate pdf` here to update the paper.

**Comment by Kevin-Mattheus-Moerman** [comment]
@NicolasHug see these required changes :point_up:

**Comment by NicolasHug** [comment]
I have removed the space, thanks.

Regarding the affiliation, would you have more detailed guidelines? The current version seems to be compliant with the [instructions](https://joss.readthedocs.io/en/latest/submitting.html), judging by the provided example.

**Comment by Kevin-Mattheus-Moerman** [comment]
> I have removed the space, thanks.
> 
> Regarding the affiliation, would you have more detailed guidelines? The current version seems to be compliant with the [instructions](https://joss.readthedocs.io/en/latest/submitting.html), judging by the provided example.

I think our guidelines are not clear enough on this, and we are updating these at the moment. If you could change it to have: `Institution, department (if applicable), city, state, country` that would be great. And please spell out United States of America. 
Thanks.

**Comment by NicolasHug** [comment]
Thanks @Kevin-Mattheus-Moerman , I updated to 

`- name: Columbia University, Data Science Institute, New York City, New York, United States of America`

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2174 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2174 with the following error: 

 error: pathspec 'joss-paper' did not match any file(s) known to git.
Can't find any papers to compile :-(

**Comment by NicolasHug** [comment]
@whedon generate pdf from branch joss_paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss_paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02174/joss.02174/10.21105.joss.02174.pdf)

**Comment by danielskatz** [comment]
👋 @Kevin-Mattheus-Moerman - is this ready to go?

**Comment by danielskatz** [comment]
@NicolasHug - in the references, I think "ECML pkdd workshop" should be "ECML PKDD Workshop" Similarly the booktitle for Gantner should be changed to title case (by protecting it in the .bib file with {}s
Guo is missing something
Some caps need to be fixed in Harper
Same for Kula 2015
And Lee
And McKinney
and Yang

After these are fixed, please regenerate the pdf

**Comment by Kevin-Mattheus-Moerman** [comment]
@danielskatz yes this looks good to me. I see you raised a minor issue :point_up:, once that is resolved it looks good to go. You can process acceptance if you like or let me know if you want me to.

**Comment by danielskatz** [comment]
I'll do it once this issue is resolved - thanks

**Comment by NicolasHug** [comment]
@whedon generate pdf from branch joss_paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss_paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02174/joss.02174/10.21105.joss.02174.pdf)

**Comment by NicolasHug** [comment]
Thanks @danielskatz , capitalization is hopefully fixed now

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2174 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
@whedon accept from branch joss_paper

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.25080/Majora-92bf1922-00a is OK
- 10.1109/MCSE.2010.118 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1007/978-3-319-29659-3 is OK
- 10.1145/3159652.3159681 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1628

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1628, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true from branch joss_paper 
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true from branch joss_paper

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1291040716009996289) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1629
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02174](https://doi.org/10.21105/joss.02174)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by danielskatz** [comment]
Thanks to @sara-02 and @ejhigson for reviewing and @terrytangyuan for editing!

Congratulations to @NicolasHug (Nicolas Hug)!!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02174/status.svg)](https://doi.org/10.21105/joss.02174)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02174">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02174/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02174/status.svg
   :target: https://doi.org/10.21105/joss.02174
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02174/status.svg)](https://doi.org/10.21105/joss.02174)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by NicolasHug** [comment]
Thank you so much everyone! :tada:
