### ISSUE TITLE
[PRE REVIEW]: Dataviz: A package of domain specific visualizations and languages for the Pharo live coding environment

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#238]
**Submitting author:** @offray (<a href="http://orcid.org/0000-0002-4640-6984">Offray Vladimir Luna Cárdenas</a>)
**Repository:** <a href="http://mutabit.com/repos.fossil/grafoscopio/doc/tip/Packages/Dataviz/intro.md" target ="_blank">http://mutabit.com/repos.fossil/grafoscopio/doc/tip/Packages/Dataviz/intro.md</a>
**Version:** 2.2.3
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @offray. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@offray if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by labarba** [comment]
@offray : I looked at the `paper.md` file in the webpage (BTW, the link to PDF is broken) and it's just a copy-paste from the blurb on the landing page.

We (the JOSS editors) plan to extend the author guidelines to clarify the requirements, and to be more firm with enforcing them. Paper length is an issue: we need to see a clear statement of need within the research enterprise, and expect that is not possible in under 250 words (the guide will likely give a range of 250 to 1000 words maximum).

Please take the time to write a short paper that describes the functionality of the software and how it addresses a research need.

**Comment by offray** [comment]
Lorena,

I'm away now in a Data Camp outside the country, but I will address your
recommendations after returning, on the first week of August.

Thanks,

Offray

**Comment by cMadan** [comment]
@offray - just thought I'd send a reminder

**Comment by arfon** [comment]
Friendly reminder on this @offray

**Comment by arfon** [comment]
@offray - please respond to this thread when you can. If we don't hear from you in the next two weeks we'll assume you've lost interest in this submission.

**Comment by offray** [comment]
Sorry @arfon and all about not being of respond earlier. Lot of stuff happening in the PhD front. I will be working on the issues reported on this article this week and reporting back here.

**Comment by offray** [comment]
@labarba I have stated the research fields of data activism and civic hacking added into `paper.md` and how Dataviz is part of a set of pocket infrastructures that address the need for more inclusive practices in such fields contrasting critically it with the exclusionary practices of Big Data. I have also fixed the PDF link and added `paper.bib`.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #238 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `block in find': No such file or directory (Errno::ENOENT)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon/processor.rb:49:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/bin/whedon:32:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

```

**Comment by arfon** [comment]
@Kevin-Mattheus-Moerman - Whedon doesn't know how to handle this submission because of where the source is hosted.

**Comment by offray** [comment]
The [previous accepted paper][grafoscopio-paper] was hosted also in a Fossil repository and was processed properly, so this is possible. Let me know what can I make to help on this.

[grafoscopio-paper]: http://joss.theoj.org/papers/c92ed13fa746bc681081f9b31678841b

**Comment by arfon** [comment]
Yep, we can process them, I just have to do it manually.

**Comment by arfon** [comment]
@offray - could you provide links to the `paper.md` and `paper.bib` files please?

**Comment by offray** [comment]
Here they are:
- paper.bib: http://mutabit.com/repos.fossil/grafoscopio/doc/tip/Packages/Dataviz/JOSS/paper.bib
- paper.md: http://mutabit.com/repos.fossil/grafoscopio/raw/Packages/Dataviz/JOSS/paper.md?name=c9dfe60db76b62a44e997f5d2a6a4ee8fd758ad4

**Comment by arfon** [comment]
@offray @Kevin-Mattheus-Moerman - here is the compiled PDF: [10.21105.joss.00238.pdf](https://github.com/openjournals/joss-reviews/files/1633321/10.21105.joss.00238.pdf)

Also, @offray - please could you reformat your `paper.md` file to be exactly like this one please: https://gist.github.com/arfon/a880bdb988d5bdf9df05561122598a6c

**Comment by offray** [comment]
@arfon Done. The new `paper.md` at http://mutabit.com/repos.fossil/grafoscopio/raw/Packages/Dataviz/JOSS/paper.md?name=cb73e904dba8cba62d4ad652c378e6659b37e072 includes your suggestion (and some typos, writing corrections, and screenshots). 

Let me know if anything else needs to be added or removed. 

Thanks.

**Comment by arfon** [comment]
:wave: @acabunoc 0 would you be willing to edit this submission for JOSS?

**Comment by Kevin-Mattheus-Moerman** [comment]
Just pinging again :ping_pong: @acabunoc, could you help edit this one?

**Comment by offray** [comment]
@arfon From the list you send me, I think that Mark Galassi, coudl be a good reviewer, because is the only one that has experience with Smalltalk. Let me know anything else I can help with.

**Comment by arfon** [comment]
@offray ok thanks. Outside of the reviewer list that we have do you have any suggestions for reviewers that you know would be good for this?

**Comment by acabunoc** [comment]
Yes, I can edit this! 🏓

**Comment by acabunoc** [comment]
@whedon assign @acabunoc as editor

**Comment by whedon** [comment]
OK, the editor is @acabunoc

**Comment by offray** [comment]
@arfon I have talked with [Sean DeNigris](https://github.com/seandenigris) and he is willing to help.

Thanks

**Comment by arfon** [comment]
@acabunoc - looks like @offray might have been able to find us a reviewer ☝️

**Comment by offray** [comment]
@arfon @acabunoc, so which are the next steps if Sean DeNigris wants to join the process?
