### ISSUE TITLE
[REVIEW]:  toqito -- Theory of quantum information toolkit: A Python package for studying quantum information

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3082]
**Submitting author:** @vprusso (<a href="http://orcid.org/0000-0002-8952-8981">Vincent Russo</a>)
**Repository:** <a href="https://github.com/vprusso/toqito" target ="_blank">https://github.com/vprusso/toqito</a>
**Version:** 0.0.7
**Editor:** @poulson
**Reviewer:** @rurz, @jameshclrk, @marwahaha
**Archive:** <a href="https://doi.org/10.5281/zenodo.4743211" target="_blank">10.5281/zenodo.4743211</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/348a46c2454beffdd24f3f0fbe128210/status.svg)](https://joss.theoj.org/papers/348a46c2454beffdd24f3f0fbe128210)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/348a46c2454beffdd24f3f0fbe128210"><img src="https://joss.theoj.org/papers/348a46c2454beffdd24f3f0fbe128210/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/348a46c2454beffdd24f3f0fbe128210/status.svg)](https://joss.theoj.org/papers/348a46c2454beffdd24f3f0fbe128210)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/vprusso/toqito" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@rurz & @jameshclrk & @marwahaha, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @poulson know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/vprusso/toqito">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@vprusso) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/vprusso/toqito">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@vprusso) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/vprusso/toqito">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@vprusso) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @rurz, @jameshclrk, @marwahaha it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.44637 is OK
- 10.1016/j.cpc.2012.11.019 is OK
- 10.22331/q-2019-03-11-129 is OK
- 10.22331/q-2018-01-31-49 is OK
- 10.1371/journal.pone.0208073 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=1.91 s (221.1 files/s, 13376.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                         269           4067           7141           7042
TeX                              8            481            125           1715
reStructuredText               124            865           1365           1108
SVG                              8              1              1            949
Markdown                         6            140              0            376
TOML                             1              6              0             57
YAML                             4              3              1             37
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                           422           5575           8641          11319
-------------------------------------------------------------------------------


Statistical information for the repository '1997a42a1bb73e67214000ab' was
gathered on 2021/03/03.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Sanketh Menda                    1             1              1            0.00
Vincent Russo                  330         52598          34796           97.93
georgios-ts                      5           254             10            0.30
sebgrijalva                      3           143              9            0.17
vprusso                         11           784            644            1.60

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Vincent Russo               446            0.8          6.2                6.95
georgios-ts                 237           93.3          0.5                7.59
sebgrijalva                 128           89.5          0.5                6.25
vprusso                   17439         2224.4          7.8                7.82
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03082/joss.03082/10.21105.joss.03082.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03082/joss.03082/10.21105.joss.03082.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
:wave: @marwahaha, please update us on how your review is going (this is an automated reminder).

**Comment by whedon** [comment]
:wave: @jameshclrk, please update us on how your review is going (this is an automated reminder).

**Comment by whedon** [comment]
:wave: @rurz, please update us on how your review is going (this is an automated reminder).

**Comment by rurz** [comment]
Hi, everyone. Hope you're doing well. 

I raised an issue thread on the toqito repo for my review -> https://github.com/vprusso/toqito/issues/48

Keep well, and safe

**Comment by jameshclrk** [comment]
I had a few comments in vprusso/toqito#54. Otherwise, almost good to go.

**Comment by jameshclrk** [comment]
Everything lgtm

**Comment by rurz** [comment]
Hi, I endorse the declaration of James, my rounds of revisions are complete with positive outcome. 👍🏻

**Comment by poulson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #3082 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:147:in `check_fields': Paper YAML header is missing expected fields: affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:89:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by poulson** [comment]
@vprusso: Would you mind fixing the PDF compilation issue. It looks like the 'affiliations' field is missing.

**Comment by vprusso** [comment]
@poulson. Fixed in https://github.com/vprusso/toqito/commit/537ee6051aa5355bbb09e6e12115f1f1d6b43ebc. Thank you very much for the catch!

**Comment by poulson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03082/joss.03082/10.21105.joss.03082.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03082/joss.03082/10.21105.joss.03082.pdf) :page_facing_up: :point_left:

**Comment by poulson** [comment]
Hi @vprusso -- it is looking good but I would consider shortening "applications pertaining to physics" to "physics applications" and potentially replace the comma after "namely" with a colon given the list that follows, and potentially also add a colon after "pertaining to".

With that said, these are minor.

Would you mind registering for a DOI on zenodo (if this version of the software does not already have one) and sharing it here?

**Comment by vprusso** [comment]
Hi @poulson. All great suggestions. Updated accordingly in https://github.com/vprusso/toqito/commit/0cb52bd625de25f8149903f7f52ade91b918ed1f

And yes, I do have a DOI on Zenodo which I can provide below:
10.5281/zenodo.3699578

Thanks again for your comments, and let me know if I can provide anything else. Thanks again!

**Comment by poulson** [comment]
@whedon set  10.5281/zenodo.3699578 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3699578" target="_blank">10.5281/zenodo.3699578</a> is the archive.

**Comment by poulson** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.44637 is OK
- 10.1016/j.cpc.2012.11.019 is OK
- 10.22331/q-2019-03-11-129 is OK
- 10.22331/q-2018-01-31-49 is OK
- 10.1371/journal.pone.0208073 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2283

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2283, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kthyng** [comment]
Hi @vprusso! Can I verify what the current version of your software associated with this JOSS publication is? Also, I see you included a Zenodo archive above but given that it is from March 2020, I'm thinking the software has changed since then. Can you make a Zenodo archive for the software as it stands? This will be associated with your publication. Also, please alter the metadata of the Zenodo archive so that the author list and title exactly match the JOSS paper. Thanks.

**Comment by vprusso** [comment]
Hi @kthyng. Excellent points. Let me address those below:

> Can I verify what the current version of your software associated with this JOSS publication is?

Sure, the current version is `v1.0`

> Also, I see you included a Zenodo archive above but given that it is from March 2020, I'm thinking the software has changed since then. Can you make a Zenodo archive for the software as it stands? This will be associated with your publication

Very good point, I've updated that and have the new Zenodo archive provided here:
https://zenodo.org/record/4743211

> Also, please alter the metadata of the Zenodo archive so that the author list and title exactly match the JOSS paper. Thanks.

Done!

> Please check out the example paper and update your paper so that the parenthetical references are together in one set of parentheses instead of separated out one by one. Also, your references have lower case "python"s in them (and possibly other words). Please update your .bib file so that the references have proper capitalization. You can preserve capitalization with {} around characters, words, or phrases.

Done and updated in the following commit: https://github.com/vprusso/toqito/commit/648a6164f826760ee775319af8a861e6480f1f1b

Thank you again for all the attention to detail. Do let me know if there is anything else to address, and thank you again!

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.4743211 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4743211" target="_blank">10.5281/zenodo.4743211</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.44637 is OK
- 10.1016/j.cpc.2012.11.019 is OK
- 10.22331/q-2019-03-11-129 is OK
- 10.22331/q-2018-01-31-49 is OK
- 10.1371/journal.pone.0208073 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2294

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2294, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@vprusso - one more minor fix here please: https://github.com/vprusso/toqito/pull/57

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.44637 is OK
- 10.1016/j.cpc.2012.11.019 is OK
- 10.22331/q-2019-03-11-129 is OK
- 10.22331/q-2018-01-31-49 is OK
- 10.1371/journal.pone.0208073 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1391403356120289283) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2296
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.03082](https://doi.org/10.21105/joss.03082)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@rurz, @jameshclrk, @marwahaha - many thanks for your reviews here and to @poulson for editing this submission. JOSS relies upon the volunteer effort of people like you and we simply couldn't do it without you! ✨ 

@vprusso - your paper is now accepted and published in JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03082/status.svg)](https://doi.org/10.21105/joss.03082)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03082">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03082/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03082/status.svg
   :target: https://doi.org/10.21105/joss.03082
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03082/status.svg)](https://doi.org/10.21105/joss.03082)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
