### ISSUE TITLE
[PRE REVIEW]: The SAGE Rejected Article Tracker

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3251]
**Submitting author:** @ad48 (<a href="http://orcid.org/0000-0002-8529-9990">Adam Day</a>)
**Repository:** <a href="https://github.com/sagepublishing/rejected_article_tracker_pkg" target ="_blank">https://github.com/sagepublishing/rejected_article_tracker_pkg</a>
**Version:** 1.5.0
**Editor:** @danielskatz
**Reviewers:** @mfenner, @dhimmel
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @ad48. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @danielskatz.

@ad48 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.23 s (307.3 files/s, 19138.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          61            566            520           2216
Markdown                         5            102              0            348
TeX                              1              5              0            164
Jupyter Notebook                 1              0            330             88
YAML                             1              7              0             41
Bourne Shell                     2              4             21             10
-------------------------------------------------------------------------------
SUM:                            71            684            871           2867
-------------------------------------------------------------------------------


Statistical information for the repository '530daf049251f652305208f6' was
gathered on 2021/05/05.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Adam Day                        32          2446            171           66.32
Andy Hails                      21          1159            137           32.84
aday                             4            19             12            0.79
andyleanlibrary                  1             1              1            0.05

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Adam Day                   2362           96.6          2.6               13.12
Andy Hails                  920           79.4          1.6                2.61
aday                         19          100.0          1.4                5.26
andyleanlibrary               1          100.0          2.1                0.00
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1002/bjs.6880 is OK
- 10.1007/s00134-018-5407-2 is OK
- 10.3138/W706-5884-KG84-J282 is OK
- 10.1111/anae.13829 is OK
- 10.23876/j.krcp.20.392 is OK
- 10.1177/0011392116663807 is OK
- 10.1093/ije/dyz187 is OK
- 10.1186/s41073-017-0031-1 is OK
- 10.1371/journal.pbio.3000959 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3251 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:72:in `block in build_affiliation_string': Problem with affiliations for Andrew Hails, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:71:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:71:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:205:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:205:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by kthyng** [comment]
Note that this is a resubmission of #2840.

**Comment by kthyng** [comment]
Hi @ad48 and thanks for your submission. Unfortunately I've needed to add it to a backlog of submissions since our editors in the relevant areas are overburdened currently. Thank you for your patience. In the meantime, could you take a look at the paper compilation errors?

**Comment by ad48** [comment]
Hi @kthyng , yes I will take a look. It's odd, we had the same issue last time and it seems to compile ok when we use the tool provided.

**Comment by ad48** [comment]
I noticed that our affiliation contains an apostrophe. Guessing this is the source of the problem if it's interpreted as a quote. I have now put the affiliation into double quotes to avoid ambiguity. Again, paper appears to compile correctly at https://whedon.theoj.org/ Is there anything more to do just now? Please let me know.

**Comment by ad48** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #3251 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:72:in `block in build_affiliation_string': Problem with affiliations for Andrew Hails, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:71:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:71:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:205:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:205:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by ad48** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #3251 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:72:in `block in build_affiliation_string': Problem with affiliations for Andrew Hails, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:71:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:71:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:205:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:205:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by ad48** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #3251 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:72:in `block in build_affiliation_string': Problem with affiliations for Andrew Hails, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:71:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:71:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:205:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:205:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by ad48** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03251/joss.03251/10.21105.joss.03251.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03251/joss.03251/10.21105.joss.03251.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@sbenthall could you edit this submission?

**Comment by kthyng** [comment]
@whedon invite @sbenthall as editor

**Comment by whedon** [comment]
@sbenthall has been invited to edit this submission.

**Comment by danielskatz** [comment]
I'll go ahead and take this one

**Comment by danielskatz** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
👋 @ad48 - if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Comment by danielskatz** [comment]
👋 @jodischneider - Would you (or someone in your group) be willing to review this submission to JOSS?  We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by danielskatz** [comment]
👋 @jasonpriem, @hpiwowar, @mfenner - Would one of you be willing to review this submission to JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by hpiwowar** [comment]
Sorry Dan, @jasonpriem and I are swamped right now and not able to do any reviews.

**Comment by danielskatz** [comment]
@hpiwowar - thanks for the quick response in any case

**Comment by ad48** [comment]
Hi @danielskatz Thanks for helping with our submission. We will take a look at the list and get back to you.

**Comment by mfenner** [comment]
I can review.

**Comment by ad48** [comment]
@danielskatz I looked at the spreadsheet and found these names who seem like they would have the right skills and interests. 

-- Bibliometrics + Python
gagolews
(there are a few others with Bibliometrics / Scientometrics in their skills, but not Python)

-- ScholComms + Python
dhimmel

-- NLP + Python
bagheria
indika.kahanda at montana
(the NLP in our application is very basic, so on the one hand a reviewer with NLP skills might help improve it, on the other they might not find much of interest, so I'm not sure if this is the right way to go)

**Comment by danielskatz** [comment]
Thanks @mfenner - I'll add you, but we won't start the review (which will happen in a new issue) until we find one more reviewer as well.

**Comment by danielskatz** [comment]
@whedon assign @mfenner as reviewer

**Comment by whedon** [comment]
OK, @mfenner is now a reviewer

**Comment by danielskatz** [comment]
👋 @gagolews, @dhimmel  - Would one of you be willing to review this submission to JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by dhimmel** [comment]
I accept!

**Comment by danielskatz** [comment]
great, thanks! - I'll add you and we'll get started

**Comment by danielskatz** [comment]
@whedon add @dhimmel as reviewer

**Comment by whedon** [comment]
OK, @dhimmel is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3348.

**Comment by jodischneider** [comment]
Sorry, I'm overbooked - but feel free to ask me for another scholcomm
project in the future, or if you lose a quorum of reviewers on this one!

**Comment by gagolews** [comment]
Apologies, extremely busy atm too.
