### ISSUE TITLE
[REVIEW]: Easy3D: a lightweight, easy-to-use, and efficient C++ library for processing and rendering 3D data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3255]
**Submitting author:** @LiangliangNan (<a href="http://orcid.org/0000-0002-5629-9975">Liangliang Nan</a>)
**Repository:** <a href="https://github.com/LiangliangNan/Easy3D" target ="_blank">https://github.com/LiangliangNan/Easy3D</a>
**Version:** v2.4.5
**Editor:** @Kevin-Mattheus-Moerman
**Reviewer:** @adi3, @vissarion, @bhajay
**Archive:** <a href="https://doi.org/10.5281/zenodo.4967311" target="_blank">10.5281/zenodo.4967311</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/29cf579bccf0a1fc1f97de041d230891/status.svg)](https://joss.theoj.org/papers/29cf579bccf0a1fc1f97de041d230891)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/29cf579bccf0a1fc1f97de041d230891"><img src="https://joss.theoj.org/papers/29cf579bccf0a1fc1f97de041d230891/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/29cf579bccf0a1fc1f97de041d230891/status.svg)](https://joss.theoj.org/papers/29cf579bccf0a1fc1f97de041d230891)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/LiangliangNan/Easy3D" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@adi3 & @vissarion & @ @bhajay, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @Kevin-Mattheus-Moerman know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/LiangliangNan/Easy3D">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@LiangliangNan) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/LiangliangNan/Easy3D">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@LiangliangNan) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/LiangliangNan/Easy3D">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@LiangliangNan) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] #3472
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] #3473
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] #3480
- [x] #3481
- [x] #3479

### Software paper

- [x] #3474
- [x] #3475
- [x] #3476
- [x] #3477
- [x] #3478

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @adi3, @vissarion, @ @bhajay it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3255 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon re-invite @bhajay as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@bhajay please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=4.45 s (318.7 files/s, 145819.5 lines/s)
-----------------------------------------------------------------------------------
Language                         files          blank        comment           code
-----------------------------------------------------------------------------------
C/C++ Header                       807          42718          63967         204179
C++                                354          27590          30854         174996
C                                   47           8144           7134          61354
Qt                                  22              0              0           7812
GLSL                                86           1190            963           4437
CMake                               71            689            689           3010
Objective-C                          5            702            339           2919
Markdown                            16            898              0           2705
PL/M                                 1              0              0            494
XML                                  5             17             22            346
make                                 2             37            107             34
Windows Resource File                1              1              2              1
-----------------------------------------------------------------------------------
SUM:                              1417          81986         104077         462287
-----------------------------------------------------------------------------------


Statistical information for the repository '4b0fe2721500647072be8079' was
gathered on 2021/05/05.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Chunmei                          5            49             27            0.00
Daniel Feist                     1             3              3            0.00
Kelvin                           1             7              1            0.00
Liangliang Nan                1977       1134708         582896           97.82
LiangliangNan                   12          1554           1543            0.18
liangliang                      16           302            259            0.03
liangliang.nan                   1             1              0            0.00
tonghao.yuan                     2         25461           9003            1.96

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Chunmei                       1            2.0         14.7                0.00
Daniel Feist                  1           33.3         18.6                0.00
Liangliang Nan           542519           47.8         13.4               17.84
tonghao.yuan              25461          100.0          0.8               18.20
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3255 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/gems/octokit-4.8.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/repos/JuliaCon/proceedings-review/issues/3255: 404 - Not Found // See: https://docs.github.com/rest/reference/issues#get-an-issue (Octokit::NotFound)
	from /app/vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/response.rb:9:in `block in call'
	from /app/vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/response.rb:61:in `on_complete'
	from /app/vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/response.rb:8:in `call'
	from /app/vendor/bundle/ruby/2.6.0/gems/octokit-4.8.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /app/vendor/bundle/ruby/2.6.0/gems/octokit-4.8.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /app/vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:143:in `build_response'
	from /app/vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/connection.rb:387:in `run_request'
	from /app/vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/connection.rb:138:in `get'
	from /app/vendor/bundle/ruby/2.6.0/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'
	from /app/vendor/bundle/ruby/2.6.0/gems/octokit-4.8.0/lib/octokit/connection.rb:156:in `request'
	from /app/vendor/bundle/ruby/2.6.0/gems/octokit-4.8.0/lib/octokit/connection.rb:19:in `get'
	from /app/vendor/bundle/ruby/2.6.0/gems/octokit-4.8.0/lib/octokit/client/issues.rb:114:in `issue'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/review.rb:21:in `issue_body'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:44:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev can you see what's wrong here :pointup:

**Comment by arfon** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03255/joss.03255/10.21105.joss.03255.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03255/joss.03255/10.21105.joss.03255.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
:wave: @vissarion, please update us on how your review is going (this is an automated reminder).

**Comment by whedon** [comment]
:wave: @adi3, please update us on how your review is going (this is an automated reminder).

**Comment by adi3** [comment]
@LiangliangNan Your `Summary` and `Statement of Need` sections are switched. Please correct this and regenerate the article proof. Also, about the figure you have included in the paper, can you please put the plain raw files in a simple grid layout? Right now, they are shown as a collage of overlapping elliptic frames with colorful borders and shadows around them? This is not appropriate for an academic publication.

**Comment by LiangliangNan** [comment]
@adi3 Thanks for pointing out the issues. The paper has been updated in the repository.

**Comment by LiangliangNan** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03255/joss.03255/10.21105.joss.03255.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03255/joss.03255/10.21105.joss.03255.pdf) :page_facing_up: :point_left:

**Comment by LiangliangNan** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03255/joss.03255/10.21105.joss.03255.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03255/joss.03255/10.21105.joss.03255.pdf) :page_facing_up: :point_left:

**Comment by LiangliangNan** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03255/joss.03255/10.21105.joss.03255.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03255/joss.03255/10.21105.joss.03255.pdf) :page_facing_up: :point_left:

**Comment by vissarion** [comment]
Hi @LiangliangNan first of all thanks for this very useful feature-rich package!

As part of my review I created a few issues in the repository 
- https://github.com/LiangliangNan/Easy3D/issues/79
- https://github.com/LiangliangNan/Easy3D/issues/80
- https://github.com/LiangliangNan/Easy3D/issues/81
- https://github.com/LiangliangNan/Easy3D/issues/82

I also have two more comments:
- Performance claims: it seems that in the intro of your paper there are some performance claims about easy3D's efficiency by taking advantage of the powerful GPUs. Can this be clarified? Do you have for example benchmarks for this efficiency or a reference to some scientific publication or some evidence that convince the reader about that claim?
- [OPTIONAL] Automated tests/availability on various platforms: I have only tested the software on debian/ubuntu but there is a claim in the README that the software builds on mac and windows platforms. Unfortunately, I do not have availability on those platforms. My suggestion here is to create automated tests (e.g. using github actions or travis or some other available CI tool) that build and test easy3D on all the claimed platforms. Of course this is not an obligation for the acceptance to JOSS, just my recommendation for the package.

**Comment by LiangliangNan** [comment]
@vissarion Thanks for the very constructive comments and suggestions.

I've revised the ReadMe file for the "missing dependencies". All other issues will be addressed shortly in the individual issues.

> * Performance claims: it seems that in the intro of your paper there are some performance claims about easy3D's efficiency by taking advantage of the powerful GPUs. Can this be clarified? Do you have for example benchmarks for this efficiency or a reference to some scientific publication or some evidence that convince the reader about that claim?

This was observed and reported by many users: Easy3D can render larger models at a good framerate. 
But indeed I haven't done any formal evaluation.

**Comment by LiangliangNan** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03255/joss.03255/10.21105.joss.03255.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03255/joss.03255/10.21105.joss.03255.pdf) :page_facing_up: :point_left:

**Comment by LiangliangNan** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03255/joss.03255/10.21105.joss.03255.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03255/joss.03255/10.21105.joss.03255.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@adi3 @adi3 @vissarion thanks for your help in reviewing here. It looks like the authors have implemented several changes. Can you pick this up again perhaps comment on the key issues the authors should work on?

**Comment by vissarion** [comment]
@Kevin-Mattheus-Moerman almost all of my comments/issues above are addressed by the author (thanks @LiangliangNan !). There is only one left https://github.com/LiangliangNan/Easy3D/issues/81 where I asked for some more clarifications.

**Comment by LiangliangNan** [comment]
@vissarion I've added a "Test" section in the ReadMe file. Thanks!

**Comment by vissarion** [comment]
@Kevin-Mattheus-Moerman I am done with my review and happily suggest acceptance. 

@LiangliangNan thanks for writing and maintaining such as useful package and thanks for your collaboration during the review process.

**Comment by Kevin-Mattheus-Moerman** [comment]
@adi3 @bhajay can you provide an update on review progress? Can you tick any boxes that you feel can be ticked and summarize what you feel needs work? Thanks again for your help!

**Comment by adi3** [comment]
@Kevin-Mattheus-Moerman I'll progress through my checklist this weekend

**Comment by adi3** [comment]
@Kevin-Mattheus-Moerman I am finished my review and recommend acceptance.

@LiangliangNan great work!

**Comment by Kevin-Mattheus-Moerman** [comment]
@bhajay can you please update us on review progress? It would be great if you could pick this up again and let us know what the remaining issues are. Thanks again for your help!

**Comment by Kevin-Mattheus-Moerman** [comment]
I am emailed @bhajay in case GitHub notifications are not getting through.

**Comment by bhajay** [comment]
@Kevin-Mattheus-Moerman : There is no paper.md anymore in the repository

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by Kevin-Mattheus-Moerman** [comment]
> @Kevin-Mattheus-Moerman : There is no paper.md anymore in the repository

Is on the 'joss' branch. I've also just updated it. Does that help?

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03255/joss.03255/10.21105.joss.03255.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03255/joss.03255/10.21105.joss.03255.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@bhajay - please do not use the automated "open an issue" option that GitHub provides. The issues are opened in the wrong repo and have no content.  Instead, please open issue manually in https://github.com/LiangliangNan/Easy3D as needed.  I'm going to close the issues that were incorrectly opened in the wrong repo.  (We would like to disable this GitHub functionality, but cannot)

**Comment by Kevin-Mattheus-Moerman** [comment]
@bhajay can you provide an update about how you are getting on with this review? Thanks

**Comment by Kevin-Mattheus-Moerman** [comment]
@bhajay it would be great to finalize this review process shortly. Can you provide an update please? Thanks.

**Comment by bhajay** [comment]
There are no more comments from my side. Thanks!

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03255/joss.03255/10.21105.joss.03255.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03255/joss.03255/10.21105.joss.03255.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@LiangliangNan congratulations, given the positive reviews above we will now process this work for acceptance in JOSS. 

- [ ] Since this work is about to be accepted we recommend you proofread the paper yourself one more time and also that you verify that the author names and affiliations are accurate. 
- [ ] The paper currently lacks an `Acknowledgements` section, this section is not required but if the work was funded please do include sources of funding in an `Acknowledgements` section. 
- [ ] Please archive a copy of the software on ZENODO and report back here with the archive DOI. You may process the upload manually or use these automated steps which many find useful: https://guides.github.com/activities/citable-code/. 
- [ ] Please amend (if needed) the ZENODO archive (you can edit information manually) such that meta-data like the title and the author list match that of the JOSS paper. The license also needs to match your software license. FYI you can also ensure, where possible, at this point that ORCID ids are also added to the ZENODO authors. 
- [ ] If during the review, or at the point of archiving, the version tag has changed (currently `v2.4.1`) please let us know.

**Comment by LiangliangNan** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03255/joss.03255/10.21105.joss.03255.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03255/joss.03255/10.21105.joss.03255.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon set 10.5281/zenodo.4967311 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4967311" target="_blank">10.5281/zenodo.4967311</a> is the archive.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon set v2.4.5 as version

**Comment by whedon** [comment]
OK. v2.4.5 is the version.

**Comment by Kevin-Mattheus-Moerman** [comment]
@LiangliangNan thanks for working on those steps. Once point remains, the ZENODO archive title still does not match that of the paper. Please change it to match: `Easy3D: a lightweight, easy-to-use, and efficient C++ library for processing and rendering 3D data`

**Comment by LiangliangNan** [comment]
@Kevin-Mattheus-Moerman The title has been updated. Thanks!

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3255 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon recommend-accept from branch joss

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by danielskatz** [comment]
@whedon recommend-accept from branch joss

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.2312/LocalChapterEvents/ItalChap/ItalianChapConf2008/129-136 is OK
- 10.1145/1653771.1653865 is OK
- 10.3390/rs11182074 is OK
- 10.3390/rs12183089 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1016/j.isprsjprs.2021.07.008 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2520

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2520, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true from branch joss 
```

**Comment by danielskatz** [comment]
👋 @Kevin-Mattheus-Moerman - I'm not sure what went wrong when you tried this yesterday, but it's now working.  Please feel free to handle the final processing yourself as a AEiC, or let me know if you want me to do it as the on-duty AEiC.

**Comment by danielskatz** [comment]
👋 @LiangliangNan - please fix the incorrect DOI (remove the 'https://doi.org/' prefix) as `@whedon` suggests above

**Comment by LiangliangNan** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03255/joss.03255/10.21105.joss.03255.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03255/joss.03255/10.21105.joss.03255.pdf) :page_facing_up: :point_left:

**Comment by LiangliangNan** [comment]
> 👋 @LiangliangNan - please fix the incorrect DOI (remove the 'https://doi.org/' prefix) as `@whedon` suggests above

@danielskatz The DOI has been fixed. Please proceed. Thanks!

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check references from branch joss

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.2312/LocalChapterEvents/ItalChap/ItalianChapConf2008/129-136 is OK
- 10.1145/1653771.1653865 is OK
- 10.3390/rs11182074 is OK
- 10.3390/rs12183089 is OK
- 10.1016/j.isprsjprs.2021.07.008 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept deposit=true from branch joss

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1429719092362203140) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2522
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.03255](https://doi.org/10.21105/joss.03255)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by LiangliangNan** [comment]
> 🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨
> 
> Here's what you must now do:
> 
> 1. Check final PDF and Crossref metadata that was deposited 👉 [Creating pull request for 10.21105.joss.03255 joss-papers#2522](https://github.com/openjournals/joss-papers/pull/2522)
> 2. Wait a couple of minutes, then verify that the paper DOI resolves https://doi.org/10.21105/joss.03255
> 3. If everything looks good, then close this review issue.
> 4. Party like you just published a paper! 🎉🌈🦄💃👻🤘
> 
> Any issues? Notify your editorial technical team...

Yes. Everything looks good.
Thank you again for all the help and efforts!

**Comment by Kevin-Mattheus-Moerman** [comment]
Congratulatios @LiangliangNan 

And thank you so much to  @adi3, @vissarion, and @bhajay for your review efforts!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03255/status.svg)](https://doi.org/10.21105/joss.03255)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03255">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03255/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03255/status.svg
   :target: https://doi.org/10.21105/joss.03255
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03255/status.svg)](https://doi.org/10.21105/joss.03255)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
