### ISSUE TITLE
[PRE REVIEW]: BlendOsim: A Blender add-on for visualization of Opensim models and motion capture data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3289]
**Submitting author:** @JonathanCamargo (<a href="http://orcid.org/0000-0001-5219-2110">Jonathan Camargo</a>)
**Repository:** <a href="https://github.com/JonathanCamargo/BlendOsim" target ="_blank">https://github.com/JonathanCamargo/BlendOsim</a>
**Version:** v0.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/8d33741a4c5756862e695ed3a6b18c75/status.svg)](https://joss.theoj.org/papers/8d33741a4c5756862e695ed3a6b18c75)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/8d33741a4c5756862e695ed3a6b18c75"><img src="https://joss.theoj.org/papers/8d33741a4c5756862e695ed3a6b18c75/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/8d33741a4c5756862e695ed3a6b18c75/status.svg)](https://joss.theoj.org/papers/8d33741a4c5756862e695ed3a6b18c75)
```

**Author instructions**

Thanks for submitting your paper to JOSS @JonathanCamargo. **Currently, there isn't an JOSS editor assigned** to your paper.

@JonathanCamargo if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3289 with the following error: 
```
 /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse': (54c9d9a497b676fd84fa863f/doc/paper.md): found character that cannot start any token while scanning for the next token at line 15 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:390:in `parse'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:277:in `load'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:578:in `block in load_file'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `open'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `load_file'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:127:in `load_yaml'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.12 s (129.3 files/s, 75791.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                              6              0           2729           5179
Python                           5            107             61            467
TeX                              1             37              0             89
Markdown                         2             39              0             59
YAML                             1              1              4             18
-------------------------------------------------------------------------------
SUM:                            15            184           2794           5812
-------------------------------------------------------------------------------


Statistical information for the repository 'a2d68aef0f8397243a353acb' was
gathered on 2021/05/15.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Jonathan                         3           649             14          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Jonathan                    635           97.8          0.0                6.61
```

**Comment by danielskatz** [comment]
@JonathanCamargo - thanks for your submission.  Due to the relatively small amount of code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  You should hear back in a week or so.

In addition, you could work on the build problem.  It appears you have a problem on line 15 of your paper.md file.

Please feel free to make changes to your .md and/or .bib files, then use the commands `@whedon check references` to check references, and `@whedon generate pdf` to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by donaldRwilliams** [comment]
@danielskatz any idea why I am getting notifications (it happened for another as well)

**Comment by danielskatz** [comment]
@donaldRwilliams - take a look at the review issue where you are reviewing, and one of the first couple of comments in the issue will show you how to unwatch other issues

**Comment by JonathanCamargo** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by JonathanCamargo** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/TBME.2007.901024 is OK
- 10.3390/s17071591 is OK
- 10.1038/sdata.2018.133 is OK

MISSING DOIs

- 10.1016/b978-012387582-2/50038-1 may be a valid DOI for title: ParaView: An End-User Tool for Large-Data Visualization
- 10.25071/10315/35247 may be a valid DOI for title: Comparative Analysis of OptiTrack Motion Capture Systems

INVALID DOIs

- https://doi.org/10.1016/j.gaitpost.2018.04.004 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.jbiomech.2021.110320 is INVALID because of 'https://doi.org/' prefix
```

**Comment by JonathanCamargo** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/B978-012387582-2/50038-1 is OK
- 10.1007/978-3-030-17369-2 is OK
- 10.1109/TBME.2007.901024 is OK
- 10.3390/s17071591 is OK
- 10.1038/sdata.2018.133 is OK
- 10.1016/j.gaitpost.2018.04.004 is OK
- 10.1016/j.jbiomech.2021.110320 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by JonathanCamargo** [comment]
paper.bib is fixed

**Comment by JonathanCamargo** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #3289 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/orcid_validator.rb:12:in `initialize': undefined method `strip' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:155:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:155:in `block in check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:153:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:153:in `check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:90:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by JonathanCamargo** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03289/joss.03289/10.21105.joss.03289.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03289/joss.03289/10.21105.joss.03289.pdf) :page_facing_up: :point_left:

**Comment by JonathanCamargo** [comment]
Fixed problems with paper.md

**Comment by kyleniemeyer** [comment]
Hello @JonathanCamargo, thanks for your patience. The JOSS editorial board has reviewed your submission, and unfortunately found that it does not meet our [substantial scholarly effort criterion](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) for review by JOSS. Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by kyleniemeyer** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
