### ISSUE TITLE
[REVIEW]: libfmp: A Python Package for Fundamentals of Music Processing

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3326]
**Submitting author:** @fzalkow (<a href="http://orcid.org/0000-0003-1383-4541">Frank Zalkow</a>)
**Repository:** <a href="https://github.com/meinardmueller/libfmp" target ="_blank">https://github.com/meinardmueller/libfmp</a>
**Version:** v1.2.1
**Editor:** @arfon
**Reviewer:** @brunaw, @expectopatronum
**Archive:** <a href="https://doi.org/10.5281/zenodo.5113869" target="_blank">10.5281/zenodo.5113869</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/47b595f5a3d0259d9ae5574e0d4a09b7/status.svg)](https://joss.theoj.org/papers/47b595f5a3d0259d9ae5574e0d4a09b7)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/47b595f5a3d0259d9ae5574e0d4a09b7"><img src="https://joss.theoj.org/papers/47b595f5a3d0259d9ae5574e0d4a09b7/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/47b595f5a3d0259d9ae5574e0d4a09b7/status.svg)](https://joss.theoj.org/papers/47b595f5a3d0259d9ae5574e0d4a09b7)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/meinardmueller/libfmp" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@brunaw & @expectopatronum, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arfon know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/meinardmueller/libfmp">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@fzalkow) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/meinardmueller/libfmp">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@fzalkow) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] #3415
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @brunaw, @expectopatronum it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3326 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.36 s (423.6 files/s, 164540.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            59           8855            174          21375
JavaScript                      14           2404           2467           9203
Python                          55           1880           3643           4641
SVG                              1              0              0           2671
CSS                              4            181             33            726
reStructuredText                13             47            181             66
DOS Batch                        1              8              1             26
Markdown                         2             18              0             22
make                             1              4              7              9
YAML                             1              0              2              6
-------------------------------------------------------------------------------
SUM:                           151          13397           6508          38745
-------------------------------------------------------------------------------


Statistical information for the repository '9f562e921fc63288d9416627' was
gathered on 2021/06/01.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Frank Zalkow                     6         16413           1871           65.33
Meinard Müller                   3          9700              4           34.67

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Frank Zalkow              16405          100.0          0.6               15.56
Meinard Müller             7833           80.8          0.1               10.29
```

**Comment by arfon** [comment]
@brunaw, @expectopatronum – This is the review thread for the paper. All of our communications will happen here from now on.

Please read the "Reviewer instructions & questions" in the first comment above.

Both reviewers have checklists at the top of this thread (in that first comment) with the JOSS requirements. As you go over the submission, please check any items that you feel have been satisfied. There are also links to the JOSS reviewer guidelines.

The JOSS review is different from most other journals. Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, the reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention `https://github.com/openjournals/joss-reviews/issues/3326` so that a link is created to this thread (and I can keep an eye on what is happening). Please also feel free to comment and ask questions on this thread. In my experience, it is better to post comments/questions/suggestions as you come across them instead of waiting until you've reviewed the entire package.

We aim for the review process to be completed within about 4-6 weeks but please make a start well ahead of this as JOSS reviews are by their nature iterative and any early feedback you may be able to provide to the author will be very helpful in meeting this schedule.

**Comment by arfon** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03326/joss.03326/10.21105.joss.03326.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03326/joss.03326/10.21105.joss.03326.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
:wave: @brunaw, please update us on how your review is going (this is an automated reminder).

**Comment by whedon** [comment]
:wave: @expectopatronum, please update us on how your review is going (this is an automated reminder).

**Comment by brunaw** [comment]
@whedon I will start the review next week

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by expectopatronum** [comment]
This is a more general question about how to understand "Substantial scholarly effort". If I would follow the list [here](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort), I would have to say no because:

"positive" answers:
-     **Total lines of code (LOC). Submissions under 1000 LOC will usually be flagged, those under 300 LOC will be desk rejected.:** many :)
-     **Whether the software is sufficiently useful that it is likely to be cited by your peer group.:** probably yes. It has lots of useful functions and reference implementations.

"negative" answers (leading to saying no):
-     **Age of software (is this a well-established software project) / length of commit history.:** according to the git history it's 6 month old
-     **Number of commits.:** 12
-     **Number of authors.:** 2
-     **Whether the software has already been cited in academic papers.:** My search for "libfmp" in Google Scholar only returned other work by the same group.

The two "positive" answers might outweigh some of the negatives. I don't think that the age of the software / the number of commits / number of authors should have much to say, as I would say that also one person could create a very useful software package, and 10 people might not; and additionally, the age of the git repository and the number of commits might not reflect the actual development effort as many software packages start in a private repository.

This leaves me with the last question (according to my reordered list), which is actually important. As mentioned above "libfmp" is only mentioned in papers by the same group. Since libfmp has only been available via pip for a couple of months, and was not promoted before (I think), this seems reasonable. So I also checked the [papers citing the FMP notebooks paper](https://scholar.google.com/scholar?cites=10367164936759895611&as_sdt=2005&sciodt=0,5&hl=en) which I would expect people to cite if they were using the code and it looks like the FMP notebooks paper is exclusively cited by work from the same group.

Maybe @arfon can clarify how this question should be answered given the information I provided. Thanks!

**Comment by expectopatronum** [comment]
I created [an issue](https://github.com/meinardmueller/libfmp/issues) for almost all the things I noticed. There are two other things that I am not sure about and might be interesting to discuss with the other reviewer or the editor:

* The "Statement of Need" in the paper is quite long. From the sentence starting at line 58 onward it feels more like a description of the actual package rather than a statement of need, maybe this could be moved to a separate section.
* There are some design choices I am not completely happy with:
  * The paper claims to integrated and build upon the `librosa` package, but many variable are named differently, and unfortunately some are harder to understand, such as `H` instead of `hop_length`, `N` instead of `n_fft`. 
  * Naming of the sub packages. I understand that the reason for naming the sub packages b, c1, ... c8 is to follow the FMP notebooks, and the book they are based on but for me as a user it is a bit cumbersome to remember or look up the sub package everytime instead of remembering a meaningful package name. I think it might be possible to keep the structure as it is and add some imports to the `__init__.py` files, to "rename" how the sub packages could be imported.

Would be interesting to hear other people's opinion about those two things.

Best regards
Verena

**Comment by fzalkow** [comment]
Many thanks for the thorough review process. I just want to clarify two of the mentioned points.

Age of software: The development of libfmp went hand in hand with developing the [FMP notebooks](https://www.audiolabs-erlangen.de/resources/MIR/FMP/C0/C0.html), which have been developed internally before releasing libfmp on GitHub. This development process preceded the first GitHub release by a few years. Furthermore, some of the algorithms are based on previously unpublished internal MATLAB implementations, which predate FMP by several years.

Variable names: The deviations of the variable names compared to librosa is intentional. An essential aspect of the FMP notebooks and libfmp is to establish a close connection to the [FMP book](https://www.audiolabs-erlangen.de/fau/professor/mueller/bookFMP). This connection enables students to study fundamental MIR concepts in-depth by reading a textbook along with implementations of the concepts explained in the book. Thus, the variable names reflect the mathematical notation used in the book.

Best,

Frank

**Comment by expectopatronum** [comment]
> Age of software ...
That's what I assumed! (and also doesn't have an impact on my review) The first comment was more of a question for the editor, since it is not clear to me what is expected from me for answering the "Substantial scholarly effort" question, although I am inclined to answer it with yes.

> Variable names ...
Thanks for the clarification, makes sense!

If you can take care of the minor issues I raised [here](https://github.com/meinardmueller/libfmp/issues/3) I can tick all the missing boxes and can finish my review.

**Comment by arfon** [comment]
> Maybe @arfon can clarify how this question should be answered given the information I provided. Thanks!

Thanks for raising these questions about scholarly effort @expectopatronum – the 'signals' we suggest are just pointers you might be able to use to guide your thinking. We also say that the work should represent [three or more months of effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) which is sound like it does?

After reading the README in a little more detail myself I did have one question for the authors – could you clarify @fzalkow if this is software designed for addressing research challenges or is a teaching tool? JOSS doesn't publish software designed for teaching (we encourage authors to submit to our sister journal [JOSE](https://jose.theoj.org) for submissions that fall into this category).

**Comment by fzalkow** [comment]
Dear arfon,

Many thanks for your question.

Indeed libfmp covers both teaching and research aspects. This combination is due to the origin of libfmp. The starting point is Müller's [FMP book](https://www.audiolabs-erlangen.de/fau/professor/mueller/bookFMP), where fundamental music information retrieval (MIR) algorithms are presented in a didactically prepared textbook. These algorithms summarize the essence from the research of many years. Then, we developed the [FMP notebooks](https://www.audiolabs-erlangen.de/resources/MIR/FMP/C0/C0.html), which expand and complement the FMP book. Here, the aim is more on the teaching side. During the development of the FMP notebooks, many research-related algorithms have been collected in the libfmp package, which we now made available independent of the FMP notebooks. Thus, compared to the FMP notebooks, the research aspect is more dominant in libfmp. Due to this development, we consider libfmp an ideal tool to transition from studying (using the FMP notebooks and the FMP book) to research. The package is intended for research purposes and contains (similar to librosa) many implementations of core algorithms and advanced methods for MIR.

Concerning three or more months of effort: This holds undoubtedly. The development of libfmp started a few years ago. Considering the origins in the FMP book, it even can be traced back more than a decade.

Best,

Frank

**Comment by arfon** [comment]
> The package is intended for research purposes and contains (similar to librosa) many implementations of core algorithms and advanced methods for MIR.

Got it. Thanks for the additional context and background.

@brunaw – do you think you might be able to complete your review soon?

**Comment by brunaw** [comment]
Dear @arfon, 

I will complete my review next week. Is that okay?

**Comment by brunaw** [comment]
@expectopatronum Just my two cents of the previous discussion. It's a little strange to me that the FMP notebooks paper isn't cited much because, at least from my experience, the notebooks are widely known in the ISMIR community. I know a few people who have used it in their research so they might have missed it when writing their references. This also leads to the age question, the first time I got to know the FMP notebooks was about ~3 years ago, and they were already very well developed/organized by them, so the software is certainly older than 6 months. I hope this helps with something.

**Comment by arfon** [comment]
> I will complete my review next week, my apologies for the delay. Is that okay?

Absolutely! Thanks for the update.

**Comment by brunaw** [comment]
@arfon I am unable to change/click in my checklist items, could you please help me fix it?

**Comment by danielskatz** [comment]
@whedon re-invite @brunaw as reviewer

**Comment by whedon** [comment]
The reviewer already has a pending invite.

@brunaw please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by brunaw** [comment]
@danielskatz My invitation has expired

**Comment by danielskatz** [comment]
@whedon re-invite @brunaw as reviewer

If this doesn't work, is there a chance you have multiple github accounts and the one with the invitation isn't the one your are logged into?

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@brunaw please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by danielskatz** [comment]
This may have just been very bad timing

**Comment by brunaw** [comment]
@danielskatz I think it was just that I didn't do anything about the first invitation and it didn't let you re-invite me even thought the invitation was already expired

Thank you! and apologies for the trouble

**Comment by brunaw** [comment]
Dear @fzalkow, 

Here are my comments/suggestions about the submission, 

- I didn't find the Statement of Need too long, more often than not I see authors writing insufficient/generic Statements of Need so this was a good surprise. I do agree with @expectopatronum that the text can be separated into "Introduction" + "Statement of Need" though, it would make the writing flow better

- I found most functions/arguments descriptions very short. I understand that sometimes it seems like a 4-word sentence properly describes a function, but considering that this software will be mainly used by students and/or people who just started learning MIR, it would be nice to have more comprehensive descriptions. For  example, the `b.b_annotation.read_csv()` function is described as

> Reads a CSV file

And it could be something more complete like

> Reads a CSV file in table format and creates a pd.DataFrame from it, with observations in the rows and variables in the columns 


Just a quick compliment, I think this was one of the best submissions I've reviewed so far. The paper was well written and I was able to check all boxes right away. The issues pointed by the first reviewer were well addressed, so I would like to congratulate the authors for the good work.

**Comment by meinardmueller** [comment]
Dear @brunaw,

Thanks for your suggestions and comments. As for your first point, we followed your suggestion by adding one more headline, which better structures the paper.  As for the second point, we have the following suggestion. Most of the libfmp-functions are introduced step-by-step and explained in the FMP Notebooks; in the header of the libfmp-functions, we provided a link to the respective FMP notebook (provided as static html-version on our website). There are only a few libfmp-functions that do not have a companion in the FMP notebooks (e.g., the one you mentioned). For those functions, we would add some more details in the header as suggested by you. Doing this , we would require some weeks (also due to holidays). Does this sound ok for you?

**Comment by fzalkow** [comment]
Dear @brunaw,

I just implemented Meinard's suggestion regarding your second point (meinardmueller/libfmp@f9e8895d2b529ee6f813afe7d3ecfa08517d5fb4, meinardmueller/libfmp@57905e09555259d5b8b9688934a6695f638d06ee). I am currently on holiday – so sorry for our somewhat asynchronous communication.

Meinard modified the markdown. So, @whedon generate pdf from branch paper.

**Comment by arfon** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03326/joss.03326/10.21105.joss.03326.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03326/joss.03326/10.21105.joss.03326.pdf) :page_facing_up: :point_left:

**Comment by brunaw** [comment]
@meinardmueller @fzalkow Yes, sounds good to me. I just saw the new changes in the paper and the function descriptions and it all looks good, thank you

**Comment by arfon** [comment]
> @meinardmueller @fzalkow Yes, sounds good to me. I just saw the new changes in the paper and the function descriptions and it all looks good, thank you

:zap: great! I think based on the feedback of both of our reviewers here we're in good shape to move forward.

@fzalkow - Once you've made all of the changes you plan to could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

I can then move forward with accepting the submission.

**Comment by fzalkow** [comment]
Dear @arfon, we made a new release (latest: v1.2.1) and a Zenodo archive (DOI: [10.5281/zenodo.5113869](https://doi.org/10.5281/zenodo.5113869)). Please let us know if everything looks right. Many thanks.

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.5113869 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.5113869" target="_blank">10.5281/zenodo.5113869</a> is the archive.

**Comment by arfon** [comment]
@whedon set v1.2.1 as version

**Comment by whedon** [comment]
OK. v1.2.1 is the version.

**Comment by arfon** [comment]
@whedon recommend-accept from branch paper

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3326 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/gems/bibtex-ruby-6.0.0/lib/bibtex/bibliography.rb:50:in `read': No such file or directory @ rb_sysopen - 5c6867af5266b997a2e1f6c4/paper/["references.bib"] (Errno::ENOENT)
	from /app/vendor/bundle/ruby/2.6.0/gems/bibtex-ruby-6.0.0/lib/bibtex/bibliography.rb:50:in `open'
	from /app/vendor/bundle/ruby/2.6.0/gems/bibtex-ruby-6.0.0/lib/bibtex/utilities.rb:25:in `open'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/bibtex_parser.rb:38:in `generate_citations'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/compilers.rb:253:in `crossref_from_markdown'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/compilers.rb:21:in `generate_crossref'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:100:in `compile'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:88:in `compile'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by arfon** [comment]
@fzalkow – could you please merge this PR which fixes your paper: https://github.com/meinardmueller/libfmp/pull/5

**Comment by fzalkow** [comment]
> @fzalkow – could you please merge this PR which fixes your paper: [meinardmueller/libfmp#5](https://github.com/meinardmueller/libfmp/pull/5)

Done!

**Comment by arfon** [comment]
@whedon recommend-accept from branch paper

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.25080/Majora-7b98e3ed-003 is OK
- 10.1109/MSP.2018.2876190 is OK
- 10.5281/zenodo.1415016 is OK
- 10.1145/2964284.2973795 is OK
- 10.1145/1631272.1631459 is OK
- 10.5281/zenodo.1417145 is OK
- 10.5281/zenodo.3527872 is OK
- 10.1109/TASL.2010.2096216 is OK
- 10.1109/ICASSP.2010.5495219 is OK
- 10.1109/TASL.2012.2227732 is OK
- 10.5281/zenodo.1416024 is OK
- 10.5281/zenodo.1416800 is OK
- 10.5281/zenodo.1415226 is OK
- 10.1109/ICASSP.2012.6287834 is OK

MISSING DOIs

- 10.1007/978-3-319-21945-5 may be a valid DOI for title: Fundamentals of Music Processing

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2467

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2467, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true from branch paper 
```

**Comment by arfon** [comment]
@whedon accept deposit=true from branch paper

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1417489194453250048) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2468
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.03326](https://doi.org/10.21105/joss.03326)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@brunaw, @expectopatronum – many thanks for your reviews here! JOSS relies upon the volunteer effort of people like you and we simply wouldn't be able to do this without you ✨ 

@fzalkow – your paper is now accepted and published in JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03326/status.svg)](https://doi.org/10.21105/joss.03326)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03326">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03326/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03326/status.svg
   :target: https://doi.org/10.21105/joss.03326
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03326/status.svg)](https://doi.org/10.21105/joss.03326)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by fzalkow** [comment]
Awesome! Many thanks, @arfon, @brunaw, and @expectopatronum for the fantastic review process! :partying_face:

**Comment by expectopatronum** [comment]
@fzalkow Thanks as well, it was nice working with you! Congrats on your paper!

**Comment by brunaw** [comment]
@fzalkow No problem at all, it was a pleasure, congrats on the excellent work 😊
