### ISSUE TITLE
[REVIEW]: Abmarl: Connecting Agent-Based Simulations with Multi-Agent Reinforcement Learning

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3424]
**Submitting author:** @rusu24edward (<a href="http://orcid.org/0000-0003-1033-439X">Edward Rusu</a>)
**Repository:** <a href="https://github.com/LLNL/Abmarl/" target ="_blank">https://github.com/LLNL/Abmarl/</a>
**Version:** 0.1.4
**Editor:** @drvinceknight
**Reviewer:** @seba-1511, @abhiramm7
**Archive:** <a href="https://doi.org/10.5281/zenodo.5196791" target="_blank">10.5281/zenodo.5196791</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/449c5d79d407dc2e0dbbbb0dae55e122/status.svg)](https://joss.theoj.org/papers/449c5d79d407dc2e0dbbbb0dae55e122)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/449c5d79d407dc2e0dbbbb0dae55e122"><img src="https://joss.theoj.org/papers/449c5d79d407dc2e0dbbbb0dae55e122/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/449c5d79d407dc2e0dbbbb0dae55e122/status.svg)](https://joss.theoj.org/papers/449c5d79d407dc2e0dbbbb0dae55e122)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/LLNL/Abmarl/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@seba-1511 & @abhiramm7, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @drvinceknight know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/LLNL/Abmarl/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@rusu24edward) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/LLNL/Abmarl/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@rusu24edward) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] #3515
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @seba-1511, @abhiramm7 it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.25 s (461.0 files/s, 68876.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          94           2095           1891          10787
reStructuredText                 9            321            649            522
Markdown                         2             35              0            131
YAML                             5             21             19            111
TeX                              1              8              0             72
Bourne Shell                     1             31            242             41
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                           114           2523           2809          11699
-------------------------------------------------------------------------------


Statistical information for the repository '06e711bc81620ad59e0ec5aa' was
gathered on 2021/06/28.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Eddie Rusu                     421         31301          17013           98.20
Edward Rusu                      2           646            181            1.68
glatt1                           1            39             21            0.12

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Eddie Rusu                14757           47.1          1.5                6.27
glatt1                       16           41.0          4.0                0.00
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1613/jair.3912 may be a valid DOI for title: The Arcade Learning Environment: An Evaluation Platform for General Agents

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03424/joss.03424/10.21105.joss.03424.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03424/joss.03424/10.21105.joss.03424.pdf) :page_facing_up: :point_left:

**Comment by drvinceknight** [comment]
> MISSING DOIs
> 
> - 10.1613/jair.3912 may be a valid DOI for title: The Arcade Learning Environment: An Evaluation Platform for General Agents

@rusu24edward if you could take a look at the above missing DOI please.

**Comment by rusu24edward** [comment]
Reviewers, please note that the release branch is [abmarl-87-interface-release](https://github.com/LLNL/Abmarl/tree/abmarl-87-interface-release). The main branch has some additional developmental work that is not a part of the release nor this review.

**Comment by rusu24edward** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by rusu24edward** [comment]
@whedon check references

**Comment by rusu24edward** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1613/jair.3912 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by rusu24edward** [comment]
@drvinceknight I believe I have fixed the DOI issue.

**Comment by whedon** [comment]
:wave: @seba-1511, please update us on how your review is going (this is an automated reminder).

**Comment by whedon** [comment]
:wave: @abhiramm7, please update us on how your review is going (this is an automated reminder).

**Comment by seba-1511** [comment]
I plan to complete my review by Sunday, July 18.

**Comment by abhiramm7** [comment]
I plan to wrap up the review by early next week, July 19

**Comment by rusu24edward** [comment]
Hi @seba-1511 and @abhiramm7. Thanks for the review work you have done so far. I just wanted to check in since we are at the dates now where we've anticipated the review would be done. Is there anything you need from me to help move this along? Any feedback on the software or paper?

**Comment by seba-1511** [comment]
@rusu24edward Apologies for the delay -- so far the submission looks good. I think ray in requirements.txt should be updated to `ray[default]` (a warning otherwise pops up) but even with that, I get the following stack trace when following the quickstart instructions:

~~~shell
Traceback (most recent call last):
  File "/Users/sebarnol/anaconda3/envs/abmarl36/lib/python3.6/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/Users/sebarnol/anaconda3/envs/abmarl36/lib/python3.6/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/Users/sebarnol/anaconda3/envs/abmarl36/lib/python3.6/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sebarnol/anaconda3/envs/abmarl36/bin/abmarl", line 33, in <module>
    sys.exit(load_entry_point('abmarl', 'console_scripts', 'abmarl')())
  File "/Users/sebarnol/Desktop/Abmarl/abmarl/scripts/scripts.py", line 43, in cli
    train.run(path_config)
  File "/Users/sebarnol/Desktop/Abmarl/abmarl/scripts/train_script.py", line 17, in run
    train.run(full_config_path)
  File "/Users/sebarnol/Desktop/Abmarl/abmarl/train.py", line 29, in run
    ray.init()
  File "/Users/sebarnol/anaconda3/envs/abmarl36/lib/python3.6/site-packages/ray/_private/client_mode_hook.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/Users/sebarnol/anaconda3/envs/abmarl36/lib/python3.6/site-packages/ray/worker.py", line 797, in init
    ray_params=ray_params)
  File "/Users/sebarnol/anaconda3/envs/abmarl36/lib/python3.6/site-packages/ray/node.py", line 230, in __init__
    self.start_head_processes()
  File "/Users/sebarnol/anaconda3/envs/abmarl36/lib/python3.6/site-packages/ray/node.py", line 861, in start_head_processes
    self.start_redis()
  File "/Users/sebarnol/anaconda3/envs/abmarl36/lib/python3.6/site-packages/ray/node.py", line 686, in start_redis
    port_denylist=self._ray_params.reserved_ports)
  File "/Users/sebarnol/anaconda3/envs/abmarl36/lib/python3.6/site-packages/ray/_private/services.py", line 891, in start_redis
    primary_redis_client.set("NumRedisShards", str(num_redis_shards))
  File "/Users/sebarnol/anaconda3/envs/abmarl36/lib/python3.6/site-packages/redis/client.py", line 1801, in set
    return self.execute_command('SET', *pieces)
  File "/Users/sebarnol/anaconda3/envs/abmarl36/lib/python3.6/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/Users/sebarnol/anaconda3/envs/abmarl36/lib/python3.6/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/Users/sebarnol/anaconda3/envs/abmarl36/lib/python3.6/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 60 connecting to 10.142.140.7:6379. Operation timed out.
[1]    87008 terminated  abmarl train examples/multi_corridor_example.py
~~~

Specifically, I ran the following:

~~~shell
conda create -n abmarl36 python=3.6
conda activate abmarl36
git clone https://github.com/LLNL/Abmarl/
cd Abmarl
pip install -r requirements.txt
pip install -e . --no-deps
abmarl train examples/multi_corridor_example.py
~~~

**Comment by seba-1511** [comment]
Other than that (and once I can confirm functionality), my only minor comment is on state of need/scholarship. The discussion around existing software around multi-agent RL could be more thorough; for example, here's some popular software that could be discussed:

* MADDPG, from OpenAI: https://github.com/openai/maddpg
* pymarl, from Oxford: https://github.com/oxwhirl/pymarl
* SMARTS, from Huawei: https://github.com/huawei-noah/SMARTS
* MAAC, from Shariq Iqbal: https://github.com/shariqiqbal2810/MAAC
* MarLo, from crowdAI: https://github.com/crowdAI/marLo

**Comment by abhiramm7** [comment]
@rusu24edward I've created two issues [168](https://github.com/LLNL/Abmarl/issues/168 ) and [167](https://github.com/LLNL/Abmarl/issues/167 ) regarding installation and documentation. The examples and documentation were really thorough; I would just recommend adding a note on dependencies in the installation instructions and also providing links the python files (e.g., `multi_corridor_example.py`) in tutorials. Beyond that, every else looks great.

**Comment by rusu24edward** [comment]
Thanks for the reviews! I will try to address each of these points by the end of the week.

**Comment by rusu24edward** [comment]
@seba-1511 Regarding your comment on other popular software that can be addressed, I'd be happy to include more discussion on comparisons with popular software, but I think it's important to clarify the suggestions you made as it will shed light on what ABMARL targets. Reinforcement learning has two components: simulation and algorithm (also commonly referred to as environment and agent). Our software targets the simulation component, so I restricted my discussion to other software that specifically targets the simulation component.

Regarding your suggestions:

**MADDPG**
This paper actually has both simulation and algorithm. The authors create a particle simulation (MPE) and a multi-agent algorithm that they benchmark against their simulation. While this is a popular paper, it is no longer maintained by the originators. The algorithm has since been folded in to RLlib, to which ABMARL connects, and the simulation has been folded into the Petting Zoo, which we do directly mention in our paper.
MADDPG actually highlights the importance of ABMARL. The creators of MADDPG chose to create a simulation in addition to the algorithm in order to benchmark their work. They made it from from scratch, and I argue that the simulation interface that Abmarl provides will greatly ease the burden on algorithm developers who want simple test beds for their multi-agent algorithms. (maybe this is a good sentence to add to the paper?)

**pymarl**
PyMarl is a collection of multi-agent algorithms, and each of the algorithms that they support is also supported in RLlib, to which ABMARL connects. Pymarl does not have its own simulation benchmark suite; it uses StarCraft, which we reference in our paper.

**MAAC**
Similar to pymarl, MAAC targets the algorithm component of RL, and the algorithm is supported in RLlib, to which ABMARL connects. It does not really create its own simulation suite. Instead, it creates a specific scenario within MPE (which is the simulation from MADDPG), which is folded into PettingZoo, which we do reference in our paper.

**SMARTS** and **MARLO**
Both of these packages do indeed target the simulation component of RL, and I would be happy to include them in my comparison if you think that would be beneficial. Like MAgent, Starcraft, and Neural MMO (already addressed in our paper), both of these also couple the interface with a simulation. I can add these two to the list that I mention in paragraph 2 of statement of need, or I can also expound on each of the packages I listed (include smarts and marlo). I tried to keep it short and sweet in the flavor of many JOSS papers I see, but I'm happy to add more. Suggestions?

**Comment by rusu24edward** [comment]
> Specifically, I ran the following:
> 
> ```shell
> conda create -n abmarl36 python=3.6
> conda activate abmarl36
> git clone https://github.com/LLNL/Abmarl/
> cd Abmarl
> pip install -r requirements.txt
> pip install -e . --no-deps
> abmarl train examples/multi_corridor_example.py
> ```

@seba-1511 Thanks for bringing this to my attention. I just ran a fresh virtual environment and did not get any error. We technically specify that python 3.7+ is required, can you try this again with python3.7?

**Comment by rusu24edward** [comment]
> I would just recommend adding a note on dependencies in the installation instructions and also providing links the python files (e.g., `multi_corridor_example.py`) in tutorials.

@abhiramm7 I've added links to the tutorials as you suggested.
I wasn't sure exactly what you meant for the dependency note in the installation instructions. Please take a look at [this PR](https://github.com/LLNL/Abmarl/pull/174) and let me know if this is what you had in mind.

**Comment by rusu24edward** [comment]
@abhiramm7 Thank you for your review so far. I believe I have followed up on all the points you have mentioned above. Please see my responses to the issues you created in Abmarl [here](https://github.com/LLNL/Abmarl/issues/167) and [here](https://github.com/LLNL/Abmarl/issues/168). Please let me know if there is still more to be done on these points or on any other part of the submission.

@seba-1511 Thank you for your review so far. My follow up was primarily asking for clarification [here](https://github.com/openjournals/joss-reviews/issues/3424#issuecomment-883812828) and requesting that you try the build again with Python3.7 [here](https://github.com/openjournals/joss-reviews/issues/3424#issuecomment-883880317). Please take a look when you get a chance.

**Comment by seba-1511** [comment]
@rusu24edward Thanks for the update.

Re related works: Thanks for the detailed answer. I think it's fine to keep the paper mostly as-is but since some of the above works also implement RL tasks I think they are worth mentioning, if only to highlight the need for Abmarl's simulation interface. This could be just 2-3 sentences, no need for a detailed comparison as above.

Re installation issues: Changing to Python 3.7 and upgrading Abmarl to the latest version (0.1.3) seems to have fixed it. Thank you.

**Comment by rusu24edward** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1613/jair.3912 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by rusu24edward** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03424/joss.03424/10.21105.joss.03424.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03424/joss.03424/10.21105.joss.03424.pdf) :page_facing_up: :point_left:

**Comment by rusu24edward** [comment]
@seba-1511 Thank you very much for your insights on the paper. I have updated it, and it now includes a short explanation on the two components of RL and a more detailed examination of related work. Take a look and let me know what you think. I see that you have checked everything on the checklist; please let me know if there's anything else I can do.

@abhiramm7 I hope my recent changes to the dependencies and documentation help clarify the environment in which Abmarl is supported. I think there are still a few things in your checklist, please take a look when you can and let me know if there's anything else I can do.

Thank you both!

**Comment by seba-1511** [comment]
Looks good to me.

**Comment by abhiramm7** [comment]
Looks great, thanks @rusu24edward

**Comment by drvinceknight** [comment]
Thank you @seba-1511 and @abhiramm7 for your work on this.

@abhiramm7 for completeness could I ask you to tick the last remaining tick boxes in the list at the top of this issue (just to make sure we are all on the same page)?

**Comment by abhiramm7** [comment]
@drvinceknight For sure.

**Comment by rusu24edward** [comment]
Hi @drvinceknight, it looks like all the tasks have been checked off, and based on the comments I believe I've done everything requested. Thank you abhiramm7 and seba-15111 for the great review!

What are the next steps?

**Comment by drvinceknight** [comment]
> Thank you abhiramm7 and seba-15111 for the great review!

Thank you @abhiramm7 and @seba-1511 :+1:

> What are the next steps?

I will proof read the paper and potentially make some final requests (about to do that now). *but* we're nearly there now :) :+1:

**Comment by drvinceknight** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03424/joss.03424/10.21105.joss.03424.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03424/joss.03424/10.21105.joss.03424.pdf) :page_facing_up: :point_left:

**Comment by drvinceknight** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1613/jair.3912 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by drvinceknight** [comment]
@whedon generate pdf from abmarl-87-interface-release

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03424/joss.03424/10.21105.joss.03424.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03424/joss.03424/10.21105.joss.03424.pdf) :page_facing_up: :point_left:

**Comment by drvinceknight** [comment]
@whedon check references from abmarl-87-interface-release

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1613/jair.3912 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by drvinceknight** [comment]
@rusu24edward can I just confirm which branch is the correct one? Is it still `abmarl-87-interface-release`?

**Comment by rusu24edward** [comment]
@drvinceknight Yes, this is the correct branch still.

**Comment by drvinceknight** [comment]
Thanks, the paper itself looks good but there are a number of missing DOIs that would be great if you could fix please.

For example `OpenGym` has the following as their citation instruction: https://github.com/openai/gym#citation

```
@misc{1606.01540,
  Author = {Greg Brockman and Vicki Cheung and Ludwig Pettersson and Jonas Schneider and John Schulman and Jie Tang and Wojciech Zaremba},
  Title = {OpenAI Gym},
  Year = {2016},
  Eprint = {arXiv:1606.01540},
}
```

Although `arXiv:1606.01540` is not technically a DOI it should still appear in the rendered pdf please.

There are a number of other references where the url to the paper is given but not the DOI, we'll need to change those please (or let me know if you're unable to find the DOI).

**Comment by rusu24edward** [comment]
Hi @drvinceknight, I updated the references so that each of them has a URL, only using an arxiv url when I was not able to find a different one. I was not able to find DOI's for any other papers. I used google's search and [cross ref](https://www.crossref.org/guestquery/), and only the arcade learning environment shows a DOI. Many of the references are conference proceedings, which I'm not sure if those get DOI's.

**Comment by drvinceknight** [comment]
Thanks!

**Comment by drvinceknight** [comment]
@whedon generate pdf from abmarl-87-interface-release

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03424/joss.03424/10.21105.joss.03424.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03424/joss.03424/10.21105.joss.03424.pdf) :page_facing_up: :point_left:

**Comment by drvinceknight** [comment]
@whedon check references from abmarl-87-interface-release

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1613/jair.3912 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by drvinceknight** [comment]
Thank you @rusu24edward, everything looks good to me.

Could you  make a tagged release and archive, and report the version number and archive DOI here?

Please make sure the archive deposit has same title and author list as the paper.

**Comment by rusu24edward** [comment]
@drvinceknight I have released version 0.1.4, and here is the DOI: 10.5281/zenodo.5196791

**Comment by rusu24edward** [comment]
@drvinceknight Did I provide the correct information? Is there more I need to do?

**Comment by drvinceknight** [comment]
Apologies for not getting back to you, I've been on leave. That all looks good to me.

**Comment by drvinceknight** [comment]
@whedon set 10.5281/zenodo.5196791 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.5196791" target="_blank">10.5281/zenodo.5196791</a> is the archive.

**Comment by drvinceknight** [comment]
@whedon set 0.1.4 as version

**Comment by whedon** [comment]
OK. 0.1.4 is the version.

**Comment by drvinceknight** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1613/jair.3912 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2523

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2523, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by drvinceknight** [comment]
@openjournals/joss-eics note that the branch from which the paper is to be built is `abmarl-87-interface-release`

**Comment by danielskatz** [comment]
@drvinceknight - I'm confused - you didn't do `@whedon recommend-accept from branch abmarl-87-interface-release`  Why not?

**Comment by danielskatz** [comment]
It appears the paper is the same in the branch and main, so I don't think it matters, but perhaps @drvinceknight or @rusu24edward could explain before we proceed?  In the meantime, I'll proofread the paper (and if changes are needed, suggest them in main)

**Comment by danielskatz** [comment]
👋 @rusu24edward - in any case (ignoring the branch vs main issue), there are a couple of small changes needed that I've indicated in https://github.com/LLNL/Abmarl/pull/195

If the paper in main is ok, then these can just be merged and we can proceed to publication with that branch of the paper.  If the paper in the other branch is different, these changes can be made there and we can publish using the paper in that branch. But again, I really don't understand what's going on with these two branches, as the paper appears the same in both, and that's the only thing that JOSS uses the branch for.

**Comment by drvinceknight** [comment]
> @drvinceknight - I'm confused - you didn't do `@whedon recommend-accept from branch abmarl-87-interface-release` Why not?

Apologies, I didn't realise that's what I should have done. Thanks for pointing it out.

**Comment by rusu24edward** [comment]
> It appears the paper is the same in the branch and main, so I don't think it matters, but perhaps drvinceknight or rusu24edward could explain before we proceed? In the meantime, I'll proofread the paper (and if changes are needed, suggest them in main)

@danielskatz I'm sorry for the confusion, I'll do my best to explain. Our software utilizes a release strategy similar to the [branch release stragey](https://nvie.com/posts/a-successful-git-branching-model/). We have our main branch, which contains active development that is not yet ready for release, and when we make releases we create a release branch off main. This review has been of our first release, which is on abmarl-87-interface-release, not the main branch. The paper is the same on both branches.

Submitting the changes to main is fine, I will duplicate them for the release branch.

**Comment by danielskatz** [comment]
The JOSS publication is of the paper, and it includes a pointer to the full repository, so there's no need to worry about the branch in this case, I don't think. Does this make sense?

**Comment by rusu24edward** [comment]
@danielskatz Yes, that makes sense.

**Comment by danielskatz** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1613/jair.3912 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2525

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2525, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1429893898957164545) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2526
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.03424](https://doi.org/10.21105/joss.03424)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by danielskatz** [comment]
Congratulations to @rusu24edward (Edward Rusu) and co-author!!

And thanks to @drvinceknight for editing, and @seba-1511 and @abhiramm7 for reviewing!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03424/status.svg)](https://doi.org/10.21105/joss.03424)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03424">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03424/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03424/status.svg
   :target: https://doi.org/10.21105/joss.03424
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03424/status.svg)](https://doi.org/10.21105/joss.03424)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by rusu24edward** [comment]
Thank you everyone very much for this awesome review process and publication. Looking forward to more!
