### ISSUE TITLE
[PRE REVIEW]: fractalRegression: An R package for multiscale regression and fractal analyses

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3499]
**Submitting author:** @aaronlikens (<a href="http://orcid.org/0000-0002-6535-5772">Aaron Likens</a>)
**Repository:** <a href="https://github.com/aaronlikens/fractalRegression/" target ="_blank">https://github.com/aaronlikens/fractalRegression/</a>
**Version:** 1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/d093dbc9c054ac40487548ac6b845a93/status.svg)](https://joss.theoj.org/papers/d093dbc9c054ac40487548ac6b845a93)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/d093dbc9c054ac40487548ac6b845a93"><img src="https://joss.theoj.org/papers/d093dbc9c054ac40487548ac6b845a93/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/d093dbc9c054ac40487548ac6b845a93/status.svg)](https://joss.theoj.org/papers/d093dbc9c054ac40487548ac6b845a93)
```

**Author instructions**

Thanks for submitting your paper to JOSS @aaronlikens. **Currently, there isn't an JOSS editor assigned** to your paper.

@aaronlikens if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.04 s (334.4 files/s, 158670.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Markdown                         2            231              0           3582
C++                              7            218            561            744
TeX                              1             23              0            284
R                                3             21            438             66
-------------------------------------------------------------------------------
SUM:                            13            493            999           4676
-------------------------------------------------------------------------------


Statistical information for the repository 'e2f562eb0514399275ebfceb' was
gathered on 2021/07/15.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Aaron Likens                     1          1523              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Aaron Likens               1523          100.0          0.0               36.84
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3499 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:146:in `check_fields': undefined method `keys' for #<String:0x0000562f6d576820> (NoMethodError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:89:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by danielskatz** [comment]
@aaronlikens - as you can see above, your code did not compile - please make the headers match those in the [example](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography).  Please make changes, then use the command `@whedon generate pdf` to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by danielskatz** [comment]
Also, due to the relatively small amount of code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  Having a paper that they can read will help them.  You should hear back sometime next week.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by travisjwiltshire** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03499/joss.03499/10.21105.joss.03499.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03499/joss.03499/10.21105.joss.03499.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @aaronlikens - I'm sorry to say that after discussion amongst the JOSS editors, we have decided that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.  I also apologize for the slower-than-expected decision process.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
