### ISSUE TITLE
[PRE REVIEW]: An R package for analyses of bioassays and probit graphs

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3512]
**Submitting author:** @piyalkarum (<a href="http://orcid.org/0000-0002-1934-145X">Piyal Karunarathne</a>)
**Repository:** <a href="https://github.com/milesilab/BioRssay.git" target ="_blank">https://github.com/milesilab/BioRssay.git</a>
**Version:** v0.9.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/73183faaf2c750eaaf0adaecc75d1f8f/status.svg)](https://joss.theoj.org/papers/73183faaf2c750eaaf0adaecc75d1f8f)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/73183faaf2c750eaaf0adaecc75d1f8f"><img src="https://joss.theoj.org/papers/73183faaf2c750eaaf0adaecc75d1f8f/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/73183faaf2c750eaaf0adaecc75d1f8f/status.svg)](https://joss.theoj.org/papers/73183faaf2c750eaaf0adaecc75d1f8f)
```

**Author instructions**

Thanks for submitting your paper to JOSS @piyalkarum. **Currently, there isn't an JOSS editor assigned** to your paper.

@piyalkarum if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 757

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.05 s (932.3 files/s, 149807.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            14            967            154           3371
Markdown                         3            126              0            623
CSS                              3             99             48            428
JavaScript                       4             65             35            267
R                                4             27            129            247
TeX                              1             15              0            113
YAML                             4             16              6             92
Rmd                              2             65            110             47
SVG                              9              0              1             19
-------------------------------------------------------------------------------
SUM:                            44           1380            483           5207
-------------------------------------------------------------------------------


Statistical information for the repository 'c71b85e47f3cd8bfbf4d3dc3' was
gathered on 2021/07/19.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Piyal Karunarathne               5          1101            734          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
piyalkarum                  367          100.0          0.0                9.54
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3512 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:72:in `block in build_affiliation_string': Problem with affiliations for Pierrick Labbé, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:71:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:71:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:205:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:205:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1038/hdy.2015.92 may be a valid DOI for title: High chlorpyrifos resistance in Culex pipiens mosquitoes: strong synergy between resistance genes
- 10.1186/1756-3305-7-299 may be a valid DOI for title: Insecticide resistance in disease vectors from Mayotte: an opportunity for integrated vector management
- 10.1371/journal.pntd.0007439 may be a valid DOI for title: Insecticide resistance levels and mechanisms in Aedes aegypti populations in and around Ouagadougou, Burkina Faso
- 10.1371/journal.pbio.2000618 may be a valid DOI for title: The ace-1 locus is amplified in all resistant Anopheles gambiae mosquitoes: fitness consequences of homogeneous and heterogeneous duplications
- 10.1007/s11829-021-09842-4 may be a valid DOI for title: Insecticidal activity of essential oils from six aromatic plants against Aedes aegypti, dengue vector from two localities of Ouagadougou, Burkina Faso
- 10.1371/journal.pone.0243992 may be a valid DOI for title: CYP450 core involvement in multiple resistance strains of Aedes aegypti from French Guiana highlighted by proteomics, molecular and biochemical studies
- 10.1038/s42003-021-02192-0 may be a valid DOI for title: Compensatory mechanisms in resistant Anopheles gambiae AcerKis and KdrKis neurons modulate insecticide-based mosquito control
- 10.1093/jee/18.2.265a may be a valid DOI for title: A method of computing the effectiveness of an insecticide
- 10.1371/journal.pone.0054092 may be a valid DOI for title: Acaricide, fungicide and drug interactions in honey bees (Apis mellifera)

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@piyalkarum - thanks for your submission.  Due to the relatively small amount of code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  You should hear back in a week or so.

In addition, you could work on the possibly missing DOIs that whedon suggests, but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

You should also make your paper compile - make sure that it follows the [example](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography), particularly in the header

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by piyalkarum** [comment]
I find "amoeba" and "rmflight" as two potential reviewers.

**Comment by piyalkarum** [comment]
@whedon check references
@whedon generate pdf

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/hdy.2015.92 is OK
- 10.1186/1756-3305-7-299 is OK
- 10.1371/journal.pntd.0007439 is OK
- 10.1371/journal.pbio.2000618 is OK
- 10.1007/s11829-021-09842-4 is OK
- 10.1371/journal.pone.0243992 is OK
- 10.1038/s42003-021-02192-0 is OK
- 10.1093/jee/18.2.265a is OK
- 10.1371/journal.pone.0054092 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by piyalkarum** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #3512 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:72:in `block in build_affiliation_string': Problem with affiliations for Pierrick Labbé, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:71:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:71:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:205:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:205:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by piyalkarum** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03512/joss.03512/10.21105.joss.03512.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03512/joss.03512/10.21105.joss.03512.pdf) :page_facing_up: :point_left:

**Comment by piyalkarum** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by piyalkarum** [comment]
@whedon check repository

**Comment by whedon** [comment]
Wordcount for `paper.md` is 758

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.10 s (432.5 files/s, 53425.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            13            619            149           2038
Markdown                         3            126              0            621
CSS                              3             99             48            428
R                                4             19            129            294
JavaScript                       4             65             35            267
TeX                              1             15              0            122
YAML                             5             16              6             96
Rmd                              2             65            111             47
SVG                              9              0              1             19
-------------------------------------------------------------------------------
SUM:                            44           1024            479           3932
-------------------------------------------------------------------------------


Statistical information for the repository '15a1d41972fa0f87cd08f339' was
gathered on 2021/07/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Piyal Karunarathne               5          1101            734          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
piyalkarum                  367          100.0          0.0                9.54
```

**Comment by piyalkarum** [comment]
@whedon check repository

**Comment by whedon** [comment]
Wordcount for `paper.md` is 758

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.07 s (588.5 files/s, 67432.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            12            526            144           1618
Markdown                         3            126              0            621
CSS                              3             99             48            428
R                                4             20            129            303
JavaScript                       4             65             35            267
TeX                              1             15              0            122
YAML                             5             16              6             96
Rmd                              2             65            111             47
SVG                              9              0              1             19
-------------------------------------------------------------------------------
SUM:                            43            932            474           3521
-------------------------------------------------------------------------------


Statistical information for the repository '11d1a591eba67e3ce9a35ed8' was
gathered on 2021/07/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Piyal Karunarathne               5          1101            734          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
piyalkarum                  367          100.0          0.0                9.54
```

**Comment by danielskatz** [comment]
@piyalkarum - I'm sorry to say that after discussion amongst the JOSS editors, we have decided that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
