### ISSUE TITLE
[PRE REVIEW]: Ensemble Learning for Harmonization and Annotation of Single Cells (ELeFHAnt)

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3516]
**Submitting author:** @praneet1988 (<a href="http://orcid.org/0000-0002-8713-6570">Praneet Chaturvedi</a>)
**Repository:** <a href="https://github.com/praneet1988/ELeFHAnt" target ="_blank">https://github.com/praneet1988/ELeFHAnt</a>
**Version:** v1.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/33ca7c505baa490d5690b7d2191a8cbd/status.svg)](https://joss.theoj.org/papers/33ca7c505baa490d5690b7d2191a8cbd)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/33ca7c505baa490d5690b7d2191a8cbd"><img src="https://joss.theoj.org/papers/33ca7c505baa490d5690b7d2191a8cbd/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/33ca7c505baa490d5690b7d2191a8cbd/status.svg)](https://joss.theoj.org/papers/33ca7c505baa490d5690b7d2191a8cbd)
```

**Author instructions**

Thanks for submitting your paper to JOSS @praneet1988. **Currently, there isn't an JOSS editor assigned** to your paper.

@praneet1988 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 938

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.csbj.2021.01.015 is OK
- 10.15252/msb.20209620 is OK
- 10.1186/s13059-019-1795-z is OK
- 10.1016/j.cell.2019.05.031 is OK
- 10.1016/j.cell.2020.12.016 is OK
- 10.1016/j.cell.2021.04.028 is OK
- 10.1016/j.devcel.2020.11.010 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.01 s (557.4 files/s, 103253.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                                1            103             65            582
Markdown                         2            129              0            324
TeX                              1              6              0             63
Rmd                              4             23            167             20
-------------------------------------------------------------------------------
SUM:                             8            261            232            989
-------------------------------------------------------------------------------


Statistical information for the repository '3b690d306a258ec518249ca2' was
gathered on 2021/07/20.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3516 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:204:in `block in parse_authors': Author (Konrad Thorner) is missing affiliation (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by danielskatz** [comment]
@praneet1988 - thanks for your submission.  Due to the relatively small amount of code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  You should hear back in a week or so.

In addition, you could work on the error in the code - then use the command `@whedon generate pdf` to make a new PDF. Whedon commands need to be the first entry in a new comment.  Refer to the [example paper](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography)

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kthorner** [comment]
@whedon generate pdf

I believe I have made the necessary corrections. Thank you!

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03516/joss.03516/10.21105.joss.03516.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03516/joss.03516/10.21105.joss.03516.pdf) :page_facing_up: :point_left:

**Comment by praneet1988** [comment]
@danielskatz Thank you so much for your reply. @kthorner and I look forward to hear from you.
We have corrected the compile pdf issue.

Thank you so much.

Best,
Praneet

**Comment by kthorner** [comment]
@whedon generate pdf

Generating the final version of the PDF so figures display correctly.

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03516/joss.03516/10.21105.joss.03516.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03516/joss.03516/10.21105.joss.03516.pdf) :page_facing_up: :point_left:

**Comment by praneet1988** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03516/joss.03516/10.21105.joss.03516.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03516/joss.03516/10.21105.joss.03516.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
Sorry, our process was a bit slower than expected.

I'm sorry to say that after discussion amongst the JOSS editors, we have decided that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by praneet1988** [comment]
Dear @danielskatz,
Thank you so much for getting back to us.

Appreciate your time and effort.

Best,
Praneet
