### ISSUE TITLE
[REVIEW]: pytreegrav: a fast Python gravity solver

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3675]
**Submitting author:** @mikegrudic (<a href="http://orcid.org/0000-0002-1655-5604">Michael Grudi´c</a>)
**Repository:** <a href="https://github.com/mikegrudic/pytreegrav" target ="_blank">https://github.com/mikegrudic/pytreegrav</a>
**Version:** 1.0.0
**Editor:** @dfm
**Reviewer:** @adrn, @maxwelltsai
**Archive:** <a href="https://doi.org/10.5281/zenodo.5807909" target="_blank">10.5281/zenodo.5807909</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/8345d6e5664943ae019a0d80a5eece99/status.svg)](https://joss.theoj.org/papers/8345d6e5664943ae019a0d80a5eece99)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/8345d6e5664943ae019a0d80a5eece99"><img src="https://joss.theoj.org/papers/8345d6e5664943ae019a0d80a5eece99/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/8345d6e5664943ae019a0d80a5eece99/status.svg)](https://joss.theoj.org/papers/8345d6e5664943ae019a0d80a5eece99)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/mikegrudic/pytreegrav" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@adrn & @maxwelltsai, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @dfm know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @adrn
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/mikegrudic/pytreegrav">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mikegrudic/pytreegrav">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mikegrudic) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @maxwelltsai
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/mikegrudic/pytreegrav">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mikegrudic/pytreegrav">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mikegrudic) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] #3785
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @adrn, @maxwelltsai it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1239

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1145/2833157.2833162 is OK
- 10.1016/S1384-1076(96)00009-7 is OK
- 10.1093/mnras/staa2578 is OK
- 10.1006/jcph.1994.1050 is OK
- 10.1093/mnras/71.5.460 is OK
- 10.1088/0004-637X/762/2/109 is OK
- 10.1093/mnras/sty2303 is OK
- 10.1093/mnras/stz3527 is OK
- 10.1046/j.1365-8711.1999.02613.x is OK
- 10.1093/mnras/stv195 is OK
- 10.1111/j.1365-2966.2005.09655.x is OK
- 10.1093/mnras/stu1421 is OK
- 10.1093/mnras/sty1690 is OK
- 10.1140/epjp/i2011-11055-3 is OK
- 10.1038/324446a0 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (285.5 files/s, 44248.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          12            256            399           1343
TeX                              1             27              0            263
Markdown                         2             65              0            143
Jupyter Notebook                 1              0            237             50
TOML                             1              0              0              6
YAML                             1              0              0              1
-------------------------------------------------------------------------------
SUM:                            18            348            636           1806
-------------------------------------------------------------------------------


Statistical information for the repository '4de020fcbc18a287478668eb' was
gathered on 2021/08/31.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Alex Gurvich                     7           862            557           23.38
Ben Keller                       4            33             16            0.81
Michael Grudic                  10           499             59            9.19
Mike Grudic                     27          2390           1215           59.39
Mike Grudić                      7           250            187            7.20
omgspace                         1             0              2            0.03

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Alex Gurvich                132           15.3          1.5               11.36
Ben Keller                   18           54.5          1.3                0.00
Michael Grudic               45            9.0         47.2                0.00
Mike Grudic                1798           75.2          0.9                6.28
Mike Grudić                   5            2.0         20.9               20.00
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03675/joss.03675/10.21105.joss.03675.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03675/joss.03675/10.21105.joss.03675.pdf) :page_facing_up: :point_left:

**Comment by dfm** [comment]
@mikegrudic, @adrn, @maxwelltsai – This is the review thread for the paper. All of our communications will happen here from now on. Thanks again for agreeing to participate!

Please read the "Reviewer instructions & questions" in the first comment above.

Both reviewers have checklists at the top of this thread (in that first comment) with the JOSS requirements. As you go over the submission, please check any items that you feel have been satisfied. There are also links to the JOSS reviewer guidelines.

The JOSS review is different from most other journals. Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, the reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention `openjournals/joss-reviews#3675` so that a link is created to this thread (and I can keep an eye on what is happening). Please also feel free to comment and ask questions on this thread. In my experience, it is better to post comments/questions/suggestions as you come across them instead of waiting until you've reviewed the entire package.

We aim for the review process to be completed within about 4-6 weeks but please make a start well ahead of this as JOSS reviews are by their nature iterative and any early feedback you may be able to provide to the author will be very helpful in meeting this schedule.

**Comment by whedon** [comment]
:wave: @maxwelltsai, please update us on how your review is going (this is an automated reminder).

**Comment by whedon** [comment]
:wave: @adrn, please update us on how your review is going (this is an automated reminder).

**Comment by adrn** [comment]
@mikegrudic The submitted paper is excellent: concise, clearly written, and I don't have any comments or edits to suggest - nice work! Comments on the code are in: mikegrudic/pytreegrav#12

**Comment by maxwelltsai** [comment]
@dfm @whedon It seems that the paper link is broken. I can no longer download the paper proof from this page: https://github.com/openjournals/joss-reviews/issues/3406#issuecomment-868250511

Has it been transferred to somewhere else? I did find the `paper.md` file on the code repo, but I am wondering whether this is the paper itself.

**Comment by dfm** [comment]
@maxwelltsai: There is a new link just a few comments up ☝️: https://github.com/openjournals/joss-reviews/issues/3675#issuecomment-909502893 That one's working for me - does it work for you too?

**Comment by mikegrudic** [comment]
Hi all, thanks a lot for the helpful input. Should be able to address and respond to comments within the next month. In particular proper documentation and potentially automated testing are forthcoming.

**Comment by mikegrudic** [comment]
Thanks to @maxwelltsai and @adrn for taking the time to give useful feedback. The package has been revised extensively, and in particular we now have [sphinx documentation](https://pytreegrav.readthedocs.io/en/latest/) and an automated `pytest` test. This contains a lot of the additional content requested in your reviews. There is still a ways to go to fully document the codebase, but at least all of the frontend API functions are fully documented now. Further feedback on this is welcome.

Responding to some specific points apart from the general suggestion of expanded documentation, first by @adrn:

>     * I don't see any mention of what profile is used to soften the point mass potentials when `h` is provided. Is there a standard profile to use (i.e. Plummer?), or is this configurable? It would be good to explicitly state this in the documentation.
> 

We mention in the paper that the softened force is that of a cubic M4 spline mass distribution and provide the reference for the specific mathematical expressions. We now also clarify this in the API documentation, where the respective softening arguments are documented.

>     * Though the details of code style can be subjective, Python packages generally at least follow the convention (laid out in PEP 8) that class names follow [the CapWords convention](https://www.python.org/dev/peps/pep-0008/#class-names) and [function names are lower case](https://www.python.org/dev/peps/pep-0008/#id43). Please consider reformatting the functions in this package to follow PEP8 guidelines.

In a vacuum I'd like to do this, but at this point I am disinclined for fear of causing headaches and confusion for the various projects that are already using this package, many of which I do not own.

 And @maxwelltsai's points:

> @mikegrudic, @dfm I have finished the review. Apart from the comments from @adrn, I have the following comments:
> 
>     * I would suggest that the authors add the dependent packages (e.g., `numpy`, `numba`) into their `setup.py`. This allows the dependency to automatically sorted out when the users install the package.
> 
Done.

>     * I assume that the library works with any version of Python 3.x. If the package requires a specific version of Python, it would be good to document this as well.
>     * I notice that `pytreegrav` is already on PyPI. I would also suggest the authors to document in their GitHub repository (and also mention in the paper) that the package can be installed using PyPI: `pip install pytreegrav`. Some users may find it easier to directly install the package with `pip` rather than having to clone the code and run `setup.py`.
> 

Done, see the installation section of the documentation.

>     * The package is designed for the specific purpose of calculating the potential and accelerations. I understand that it is a software library to be integrated into a Python N-body integrator, but it would be great if the authors could demonstrate this by implementing a simple integrator (e.g., LeapFrog) with `pytreegrav`. This can be done within a Jupyter notebook and/or a standalone python script. I would also suggest that the authors to add a directory `examples/` in the root of their repository, which contains all these examples for new users to get started.
> 
Done, see `examples/Nbody_integrator.ipynb`

>     * Since the authors use the JIT decorator in `numpy` to parallelise the computation on CPUs, is there any reason that they didn't try to use `cuda.jit` for GPU parallelisation?

Just that I've never personally been able to get numba's cuda interface working on any system of my own 🤷‍♂️ this is probably possible, because the tree structure is really a set of float/int arrays for which the Octree instance serves as a wrapper, so one could write a kernel that just accepts the unpacked arrays as arguments, and otherwise run the same loop as in the CPU treewalk functions. I encourage anyone interested to give this a shot.

**Comment by dfm** [comment]
👋 Pinging @adrn and @maxwelltsai to take a look at @mikegrudic's response to your comments ☝️

**Comment by adrn** [comment]
Thanks @mikegrudic for addressing my comments! Your responses above are reasonable and the new documentation site looks good. I'm satistifed!

**Comment by maxwelltsai** [comment]
Thanks @mikegrudic for addressing my comments. On my side I am happy to recommend the paper for publication.

**Comment by dfm** [comment]
@adrn, @maxwelltsai: Thanks for your updates. Can you both go through [your checklists up at the top of this thread](https://github.com/openjournals/joss-reviews/issues/3675#issue-984176521), because I'm still seeing a lot of un-checked boxes. Thanks!

**Comment by dfm** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1145/2833157.2833162 is OK
- 10.1016/S1384-1076(96)00009-7 is OK
- 10.1093/mnras/staa2578 is OK
- 10.1006/jcph.1994.1050 is OK
- 10.1093/mnras/71.5.460 is OK
- 10.1088/0004-637X/762/2/109 is OK
- 10.1093/mnras/sty2303 is OK
- 10.1093/mnras/stz3527 is OK
- 10.1046/j.1365-8711.1999.02613.x is OK
- 10.1093/mnras/stv195 is OK
- 10.1111/j.1365-2966.2005.09655.x is OK
- 10.1093/mnras/stu1421 is OK
- 10.1093/mnras/sty1690 is OK
- 10.1140/epjp/i2011-11055-3 is OK
- 10.1038/324446a0 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by dfm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03675/joss.03675/10.21105.joss.03675.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03675/joss.03675/10.21105.joss.03675.pdf) :page_facing_up: :point_left:

**Comment by dfm** [comment]
@mikegrudic I've just opened [a small PR](https://github.com/mikegrudic/pytreegrav/pull/13) over on your repo. Once you've checked that out and merged, here are a few last steps for you, then we'll be ready to go!

1. Comment `@whedon generate pdf`, then take one last read through the manuscript to make sure that you're happy with it (it's harder to make changes later!), especially the author names and affiliations. I've taken a pass and it looks good to me!
2. Increment the version number of the software and report that version number back here.
3. Create an archived release of that version of the software (using Zenodo or something similar). **Please make sure that the metadata (title and author list) exactly match the paper.** Then report the DOI of the release back to this thread.

**Comment by mikegrudic** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03675/joss.03675/10.21105.joss.03675.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03675/joss.03675/10.21105.joss.03675.pdf) :page_facing_up: :point_left:

**Comment by mikegrudic** [comment]
@dfm thanks for your work on this. I have incremented the version to 1.0.0, and have uploaded the version to zenodo: 10.5281/zenodo.5807909

**Comment by dfm** [comment]
@whedon set 1.0.0 as version

**Comment by whedon** [comment]
OK. 1.0.0 is the version.

**Comment by dfm** [comment]
@whedon set 10.5281/zenodo.5807909 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.5807909" target="_blank">10.5281/zenodo.5807909</a> is the archive.

**Comment by dfm** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1145/2833157.2833162 is OK
- 10.1016/S1384-1076(96)00009-7 is OK
- 10.1093/mnras/staa2578 is OK
- 10.1006/jcph.1994.1050 is OK
- 10.1093/mnras/71.5.460 is OK
- 10.1088/0004-637X/762/2/109 is OK
- 10.1093/mnras/sty2303 is OK
- 10.1093/mnras/stz3527 is OK
- 10.1046/j.1365-8711.1999.02613.x is OK
- 10.1093/mnras/stv195 is OK
- 10.1111/j.1365-2966.2005.09655.x is OK
- 10.1093/mnras/stu1421 is OK
- 10.1093/mnras/sty1690 is OK
- 10.1140/epjp/i2011-11055-3 is OK
- 10.1038/324446a0 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3675 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:72:in `block in build_affiliation_string': Problem with affiliations for Michael Grudić, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:71:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:71:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:205:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:205:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:87:in `compile'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by dfm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03675/joss.03675/10.21105.joss.03675.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03675/joss.03675/10.21105.joss.03675.pdf) :page_facing_up: :point_left:

**Comment by dfm** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1145/2833157.2833162 is OK
- 10.1016/S1384-1076(96)00009-7 is OK
- 10.1093/mnras/staa2578 is OK
- 10.1006/jcph.1994.1050 is OK
- 10.1093/mnras/71.5.460 is OK
- 10.1088/0004-637X/762/2/109 is OK
- 10.1093/mnras/sty2303 is OK
- 10.1093/mnras/stz3527 is OK
- 10.1046/j.1365-8711.1999.02613.x is OK
- 10.1093/mnras/stv195 is OK
- 10.1111/j.1365-2966.2005.09655.x is OK
- 10.1093/mnras/stu1421 is OK
- 10.1093/mnras/sty1690 is OK
- 10.1140/epjp/i2011-11055-3 is OK
- 10.1038/324446a0 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2851

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2851, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by dfm** [comment]
@mikegrudic: Thanks for all your work here! I've handed this off to the EiC team who may have some final edits before processing for publication. Thanks for your submission and your participation in this process!!

@adrn, @maxwelltsai: I really appreciate the time that you volunteered here, and for your thorough and constructive reviews. We couldn't do this without you, so thanks so much for your help!

**Comment by mikegrudic** [comment]
Thanks again everyone!

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1475931427585863680) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2852
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.03675](https://doi.org/10.21105/joss.03675)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@adrn, @maxwelltsai – many thanks for your reviews here and to @dfm for editing this submission! JOSS relies upon the volunteer effort of people like you and we simply wouldn't be able to do this without you ✨ 

@mikegrudic – your paper is now accepted and published in JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03675/status.svg)](https://doi.org/10.21105/joss.03675)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03675">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03675/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03675/status.svg
   :target: https://doi.org/10.21105/joss.03675
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03675/status.svg)](https://doi.org/10.21105/joss.03675)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by arfon** [comment]
Also, I meant to say that this was JOSS' 1500th published paper! 🎉
