### ISSUE TITLE
[REVIEW]: AMAT: A Python package for rapid conceptual design of aerocapture and atmospheric Entry, Descent, and Landing (EDL) missions in a Jupyter environment

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3710]
**Submitting author:** @athulpg007 (<a href="http://orcid.org/0000-0002-9326-3293">Athul Pradeepkumar Girija</a>)
**Repository:** <a href="https://github.com/athulpg007/AMAT" target ="_blank">https://github.com/athulpg007/AMAT</a>
**Version:** v2.2.3
**Editor:** @jbytecode
**Reviewer:** @astrojuanlu, @helgee
**Archive:** <a href="https://doi.org/10.5281/zenodo.5650129" target="_blank">10.5281/zenodo.5650129</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/57c18b7854b74d83e75250857716e229/status.svg)](https://joss.theoj.org/papers/57c18b7854b74d83e75250857716e229)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/57c18b7854b74d83e75250857716e229"><img src="https://joss.theoj.org/papers/57c18b7854b74d83e75250857716e229/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/57c18b7854b74d83e75250857716e229/status.svg)](https://joss.theoj.org/papers/57c18b7854b74d83e75250857716e229)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/athulpg007/AMAT" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@astrojuanlu & @helgee, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @jbytecode know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @astrojuanlu
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/athulpg007/AMAT">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/athulpg007/AMAT">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@athulpg007) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @helgee
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/athulpg007/AMAT">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/athulpg007/AMAT">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@athulpg007) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @astrojuanlu, @helgee it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1142

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/AERO.2010.5447017 is OK
- 10.1109/AERO.2002.1035313 is OK
- 10.17226/13117 is OK
- 10.2514/6.2003-2172 is OK
- 10.2514/1.2589 is OK
- 10.2514/1.A34121 is OK
- 10.2514/1.A34056 is OK
- 10.2514/1.A34719 is OK
- 10.2514/1.A34529 is OK
- 10.2514/1.A33997 is OK
- 10.2514/6.2007-605 is OK
- 10.2514/1.A34703 is OK
- 10.2514/1.13095 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by jbytecode** [comment]
@whedon check references

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03710/joss.03710/10.21105.joss.03710.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03710/joss.03710/10.21105.joss.03710.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/AERO.2010.5447017 is OK
- 10.1109/AERO.2002.1035313 is OK
- 10.17226/13117 is OK
- 10.2514/6.2003-2172 is OK
- 10.2514/1.2589 is OK
- 10.2514/1.A34121 is OK
- 10.2514/1.A34056 is OK
- 10.2514/1.A34719 is OK
- 10.2514/1.A34529 is OK
- 10.2514/1.A33997 is OK
- 10.2514/6.2007-605 is OK
- 10.2514/1.A34703 is OK
- 10.2514/1.13095 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=4.75 s (40.4 files/s, 20854.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            75          11312             75          41553
JavaScript                      11           2144           2126           8152
Jupyter Notebook                63              0          14124           5419
Python                          18           1973           3746           3902
SVG                              1              0              0           2671
CSS                              4            164             34            641
TeX                              1             25              0            196
Markdown                         2             96              0            179
reStructuredText                14            138            144            167
DOS Batch                        1              8              1             26
make                             1              4              7              9
YAML                             1              0              0              3
-------------------------------------------------------------------------------
SUM:                           192          15864          20257          62918
-------------------------------------------------------------------------------


Statistical information for the repository 'd5800a3257896aa4b39ed359' was
gathered on 2021/09/09.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Athul P. Girija                 30         46315          25145          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Athul P. Girija           29348           63.4          8.8               13.79
```

**Comment by jbytecode** [comment]
Dear @astrojuanlu and @helgee, 

Thank you for accepting our invitation. Here is the review issue. There are 20 check items for each reviewer. Whenever you finish the corresponding item, you can check it. You can interact with the authors and the editor. Please do not hesitate to ask me if you have difficulties. 

Thank you in advance!

**Comment by astrojuanlu** [comment]
I did a first pass, and opened https://github.com/athulpg007/AMAT/issues/3 and https://github.com/athulpg007/AMAT/issues/4 accordingly. In addition, I didn't see automated tests or contribution instructions, so for now I left those checkboxes unchecked. I still have to go over the rest.

**Comment by athulpg007** [comment]
I have addressed [athulpg007/AMAT/#/3](https://github.com/athulpg007/AMAT/#/3) and [athulpg007/AMAT/#/4](https://github.com/athulpg007/AMAT/#/4). 

I will add some tests and contribution instructions later today. Thanks!

**Comment by athulpg007** [comment]
Added some tests and contribution instructions. Sorry for my late response.

**Comment by jbytecode** [comment]
@athulpg007 thank you for adding tests. It is also a good practice to add a GitHub action that performs the tests after a commit so people can see the latest changes don't break the package.

**Comment by athulpg007** [comment]
@jbytecode thanks for the comment, I will set up the GitHub action as suggested.

**Comment by whedon** [comment]
:wave: @astrojuanlu, please update us on how your review is going (this is an automated reminder).

**Comment by whedon** [comment]
:wave: @helgee, please update us on how your review is going (this is an automated reminder).

**Comment by athulpg007** [comment]
License has been updated to GPL-v3-or-later. Updated up header text from some files with the old CC-BY-SA-4.0 license text to reflect the new license. If this issue if resolved, I will close [athulpg007/AMAT/#3](https://github.com/athulpg007/AMAT/issues/3).

Removed pandas and jupyterlab from setup.py Listed package and readthedocs build dependencies in docs/requirements.txt. See if this resolves [athulpg007/AMAT/#5](https://github.com/athulpg007/AMAT/issues/5)

Added GitHub action to perform tests after a commit.

**Comment by jbytecode** [comment]
> Added GitHub action to perform tests after a commit.

Great! Thank you. @athulpg007

**Comment by helgee** [comment]
Quick note @athulpg007: I have verified that the Linux installation instructions are valid for macOS as well.

**Comment by athulpg007** [comment]
Hi @astrojuanlu, just a gentle reminder about the review. Let me know if there are any issues. Appreciate your response. Thanks!

**Comment by astrojuanlu** [comment]
Hi all, sorry for the delay - I'm finishing my review right now 🙏🏽

**Comment by astrojuanlu** [comment]
Issues updated, review finished, everything looks good to me. Happy to accept this submission ✔️

**Comment by athulpg007** [comment]
@astrojuanlu thanks for your response and valuable review!

**Comment by jbytecode** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/AERO.2010.5447017 is OK
- 10.1109/AERO.2002.1035313 is OK
- 10.17226/13117 is OK
- 10.2514/6.2003-2172 is OK
- 10.2514/1.2589 is OK
- 10.2514/1.A34121 is OK
- 10.2514/1.A34056 is OK
- 10.2514/1.A34719 is OK
- 10.2514/1.A34529 is OK
- 10.2514/1.A33997 is OK
- 10.2514/6.2007-605 is OK
- 10.2514/1.A34703 is OK
- 10.2514/1.13095 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by jbytecode** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03710/joss.03710/10.21105.joss.03710.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03710/joss.03710/10.21105.joss.03710.pdf) :page_facing_up: :point_left:

**Comment by jbytecode** [comment]
Dear @athulpg007 

- [ ] I sent a pull request (https://github.com/athulpg007/AMAT/pull/7) that includes typo / language correction and possible enhancements. If you agree with them, please apply.
 
- [ ] Please re-check the whole paper by means of both language and format (one more time). When it is finished, please ping me here.

- [ ] make a tagged release and archive (e.g. with [Zenodo](https://zenodo.org/)) as described [here](<https://joss.readthedocs.io/en/latest/submitting.html#the-review-process>), and report the version number and archive DOI in this thread. Please verify that the archive deposit has the correct metadata (title and author list), or edit these if that is not the case.

- [ ] use the format vx.y.z as your versioning format.

Thank you in advance.

**Comment by athulpg007** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03710/joss.03710/10.21105.joss.03710.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03710/joss.03710/10.21105.joss.03710.pdf) :page_facing_up: :point_left:

**Comment by athulpg007** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03710/joss.03710/10.21105.joss.03710.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03710/joss.03710/10.21105.joss.03710.pdf) :page_facing_up: :point_left:

**Comment by jbytecode** [comment]
@athulpg007 

Could you please correct me if I am wrong with the line 60: 

-  Figure 3 shows example trajectories for a drag modulation system at Mars computed by using AMAT.

means 

-  Figure 3 shows `an` example `of` trajectories for a drag modulation system at Mars computed by using AMAT.

or something else? If yes, please correct all of the Figure descriptions. Thank you.

**Comment by athulpg007** [comment]
@jbytecode I agree with you. I'm working on the corrections. I will ping you when I am done.

**Comment by athulpg007** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03710/joss.03710/10.21105.joss.03710.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03710/joss.03710/10.21105.joss.03710.pdf) :page_facing_up: :point_left:

**Comment by athulpg007** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #3710 with the following error: 
```
 /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/net/http.rb:949:in `rescue in block in connect': Failed to open TCP connection to joss.theoj.org:443 (getaddrinfo: Name or service not known) (SocketError)
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/net/http.rb:946:in `block in connect'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/timeout.rb:103:in `timeout'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/net/http.rb:945:in `connect'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/net/http.rb:919:in `start'
	from /app/vendor/bundle/ruby/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
	from /app/vendor/bundle/ruby/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
	from /app/vendor/bundle/ruby/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
	from /app/vendor/bundle/ruby/2.6.0/gems/rest-client-2.1.0/lib/restclient.rb:66:in `get'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/compilers.rb:111:in `pdf_from_markdown'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/compilers.rb:13:in `generate_pdf'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:59:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'
/app/vendor/ruby-2.6.6/lib/ruby/2.6.0/net/http.rb:947:in `initialize': getaddrinfo: Name or service not known (SocketError)
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/net/http.rb:947:in `open'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/net/http.rb:947:in `block in connect'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/timeout.rb:103:in `timeout'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/net/http.rb:945:in `connect'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/net/http.rb:919:in `start'
	from /app/vendor/bundle/ruby/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
	from /app/vendor/bundle/ruby/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
	from /app/vendor/bundle/ruby/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
	from /app/vendor/bundle/ruby/2.6.0/gems/rest-client-2.1.0/lib/restclient.rb:66:in `get'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/compilers.rb:111:in `pdf_from_markdown'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/compilers.rb:13:in `generate_pdf'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:59:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03710/joss.03710/10.21105.joss.03710.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03710/joss.03710/10.21105.joss.03710.pdf) :page_facing_up: :point_left:

**Comment by athulpg007** [comment]
Hi @jbytecode : 

1. I accepted the suggested edits. Based on the suggestions, I made some additional corrections and checked the paper. If there are still any language/format issues, I am happy to revise further. 
2. Zenodo archive version number: v2.2.3, DOI: 10.5281/zenodo.5650129.

Thanks!

**Comment by jbytecode** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/AERO.2010.5447017 is OK
- 10.1109/AERO.2002.1035313 is OK
- 10.2514/6.2003-2172 is OK
- 10.2514/1.2589 is OK
- 10.2514/1.A34121 is OK
- 10.2514/1.A34056 is OK
- 10.2514/1.A34719 is OK
- 10.2514/1.A34529 is OK
- 10.2514/1.A33997 is OK
- 10.2514/6.2007-605 is OK
- 10.2514/1.A34703 is OK
- 10.2514/1.13095 is OK

MISSING DOIs

- 10.17226/13117 may be a valid DOI for title: Vision and Voyages for Planetary Science in the Decade 2013-2022

INVALID DOIs

- None
```

**Comment by jbytecode** [comment]
@athulpg007 could you please correct the missing DOI issue as Whedon suggested above?

**Comment by jbytecode** [comment]
@whedon set v2.2.3 as version

**Comment by whedon** [comment]
OK. v2.2.3 is the version.

**Comment by athulpg007** [comment]
@jbytecode applied pull request to correct missing DOI. Thank you for the edit.

**Comment by athulpg007** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/AERO.2010.5447017 is OK
- 10.1109/AERO.2002.1035313 is OK
- 10.17226/13117 is OK
- 10.2514/6.2003-2172 is OK
- 10.2514/1.2589 is OK
- 10.2514/1.A34121 is OK
- 10.2514/1.A34056 is OK
- 10.2514/1.A34719 is OK
- 10.2514/1.A34529 is OK
- 10.2514/1.A33997 is OK
- 10.2514/6.2007-605 is OK
- 10.2514/1.A34703 is OK
- 10.2514/1.13095 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by jbytecode** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/AERO.2010.5447017 is OK
- 10.1109/AERO.2002.1035313 is OK
- 10.17226/13117 is OK
- 10.2514/6.2003-2172 is OK
- 10.2514/1.2589 is OK
- 10.2514/1.A34121 is OK
- 10.2514/1.A34056 is OK
- 10.2514/1.A34719 is OK
- 10.2514/1.A34529 is OK
- 10.2514/1.A33997 is OK
- 10.2514/6.2007-605 is OK
- 10.2514/1.A34703 is OK
- 10.2514/1.13095 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by jbytecode** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03710/joss.03710/10.21105.joss.03710.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03710/joss.03710/10.21105.joss.03710.pdf) :page_facing_up: :point_left:

**Comment by jbytecode** [comment]
@whedon set 10.5281/zenodo.5650129 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.5650129" target="_blank">10.5281/zenodo.5650129</a> is the archive.

**Comment by jbytecode** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/AERO.2010.5447017 is OK
- 10.1109/AERO.2002.1035313 is OK
- 10.17226/13117 is OK
- 10.2514/6.2003-2172 is OK
- 10.2514/1.2589 is OK
- 10.2514/1.A34121 is OK
- 10.2514/1.A34056 is OK
- 10.2514/1.A34719 is OK
- 10.2514/1.A34529 is OK
- 10.2514/1.A33997 is OK
- 10.2514/6.2007-605 is OK
- 10.2514/1.A34703 is OK
- 10.2514/1.13095 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2732

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2732, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1457728639999614982) 👈 🐦🐦🐦

**Comment by kyleniemeyer** [comment]
Congratulations @athulpg007 on your article's publication in JOSS!

Many thanks to @astrojuanlu and @helgee for reviewing this, and @jbytecode for editing.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03710/status.svg)](https://doi.org/10.21105/joss.03710)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03710">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03710/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03710/status.svg
   :target: https://doi.org/10.21105/joss.03710
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03710/status.svg)](https://doi.org/10.21105/joss.03710)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by athulpg007** [comment]
Dear @kyleniemeyer @jbytecode @astrojuanlu @helgee,

Thank you all for your efforts!

I added my name to the reviewer list, and made a small donation to support the journal.
