### ISSUE TITLE
[REVIEW]: SPbLA: The Library of GPGPU-powered Sparse Boolean Linear Algebra Operations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3743]
**Submitting author:** @EgorOrachyov (<a href="http://orcid.org/0000-0002-0424-4059">Egor Orachev</a>)
**Repository:** https://github.com/JetBrains-Research/spbla
**Branch with paper.md** (empty if default branch): joss-paper
**Version:** v1.0.0
**Editor:** @Nikoleta-v3
**Reviewers:** @mlxd, @bencardoen
**Archive:** 10.5281/zenodo.7009938

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/1da10be51ab03b0f574f2fda4aabc3f9/status.svg)](https://joss.theoj.org/papers/1da10be51ab03b0f574f2fda4aabc3f9)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/1da10be51ab03b0f574f2fda4aabc3f9"><img src="https://joss.theoj.org/papers/1da10be51ab03b0f574f2fda4aabc3f9/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/1da10be51ab03b0f574f2fda4aabc3f9/status.svg)](https://joss.theoj.org/papers/1da10be51ab03b0f574f2fda4aabc3f9)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/JetBrains-Research/spbla" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@abb58 & @mlxd, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @Nikoleta-v3 know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @abb58
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/JetBrains-Research/spbla">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [ ] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [ ] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/JetBrains-Research/spbla">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Contribution and authorship:** Has the submitting author (@EgorOrachyov) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [ ] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @mlxd
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/JetBrains-Research/spbla">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/JetBrains-Research/spbla">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@EgorOrachyov) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @abb58, @mlxd it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 394

**Comment by whedon** [comment]
PDF failed to compile for issue #3743 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:155:in `block in check_orcids': Problem with ORCID (0000-0000-0000-0000) for Egor Orachev^[co-first author] (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:153:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:153:in `check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:90:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1186/1471-2105-14-149 is OK
- 10.1145/2499370.2462159 is OK
- 10.1145/3210259.3210264 is OK
- 10.1007/978-3-030-54832-2_6 is OK

MISSING DOIs

- 10.1007/978-3-319-46523-4_38 may be a valid DOI for title: Context-Free Path Queries on RDF Graphs

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.57 s (526.7 files/s, 94282.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C/C++ Header                    96           4745           6380          22648
C++                             98           1677           1552           5539
OpenCL                          31            961            215           3345
CUDA                            29            602            605           1850
Python                          20            505            546           1128
Markdown                         8            204              0            708
CMake                            9             85             31            382
Bourne Shell                     6             17             21            109
YAML                             2             14              2            107
TeX                              1              5              0             70
SVG                              2              0              0              2
-------------------------------------------------------------------------------
SUM:                           302           8815           9352          35888
-------------------------------------------------------------------------------


Statistical information for the repository '686d7eec9413c01fa1158df8' was
gathered on 2021/09/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Egor19035                       11          7145            913           11.05
EgorOrachev                      3            11           8250           11.33
Maria Karpenko                  15         45080          11508           77.62

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
EgorOrachev               11123       101118.2          2.7               25.60
Maria Karpenko            33597           74.5          2.5               15.90
```

**Comment by Nikoleta-v3** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03743/joss.03743/10.21105.joss.03743.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03743/joss.03743/10.21105.joss.03743.pdf) :page_facing_up: :point_left:

**Comment by Nikoleta-v3** [comment]
👋🏼 @EgorOrachyov @abb58, @mlxd this is the review thread for the paper. All of our communications will happen here from now on.

Both reviewers have checklists at the top of this thread with the JOSS requirements 🔝 As you go over the submission, please check any items that you feel have been satisfied. There are also links to the JOSS reviewer guidelines.

The JOSS review is different from most other journals. Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, the reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention #3743 so that a link is created to this thread (and I can keep an eye on what is happening). Please also feel free to comment and ask questions on this thread. In my experience, it is better to post comments/questions/suggestions as you come across them instead of waiting until you've reviewed the entire package.

We aim for reviews to be completed within about 2-4 weeks. Please let me know if any of you require some more time. We can also use Whedon (our bot) to set automatic reminders if you know you'll be away for a known period of time.

Please feel free to ping me (@Nikoleta-v3 ) if you have any questions/concerns 👍🏻 😄

**Comment by Nikoleta-v3** [comment]
@EgorOrachyov please fix the missing DOI: https://github.com/openjournals/joss-reviews/issues/3743#issuecomment-923893328 :)

**Comment by EgorOrachyov** [comment]
Missing doi fixed! :)

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03743/joss.03743/10.21105.joss.03743.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03743/joss.03743/10.21105.joss.03743.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
:wave: @mlxd, please update us on how your review is going (this is an automated reminder).

**Comment by Nikoleta-v3** [comment]
Thank you for the update! @abb58, please let us know how your review is going 😄

**Comment by mlxd** [comment]
Apologies for the delays. I have added a new issue for compiling the library at https://github.com/JetBrains-Research/spbla/issues/13

**Comment by mlxd** [comment]
Issue added for adding additional examples: https://github.com/JetBrains-Research/spbla/issues/14

**Comment by mlxd** [comment]
Issue added for community guidelines https://github.com/JetBrains-Research/spbla/issues/16

**Comment by mlxd** [comment]
Issue added for API functionality documentation https://github.com/JetBrains-Research/spbla/issues/15

**Comment by Nikoleta-v3** [comment]
Hey @EgorOrachyov! Any update on your progress? 😄 and @abb58, please let us know how your review is going 😄

**Comment by EgorOrachyov** [comment]
@Nikoleta-v3 Hi! Thank you for you gentle reminder :) **mlxd** left a number of not critical but very importan issues to your project, so we are going to fix it in a couple of upcoming days!

**Comment by Nikoleta-v3** [comment]
Great, thank you @EgorOrachyov 😃

**Comment by Nikoleta-v3** [comment]
Hey @EgorOrachyov 👋🏻   I hope everything is well with you!

The submission has been still for a while now. I was wondering if you had an update for us?

**Comment by mlxd** [comment]
Hi @EgorOrachyov apologies for the delay. I'll get to this before the end-of-week.

**Comment by EgorOrachyov** [comment]
@mlxd Hello, thank you. We will be waiting for a response from you.

**Comment by mlxd** [comment]
Apologies for the delay. I am happy to report that I am done with my review, and all boxes are now ticked. Nice work @EgorOrachyov

**Comment by EgorOrachyov** [comment]
@mlxd It is great! Thank you so much for your review. 

We apologize once more for such a delay from our side.

**Comment by EgorOrachyov** [comment]
@Nikoleta-v3 Hello, we hope it is not too late now :)

We wondering, what is the next step of the review process. If I understand correctly, we have to get the responses from other reviewer?

**Comment by Nikoleta-v3** [comment]
Hey @EgorOrachyov that's correct. The second reviewer has been inactive for a while! I emailed them and I am waiting to hear back from them. If they do not reply I am going to find a new reviewer for the submission 👍🏻

**Comment by EgorOrachyov** [comment]
@Nikoleta-v3 Cool, thanks! We will be waiting for updates on this question.

**Comment by Nikoleta-v3** [comment]
Just to let you know @EgorOrachyov - I have been emailing people every week but I haven't managed to find a new reviewer for the submission. I will keep you updated. In the meantime if you or @mlxd  have any suggestions please let me know!

**Comment by EgorOrachyov** [comment]
@Nikoleta-v3 Hi, thank you for your message. Is it possible to assign as a reviewer someone who I have suggested in previous (pre-review) discussion?

**Comment by EgorOrachyov** [comment]
hausen
arghdos
pszi1ard
abb58
JaroslavHron
sarats
camillescott
mlxd
wrathematics

**Comment by Nikoleta-v3** [comment]
Yes I have been emailing them 😄

**Comment by EgorOrachyov** [comment]
@Nikoleta-v3 Okay, I see :) So, is it possible to try to email others, if we have another look into excel table and try to find new possible reviewers?

**Comment by Nikoleta-v3** [comment]
There only two reviewers from the above list I haven't reach out because I couldn't find their emails. I will ping them here 😄

**Comment by Nikoleta-v3** [comment]
👋 @hausen & @arghdos would any of you be willing to review this submission for JOSS?

We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

The submission I'd like you to review is titled: "SPbLA: The Library of GPGPU-powered Sparse Boolean Linear Algebra Operations". You can find more information at the top of this Github issue 🆙

Please let me know if you're available 😄 Thank you!

**Comment by Nikoleta-v3** [comment]
I was corresponding with a few potential reviewers but unfortunately no one was able to commit at the end. I am going back into the excel spreadsheet.

**Comment by Nikoleta-v3** [comment]
👋 @bencardoen & @chaypaterson & @alejandrogallo & @mkareshk  would any of you be willing to review this submission for JOSS? One reviewer has already reviewed the submission, and I am looking for a second pair of 👀

We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

The submission I'd like you to review is titled: "SPbLA: The Library of GPGPU-powered Sparse Boolean Linear Algebra Operations". You can find more information at the top of this Github issue 🆙

Please let me know if you're available 😄 Thank you!

**Comment by bencardoen** [comment]
@Nikoleta-v3 the invite / confirm link at the top of the issue seems no longer valid, how do I start the review? (this is my first JOSS review)

**Comment by EgorOrachyov** [comment]
> @Nikoleta-v3 Sure, I'd be happy to review.

@bencardoen Hi, thank you! 🎉

We will be waiting for your review/comments. If there are some issues, we will fix it as soon as possible.

**Comment by Nikoleta-v3** [comment]
@editorialbot remove @abb58 from reviewers

**Comment by Nikoleta-v3** [comment]
@editorialbot add @bencardoen to reviewers

**Comment by Nikoleta-v3** [comment]
Thank you very much @bencardoen for agreeing to review this submission! 🙏🏻 

> this is my first JOSS review

This is great - welcome! 🎉 

If you comment the following command `@editorialbot generate my checklist` on this issue the bot will generate a checklist for you ✍🏻 

What you have to do is go over the checklist and make sure that the submission addresses each point. These points will include details both about the software and the paper. 

I recommend that each time you would like the authors to change something that you open an issue on their repository (https://github.com/JetBrains-Research/spbla) and in there mention this issue (#3743). That way I can keep track of the issues! 

Once you are done with the checklist you can just leave a comment here to let me know. If you have any questions regarding something on the checklist (or anything else) you can ping me here and I will reply as soon as possible!

**Comment by bencardoen** [comment]
@editorialbot generate my checklist

**Comment by bencardoen** [comment]
@Nikoleta-v3 
I completed the checklist, and made issues (I hope in the right way) for the items I came across. 
My general review comments are in issue https://github.com/JetBrains-Research/spbla/issues/19
I haven't been able to verify the performance results due to a build issue https://github.com/JetBrains-Research/spbla/issues/17 so that's unchecked, and I still need to get the python tests running. 
I'll revisit this comment thread once I've completed the Python part.

**Comment by Nikoleta-v3** [comment]
That's great, thank you for the update @bencardoen 😄

The comments regarding the paper look good and addressable 👍🏻 I hope the build issue is resolved soon.

**Comment by Nikoleta-v3** [comment]
👋🏻 @bencardoen any updates? 😄

**Comment by bencardoen** [comment]
@Nikoleta-v3 https://github.com/JetBrains-Research/spbla/issues/19 (general feedback/comments) is open, the other issues have been addressed. I've updated the comment above to reflect the changes.

**Comment by Nikoleta-v3** [comment]
Perfect -- thank you! @EgorOrachyov ⬆️  please have a look at the issue.

**Comment by Nikoleta-v3** [comment]
@EgorOrachyov any updates on this?

**Comment by EgorOrachyov** [comment]
@Nikoleta-v3 Hi! Yes, we have addressed some minor technical and documentation related features. Now we are going to do a text clean-up, as it is suggested in https://github.com/JetBrains-Research/spbla/issues/19 issue. I hope, we will have it done in a couple of days. 

Apologies for delays, busy work days :/

**Comment by EgorOrachyov** [comment]
@whedon generate pdf from branch joss-paper

**Comment by EgorOrachyov** [comment]
@whedon

**Comment by EgorOrachyov** [comment]
@Nikoleta-v3 Hi, I hope, we have addressed all issues. Waiting for a feedback from @bencardoen 

It would be great, if you trigger paper recompilation (seems I do not have enough permissions to do it), since we updates text and some diagrams :)

`@whedon generate pdf from branch joss-paper`

**Comment by Nikoleta-v3** [comment]
@whedon generate pdf from branch joss-paper

**Comment by Nikoleta-v3** [comment]
@editorialbot  generate pdf from branch joss-paper

**Comment by Nikoleta-v3** [comment]
@editorialbot set joss-paper as branch

**Comment by Nikoleta-v3** [comment]
@editorialbot generate pdf

**Comment by bencardoen** [comment]
@Nikoleta-v3 @EgorOrachyov 
I'm ok with the changes made in issue 19, however noted the below writing issues (quickly fixed, so just listing them here if that's ok)

Line 10: within [a] Python runtime 
Line 48 Related Tools: Best to our knowledge --> To the best of our knowledge
Line 74 Experiment is --> The experiment is  
Line 86 Future research : Potential solution --> A potential solution

Apart from those minor issues I'm satisfied. (Thank you @EgorOrachyov for the clarifying answer to my question in the issue)

**Comment by EgorOrachyov** [comment]
@editorialbot generate pdf

**Comment by EgorOrachyov** [comment]
@bencardoen Hi, thank you once more 😀! I've minor fixed writing issues, new pdf file is above.

**Comment by bencardoen** [comment]
@EgorOrachyov thanks for the quick turnaround, latest version of the paper looks great. 
@Nikoleta-v3  Do I need to issue a special command to conclude the review on my part?

**Comment by Nikoleta-v3** [comment]
Hey @bencardoen thank you so much for your review! Apologies for my late reply (I am currently at a workshop 💻 ).

No, I can see that you have ticked all the boxes on your list so that's all 😄 Thank you for your time once again 🙏🏻 

@EgorOrachyov - I already have looked over the source code. I will have one final look at the paper at some point this week and see if there are any more minor things that we might have missed and then we should be good to go!

**Comment by Nikoleta-v3** [comment]
@EgorOrachyov thank you for your patience. There are a few typos in the paper. I believe I've picked them all up (see below). 

Another minor comment I have is regarding the figures. The numbers (the memory consumption) are not always easy to see. Could you maybe use a bold font? 

### Typos
#### Summary

- as **a** stand-alone self-sufficient

#### Statement of need

-  to leverage a set of ~a~ powerful sparse linear algebra libraries (I think)
- Also, we hope ~,~ that the library is a small step to move the implementation (remove second comma)

#### Related tools

- is one of the first standards ~,~ that formalize the mathematical (remove comma)
- in the language of ~the~ linear algebra.
- is a reference implementation~s~ of the (I think)
- It is **a** mature and fully featured library with **a** number of bindings for 
- is currently in ~the~ active development. 
- There **are a** number of open-source and proprietary libraries

#### Performance

- The experiment itself is designed as a computational task~s~,  which arises as **a** stand-alone
- memory consumption in some cases, ~what~ **which** can be a critical limitation

#### Future research

- in order to support arbitrary types and operations, defined by **the** user.

**Comment by Nikoleta-v3** [comment]
@EgorOrachyov 🆙 👋🏻 😄

**Comment by Nikoleta-v3** [comment]
@EgorOrachyov sorry for the multiple pings but it would be nice to see this paper published soon.

**Comment by EgorOrachyov** [comment]
@editorialbot generate pdf

**Comment by EgorOrachyov** [comment]
@Nikoleta-v3 

Hello! I apologize for such a long response. 
We have corrected typos and updated the charts, highlighting the measurements numbers in bold.

I hope to proceed without delay to carry out the rest of the work 👽

**Comment by Nikoleta-v3** [comment]
Thank you @EgorOrachyov! 

At this point could you:
- [ ] Let me know which tagged release of your software we should use? `v1.0.0`? or would you like to make a new one?
- [ ] Archive the reviewed software in Zenodo or a similar service (e.g., figshare, an institutional repository)
- [ ] Check the archival deposit (e.g., in Zenodo) has the correct metadata. This includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it). You may also add the authors' ORCID.
- [ ] Please list the DOI of the archived version here.

I can then move forward with accepting the submission.

**Comment by EgorOrachyov** [comment]
@Nikoleta-v3 

- [x] Release `v1.0.0` is ok. (I have made new one especially for Zenodo `v1.0.0-zenodo`, but it is effectively the same thing)
- [x] Zenodo archive [DOI: 10.5281/zenodo.7009938](https://doi.org/10.5281/zenodo.7009938)
- [x] Meta filled, orcid added where possible
- [x] [DOI: 10.5281/zenodo.7009938](https://doi.org/10.5281/zenodo.7009938)

**Comment by Nikoleta-v3** [comment]
@editorialbot set 10.5281/zenodo.7009938 as archive

**Comment by Nikoleta-v3** [comment]
@editorialbot set v1.0.0 as version

**Comment by Nikoleta-v3** [comment]
@editorialbot recommend-accept

**Comment by Nikoleta-v3** [comment]
@EgorOrachyov there is a missing DOI. Could you please take care of this? 😄

**Comment by Nikoleta-v3** [comment]
My apologises for only raising the issue now. I was sured I checked the references 😅

**Comment by EgorOrachyov** [comment]
@Nikoleta-v3 If I understand you correctly, I have to fix doi `10.1145/3466795` for GraphBLATS paper and updated article sources?

**Comment by EgorOrachyov** [comment]
@editorialbot generate pdf

**Comment by EgorOrachyov** [comment]
@Nikoleta-v3 Seems to be fixed now

> @EgorOrachyov there is a missing DOI. Could you please take care of this? 😄

**Comment by Nikoleta-v3** [comment]
@editorialbot check references

**Comment by Nikoleta-v3** [comment]
dear editors please note that I've set the version to be the tagged release `v1.0.0`. However,

> Release v1.0.0 is ok. (I have made new one especially for Zenodo v1.0.0-zenodo, but it is effectively the same thing)

So the Zenodo archive is based on the tagged release `v1.0.0-zenodo`.  Let me know if I should change the version to be `v1.0.0-zenodo` instead.

**Comment by arfon** [comment]
@editorialbot recommend-accept

**Comment by arfon** [comment]
@editorialbot accept

**Comment by arfon** [comment]
@mlxd, @bencardoen – many thanks for your reviews here and to @Nikoleta-v3 for editing this submission! JOSS relies upon the volunteer effort of people like you and we simply wouldn't be able to do this without you ✨ 

@EgorOrachyov – your paper is now accepted and published in JOSS :zap::rocket::boom:

**Comment by EgorOrachyov** [comment]
Many thanks to joss community for reviewing and editing this submission.  We are very pleased that we have an opportunity to finally publish it 🎉🚀

**Comment by bencardoen** [comment]
Congrats on the acceptance @EgorOrachyov  
As a general comment, 99% of journals/venues I've interacted with so far could learn a lot of how the review process works here: highly responsive, collaborative, constructive, open, automated where needed, allowing humans to focus on the parts that need human reflection. @arfon @Nikoleta-v3
