### ISSUE TITLE
[PRE REVIEW]: cofad: An R package and shiny app for contrast analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3745]
**Submitting author:** @johannes-titz (<a href="http://orcid.org/0000-0002-1102-5719">Johannes Titz</a>)
**Repository:** <a href="https://github.com/johannes-titz/cofad" target ="_blank">https://github.com/johannes-titz/cofad</a>
**Version:** v0.2.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/b86ad7d9c7500604c0c66df652475406/status.svg)](https://joss.theoj.org/papers/b86ad7d9c7500604c0c66df652475406)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/b86ad7d9c7500604c0c66df652475406"><img src="https://joss.theoj.org/papers/b86ad7d9c7500604c0c66df652475406/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/b86ad7d9c7500604c0c66df652475406/status.svg)](https://joss.theoj.org/papers/b86ad7d9c7500604c0c66df652475406)
```

**Author instructions**

Thanks for submitting your paper to JOSS @johannes-titz. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @chartgerink.

@johannes-titz if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
PDF failed to compile for issue #3745 with the following error: 
```
 ORCID looks malformed
/app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:155:in `block in check_orcids': Problem with ORCID (TODO) for Markus Burkhardt (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:153:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:153:in `check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:90:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03745/joss.03745/10.21105.joss.03745.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03745/joss.03745/10.21105.joss.03745.pdf) :page_facing_up: :point_left:

**Comment by chartgerink** [comment]
Thanks for suggesting me @johannes-titz - looks right up my alley! 

@whedon assign @chartgerink as editor

**Comment by chartgerink** [comment]
@whedon assign @chartgerink as editor

**Comment by whedon** [comment]
OK, the editor is @chartgerink
