### ISSUE TITLE
[PRE REVIEW]: AixCaliBuHA: Automated calibration of building and HVAC systems

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3800]
**Submitting author:** @FWuellhorst (<a href="http://orcid.org/0000-0003-3325-5707">Fabian Wüllhorst</a>)
**Repository:** <a href="https://github.com/RWTH-EBC/AixCaliBuHA" target ="_blank">https://github.com/RWTH-EBC/AixCaliBuHA</a>
**Version:** v0.2.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/ef57939010ca99df11bf4c2056dd7caf/status.svg)](https://joss.theoj.org/papers/ef57939010ca99df11bf4c2056dd7caf)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/ef57939010ca99df11bf4c2056dd7caf"><img src="https://joss.theoj.org/papers/ef57939010ca99df11bf4c2056dd7caf/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/ef57939010ca99df11bf4c2056dd7caf/status.svg)](https://joss.theoj.org/papers/ef57939010ca99df11bf4c2056dd7caf)
```

**Author instructions**

Thanks for submitting your paper to JOSS @FWuellhorst. **Currently, there isn't an JOSS editor assigned** to your paper.

@FWuellhorst if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 908

**Comment by whedon** [comment]
PDF failed to compile for issue #3800 with the following error: 
```
 ORCID looks malformed
/app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:155:in `block in check_orcids': Problem with ORCID (TODO) for Fabian Wüllhorst (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:153:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:153:in `check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:90:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.12 s (385.4 files/s, 187641.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SVG                              5              0            135          17082
Python                          26            578           1551           2638
Markdown                         5             73              0            248
Jupyter Notebook                 1              0            566            153
TeX                              1             11              0            120
reStructuredText                 7             34             66             43
YAML                             2              3              4             42
make                             1              4              6             10
-------------------------------------------------------------------------------
SUM:                            48            703           2328          20336
-------------------------------------------------------------------------------


Statistical information for the repository 'b2969cebb1027fd573f09342' was
gathered on 2021/10/02.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Fabian                           1             5             10            0.05
Fabian Wüllhorst                10          6304           5805           37.39
Leonard Schulte                  1             4              4            0.02
Lovis Kauderer                   6           131             52            0.57
MBaranskiEBC                     3           913              0            2.82
MichaMans                        1            12              6            0.06
Philipp Mehrfeld                 3             9              2            0.03
Sebastian                       22           904            692            4.93
Sebastian Borges                 1            39             38            0.24
Sebastian.Borges                 1            10              1            0.03
fabian.wuellhorst              160          8649           6124           45.62
philipp.mehrfeld                36          1291           1067            7.28
zhiyupan                         1           309              3            0.96

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Fabian Wüllhorst           1227           19.5         19.0               14.75
Lovis Kauderer                4            3.1         10.1                0.00
MichaMans                     1            8.3          0.9                0.00
Sebastian.Borges            131         1310.0         11.0               25.19
fabian.wuellhorst          3396           39.3          6.7               16.73
philipp.mehrfeld              5            0.4         30.1               40.00
zhiyupan                      3            1.0         28.0               66.67
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.00097 is OK
- 10.1038/s41592-019-0686-2 is OK

MISSING DOIs

- 10.1109/access.2020.2990567 may be a valid DOI for title: Pymoo: Multi-Objective Optimization in Python
- 10.1016/j.rser.2014.05.007 may be a valid DOI for title: A review of methods to match building energy simulation models to measured data
- 10.26868/25222708.2019.210992 may be a valid DOI for title: Applying Machine Learning to Automate Calibration for Model Predictive Control of Building Energy Systems
- 10.3384/ecp21181561 may be a valid DOI for title: A Modular Model of Reversible Heat Pumps and Chillers for System Applications

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @FWuellhorst - note that your paper does not compile. Please follow the [example paper](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography). In addition, you could work on the possibly missing DOIs that whedon suggests, but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` after making changes to the .md file or when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by FWuellhorst** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.00097 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1109/ACCESS.2020.2990567 is OK
- 10.1016/j.rser.2014.05.007 is OK
- 10.26868/25222708.2019.210992 is OK
- 10.3384/ecp21181561 is OK

MISSING DOIs

- 10.3384/ecp21181561 may be a valid DOI for title: A Modular Model of Reversible Heat Pumps and Chillers for System Applications

INVALID DOIs

- None
```

**Comment by FWuellhorst** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.00097 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1109/ACCESS.2020.2990567 is OK
- 10.1016/j.rser.2014.05.007 is OK
- 10.26868/25222708.2019.210992 is OK
- 10.3384/ecp21181561 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by FWuellhorst** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03800/joss.03800/10.21105.joss.03800.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03800/joss.03800/10.21105.joss.03800.pdf) :page_facing_up: :point_left:

**Comment by FWuellhorst** [comment]
@danielskatz: Thank you for the explanation and command hints. Everything seems to compile now.

**Comment by FWuellhorst** [comment]
A list of possible reviewers for this submission:
- mewilhel
- noah80
- willu47
- ralphevins
- samuelduchesne

**Comment by kyleniemeyer** [comment]
Hi @fraukewiese could you edit this submission for us?

**Comment by kyleniemeyer** [comment]
@whedon invite @fraukewiese as editor

**Comment by whedon** [comment]
@fraukewiese has been invited to edit this submission.

**Comment by kyleniemeyer** [comment]
Hi @FWuellhorst, I noticed a few remaining (minor) issues with the paper that you could resolve while we are getting started:

- In the second paragraph, you have references with nested parentheses :"(e.g. (Blank & Deb, 2020...". You can avoid this by changing the citation to `(e.g., @2020SciPy-NMeth; @dlib09; @pymoo)`.
- In the third paragraph: "it's usage" -> "its usage"
- In the first paragraph of Statement of Need, you have a period after "digital twins" but prior to the references, which are part of that sentence.
- The two Vering et al. (2021) references seem to be missing some bibliographic information.

**Comment by FWuellhorst** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03800/joss.03800/10.21105.joss.03800.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03800/joss.03800/10.21105.joss.03800.pdf) :page_facing_up: :point_left:

**Comment by FWuellhorst** [comment]
@kyleniemeyer thank you for your review! 
I corrected the listed issues. 
Two remarks regarding the missing information in the references of Vering et al. (2021).
1. The conference article regarding digital twins is part of the 17th IBPSA Conference, which already took place. The proceedings are not published yet. A DOI is not yet present.
2. We submitted an article to Energy Conversion and Management, which is currently under review. As the article extends our already published conference paper at the ECOS 2021 (https://www.ebc.eonerc.rwth-aachen.de/go/id/dncb/file/826177?lidx=1), I will refer to the conference instead. Again, a DOI is not yet present.

**Comment by ralphevins** [comment]
Sure I can take a look.

Ralph

**Comment by fraukewiese** [comment]
@whedon assign @ralphevins as reviewer

**Comment by fraukewiese** [comment]
@kramea @jordanperr – would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: [https://joss.readthedocs.io/en/latest/reviewer_guidelines.html](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html)

The submission under review here is [AixCaliBuHA: Automated calibration of building and HVAC systems https://github.com/RWTH-EBC/AixCaliBuHA](https://github.com/RWTH-EBC/AixCaliBuHA)

**Comment by kramea** [comment]
Hi, I cannot review this at the moment. However I would like to recommend my colleague https://github.com/samanmostafavi He is a domain expert and has a lot of experience in building and HVAC systems
