### ISSUE TITLE
[REVIEW]: bistablehistory: an R package for history-dependent analysis of perceptual time series

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3901]
**Submitting author:** @alexander-pastukhov (<a href="http://orcid.org/0000-0002-8738-8591">Alexander Pastukhov</a>)
**Repository:** <a href="https://github.com/alexander-pastukhov/bistablehistory" target ="_blank">https://github.com/alexander-pastukhov/bistablehistory</a>
**Version:** v1.1.0
**Editor:** @mikldk
**Reviewer:** @fernandomayer, @fartist
**Archive:** <a href="https://doi.org/10.5281/zenodo.5851674" target="_blank">10.5281/zenodo.5851674</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/43397f168000b6fafe03416c3168a78a/status.svg)](https://joss.theoj.org/papers/43397f168000b6fafe03416c3168a78a)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/43397f168000b6fafe03416c3168a78a"><img src="https://joss.theoj.org/papers/43397f168000b6fafe03416c3168a78a/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/43397f168000b6fafe03416c3168a78a/status.svg)](https://joss.theoj.org/papers/43397f168000b6fafe03416c3168a78a)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/alexander-pastukhov/bistablehistory" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@fernandomayer & @fartist, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @mikldk know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @fernandomayer
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/alexander-pastukhov/bistablehistory">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/alexander-pastukhov/bistablehistory">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@alexander-pastukhov) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @fartist
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/alexander-pastukhov/bistablehistory">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/alexander-pastukhov/bistablehistory">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@alexander-pastukhov) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @fernandomayer, @fartist it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.04 s (763.2 files/s, 106808.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C/C++ Header                     2              3             38           1971
R                               23            147            851            550
Markdown                         3            118              0            521
Rmd                              3             84            171            157
C++                              3             24             31             92
-------------------------------------------------------------------------------
SUM:                            34            376           1091           3291
-------------------------------------------------------------------------------


Statistical information for the repository '0827d4fb975b3d7e50d5625c' was
gathered on 2021/11/09.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Alexander (Sasha) Pa             7          3599              2          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Alexander (Sasha) Pa       2159           60.0          0.1                3.29
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3901 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by mikldk** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03901/joss.03901/10.21105.joss.03901.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03901/joss.03901/10.21105.joss.03901.pdf) :page_facing_up: :point_left:

**Comment by mikldk** [comment]
@fernandomayer, @fartist, can you please give a brief status of your review? This is not to rush you, merely to give me an impression of the progress and time-frame.

**Comment by fartist** [comment]
Thanks for checking in @mikldk - I have started and should be able to finish the first round in the coming week.

**Comment by fernandomayer** [comment]
@mikldk I will be able to send a few more comments and feedback in the next week.

**Comment by whedon** [comment]
:wave: @fernandomayer, please update us on how your review is going (this is an automated reminder).

**Comment by whedon** [comment]
:wave: @fartist, please update us on how your review is going (this is an automated reminder).

**Comment by mikldk** [comment]
@fernandomayer, @fartist, can you please give a brief status of your review? This is not to rush you, merely to give me an impression of the progress and time-frame.

**Comment by fernandomayer** [comment]
@mikldk I should be able to complete it in the next week.

**Comment by mikldk** [comment]
@fernandomayer, @fartist, can you please give a brief status of your review? This is not to rush you, merely to give me an impression of the progress and time-frame.

**Comment by fernandomayer** [comment]
@mikldk I've sent a PR to the author with some suggestions, so I hope to finish my review next week.

**Comment by fartist** [comment]
I plan to finish my review in the coming week, thx! Sent from Mail for Windows From: Mikkel Meyer AndersenSent: Friday, December 17, 2021 1:29 AMTo: openjournals/joss-reviewsCc: Feeeeeeeeeeng; MentionSubject: Re: [openjournals/joss-reviews] [REVIEW]: bistablehistory: an R package for history-dependent analysis of perceptual time series (Issue ***@***.***, @fartist, can you please give a brief status of your review? This is not to rush you, merely to give me an impression of the progress and time-frame.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by fernandomayer** [comment]
@mikldk I've finished my review. Is there anything else I need to do?

**Comment by mikldk** [comment]
@fernandomayer Thanks. I still see a box not checked. Can you please check if you are happy with that one, too - and if so, check it?

**Comment by fernandomayer** [comment]
@mikldk Sorry, I had misunderstood that item. It is checked now. Thanks.

**Comment by fartist** [comment]
Please find my review at https://github.com/alexander-pastukhov/bistablehistory/issues/3 - solid work!

**Comment by alexander-pastukhov** [comment]
@fartist  I have posted detailed response at [alexander-pastukhov/bistablehistory#3](https://github.com/alexander-pastukhov/bistablehistory/issues/3) , should I duplicate it here as well?

**Comment by fartist** [comment]
No, thanks - I can see that on the repo - thanks for taking your time.

**Comment by mikldk** [comment]
@alexander-pastukhov, @fartist What is the status of the remaining issue and check boxes? Please let me know if there is anything I can do or once the review is completed.

**Comment by mikldk** [comment]
@alexander-pastukhov, @fartist What is the status of the remaining issue and check boxes? Please let me know if there is anything I can do or once the review is completed.

**Comment by alexander-pastukhov** [comment]
@mikldk @fartist Sorry for being obtuse but is there something left for me to do that I did not realize I needed to do beyond answering the comments and updating the paper itself?

**Comment by mikldk** [comment]
@alexander-pastukhov Is it correct that you have addressed all points in alexander-pastukhov/bistablehistory#3? In that case I guess we just need @fartist to update the review.

**Comment by alexander-pastukhov** [comment]
@mikldk I did! (to the best of my ability :) )

**Comment by fartist** [comment]
Sorry for the delay! I have no further requests/comments - great work!

**Comment by mikldk** [comment]
@alexander-pastukhov :

* Please have a final read though of the paper, checking language etc.
* Have a final check of the proofs with `@whedon generate pdf`
* In general, be sure that all versions are correct and that the repo is in the state that should be published.
* Please make a tagged release and archive (e.g. with [Zenodo](https://zenodo.org/)) as described [here](<https://joss.readthedocs.io/en/latest/submitting.html#the-review-process>), and report the version number and archive DOI in this thread. Please **verify** that the archive deposit has the correct metadata (**title** and **author list**), or edit these if that is not the case.

**Comment by alexander-pastukhov** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03901/joss.03901/10.21105.joss.03901.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03901/joss.03901/10.21105.joss.03901.pdf) :page_facing_up: :point_left:

**Comment by alexander-pastukhov** [comment]
@mikldk

Version 1.1.0
Tag v1.1.0
https://github.com/alexander-pastukhov/bistablehistory/releases/tag/v1.1.0

Zenodo DOI for 1.1.0: https://zenodo.org/record/5851674
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.5851674.svg)](https://doi.org/10.5281/zenodo.5851674)

**Comment by mikldk** [comment]
@whedon set 10.5281/zenodo.5851674 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.5851674" target="_blank">10.5281/zenodo.5851674</a> is the archive.

**Comment by whedon** [comment]
OK. v1.1.0 is the version.

**Comment by mikldk** [comment]
> @mikldk
> 
> Version 1.1.0 Tag v1.1.0 https://github.com/alexander-pastukhov/bistablehistory/releases/tag/v1.1.0
> 
> Zenodo DOI for 1.1.0: https://zenodo.org/record/5851674 [![DOI](https://camo.githubusercontent.com/8d7b2993811bdf13bafbbb2f51561dcc4e88c3187dab23f6755604c6d477194d/68747470733a2f2f7a656e6f646f2e6f72672f62616467652f444f492f31302e353238312f7a656e6f646f2e353835313637342e737667)](https://doi.org/10.5281/zenodo.5851674)

@alexander-pastukhov , Please change the metadata at Zenodo (title, authors) to match the paper's.

**Comment by alexander-pastukhov** [comment]
@mikldk Fixed! (I hope I did it right!)

**Comment by mikldk** [comment]
@whedon check references

**Comment by mikldk** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03901/joss.03901/10.21105.joss.03901.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03901/joss.03901/10.21105.joss.03901.pdf) :page_facing_up: :point_left:

**Comment by mikldk** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by alexander-pastukhov** [comment]
@mikldk What does the issue mean? that I need to put paper.md into master branch?

**Comment by danielskatz** [comment]
@mikldk needs to run `@whedon recommend-accept from branch joss` next

**Comment by mikldk** [comment]
Sorry about the delay to you.

**Comment by mikldk** [comment]
@whedon recommend-accept from branch joss

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Checking the BibTeX entries failed with the following error: 

 Failed to parse BibTeX entry: cite-key missing

**Comment by whedon** [comment]
PDF failed to compile for issue #3901 with the following error: 
```
 [WARNING] Missing character: There is no ≥ (U+2265) in font cmr10!
[WARNING] Missing character: There is no ≥ (U+2265) in font cmr10!
[WARNING] Missing character: There is no ≥ (U+2265) in font cmr10!
[WARNING] Missing character: There is no ≥ (U+2265) in font cmr10!
[WARNING] Missing character: There is no ≥ (U+2265) in font cmr7!
[WARNING] Missing character: There is no ≥ (U+2265) in font cmr7!
[WARNING] Missing character: There is no ≥ (U+2265) in font cmr5!
[WARNING] Missing character: There is no ≥ (U+2265) in font cmr5!
bibtex.y:129:in `missing_key': Failed to parse BibTeX entry: cite-key missing (BibTeX::ParseError)
	from bibtex.y:72:in `_reduce_27'
	from (eval):3:in `_racc_do_parse_c'
	from (eval):3:in `do_parse'
	from bibtex.y:111:in `parse'
	from /app/vendor/bundle/ruby/2.6.0/gems/bibtex-ruby-6.0.0/lib/bibtex/bibliography.rb:67:in `parse'
	from /app/vendor/bundle/ruby/2.6.0/gems/bibtex-ruby-6.0.0/lib/bibtex/bibliography.rb:50:in `open'
	from /app/vendor/bundle/ruby/2.6.0/gems/bibtex-ruby-6.0.0/lib/bibtex/utilities.rb:25:in `open'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/bibtex_parser.rb:38:in `generate_citations'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/compilers.rb:253:in `crossref_from_markdown'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/compilers.rb:21:in `generate_crossref'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:100:in `compile'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:88:in `compile'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by mikldk** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03901/joss.03901/10.21105.joss.03901.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03901/joss.03901/10.21105.joss.03901.pdf) :page_facing_up: :point_left:

**Comment by mikldk** [comment]
I'll look at this problem. Please hang on.

**Comment by alexander-pastukhov** [comment]
My bad, somehow two papers were included twice in the bib file. I guess that was the problem,

**Comment by alexander-pastukhov** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03901/joss.03901/10.21105.joss.03901.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03901/joss.03901/10.21105.joss.03901.pdf) :page_facing_up: :point_left:

**Comment by mikldk** [comment]
@whedon recommend-accept from branch joss

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1167/11.10.12 is OK
- 10.5281/zenodo.5851674 is OK
- 10.1016/j.visres.2007.08.023 is OK
- 10.1364/JOSAA.26.002612 is OK
- 10.18637/jss.v076.i01 is OK
- 10.1007/s11222-016-9696-4 is OK
- 10.3389/fncom.2013.00017 is OK
- 10.1371/journal.pcbi.1005536 is OK
- 10.1016/j.neuron.2007.09.028 is OK
- 10.18637/jss.v027.i03 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2971

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2971, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true from branch joss 
```

**Comment by danielskatz** [comment]
@alexander-pastukhov - I've suggested some edits in https://github.com/alexander-pastukhov/bistablehistory/pull/4. Please check this and merge it if they seem correct to you.

**Comment by alexander-pastukhov** [comment]
@danielskatz Merged! Thank you for spotting the mistakes!

**Comment by danielskatz** [comment]
@whedon recommend-accept from branch joss

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1167/11.10.12 is OK
- 10.5281/zenodo.5851674 is OK
- 10.1016/j.visres.2007.08.023 is OK
- 10.1364/JOSAA.26.002612 is OK
- 10.18637/jss.v076.i01 is OK
- 10.1007/s11222-016-9696-4 is OK
- 10.3389/fncom.2013.00017 is OK
- 10.1371/journal.pcbi.1005536 is OK
- 10.1016/j.neuron.2007.09.028 is OK
- 10.18637/jss.v027.i03 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2974

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2974, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true from branch joss 
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true from branch joss

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1494317780728000513) 👈 🐦🐦🐦

**Comment by danielskatz** [comment]
Congratulations to @alexander-pastukhov (Alexander Pastukhov)!!

And thanks to @fernandomayer and @fartist for reviewing, and @mikldk for editing!
We couldn't do this without you!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03901/status.svg)](https://doi.org/10.21105/joss.03901)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03901">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03901/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03901/status.svg
   :target: https://doi.org/10.21105/joss.03901
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03901/status.svg)](https://doi.org/10.21105/joss.03901)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by alexander-pastukhov** [comment]
@danielskatz @fernandomayer @mikldk Thank you for your help and guidance! That was a super interesting, useful and fun experience!
