### ISSUE TITLE
[PRE REVIEW]: PWSpy: A Python library dedicated to the analysis of Partial Wave Spectroscopic Microscopy data.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3943]
**Submitting author:** @nanthony21 (<a href="http://orcid.org/0000-0003-2882-2471">Nicholas Anthony</a>)
**Repository:** <a href="https://github.com/BackmanLab/PWSpy" target ="_blank">https://github.com/BackmanLab/PWSpy</a>
**Version:** 0.2.11
**Editor:** @jgostick
**Reviewers:** @dxm447
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/8c2996669cee9e94c227f4427c545962/status.svg)](https://joss.theoj.org/papers/8c2996669cee9e94c227f4427c545962)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/8c2996669cee9e94c227f4427c545962"><img src="https://joss.theoj.org/papers/8c2996669cee9e94c227f4427c545962/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/8c2996669cee9e94c227f4427c545962/status.svg)](https://joss.theoj.org/papers/8c2996669cee9e94c227f4427c545962)
```

**Author instructions**

Thanks for submitting your paper to JOSS @nanthony21. **Currently, there isn't an JOSS editor assigned** to your paper.

@nanthony21 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3943 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.19 s (531.6 files/s, 60572.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          62           1615           3236           5425
MATLAB                           9             91            210            322
YAML                             6             24              9            145
JSON                             6              0              0             73
Markdown                         3             26              0             58
DOS Batch                        4             20              1             54
reStructuredText                 6             49             52             51
TOML                             1              2              1             13
Bourne Shell                     3              1              0             12
make                             1              4              6              9
-------------------------------------------------------------------------------
SUM:                           101           1832           3515           6162
-------------------------------------------------------------------------------


Statistical information for the repository '57d7b50ba45a49294bfd5088' was
gathered on 2021/11/22.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
4D-1-HPD-1                      1             2              1            0.00
Nick                            81          5435           2013            7.16
Nick Anthony                  1653         43308          25861           66.50
nanthony21                      69          3236           1730            4.77
nicholas.anthony@nor           148          5052          17339           21.53
nickAnthonyNU                    2            24             11            0.03

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Nick                       1886           34.7         17.3               44.27
Nick Anthony               8390           19.4         18.4               10.64
```

**Comment by nanthony21** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by nanthony21** [comment]
@whedon generate pdf from branch JOSS

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3943 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:72:in `block in build_affiliation_string': Problem with affiliations for Nicholas Anthony, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:71:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:71:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:205:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:205:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by nanthony21** [comment]
The paper builds fine through [Github Actions](https://github.com/BackmanLab/PWSpy/actions/runs/1490905003), Docker, and the online previewer, I'm not sure what the issue is here.

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev can you help troubleshoot this error :point_up:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @jgostick as editor

**Comment by whedon** [comment]
@jgostick has been invited to edit this submission.

**Comment by nanthony21** [comment]
@whedon generate pdf from branch JOSS

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03943/joss.03943/10.21105.joss.03943.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03943/joss.03943/10.21105.joss.03943.pdf) :page_facing_up: :point_left:

**Comment by nanthony21** [comment]
> @openjournals/dev can you help troubleshoot this error ☝️

It looks like it may have been because my `affiliations` section was missing `index: 1`. It's fixed now.

**Comment by jgostick** [comment]
@whedon assign @jgostick as editor

**Comment by whedon** [comment]
OK, the editor is @jgostick

**Comment by jgostick** [comment]
@whedon assign @pr4deepr as reviewer

**Comment by whedon** [comment]
OK, @pr4deepr is now a reviewer

**Comment by jgostick** [comment]
@whedon assign @dxm447 as reviewer

**Comment by whedon** [comment]
OK, @dxm447 is now a reviewer

**Comment by jgostick** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3957.
