### ISSUE TITLE
[PRE REVIEW]: TEXTLYTICS – the Text Analytics Toolkit

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3961]
**Submitting author:** @fabiolobato (<a href="http://orcid.org/0000-0002-6282-0368">Fábio Manoel França Lobato</a>)
**Repository:** <a href="https://github.com/fabiolobato/textlytics" target ="_blank">https://github.com/fabiolobato/textlytics</a>
**Version:** V1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/dc97b4cb9b799e816a21e75c429412fa/status.svg)](https://joss.theoj.org/papers/dc97b4cb9b799e816a21e75c429412fa)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/dc97b4cb9b799e816a21e75c429412fa"><img src="https://joss.theoj.org/papers/dc97b4cb9b799e816a21e75c429412fa/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/dc97b4cb9b799e816a21e75c429412fa/status.svg)](https://joss.theoj.org/papers/dc97b4cb9b799e816a21e75c429412fa)
```

**Author instructions**

Thanks for submitting your paper to JOSS @fabiolobato. **Currently, there isn't an JOSS editor assigned** to your paper.

@fabiolobato if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 899

**Comment by whedon** [comment]
PDF failed to compile for issue #3961 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:147:in `check_fields': Paper YAML header is missing expected fields: tags, date (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:89:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.04 s (120.1 files/s, 17895.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           2             74             12            343
Markdown                         2             50              0            179
TeX                              1              9              0             78
-------------------------------------------------------------------------------
SUM:                             5            133             12            600
-------------------------------------------------------------------------------


Statistical information for the repository '53227f47f2da3a90470f0ed1' was
gathered on 2021/11/30.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
fabiolobato                      1           429              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
fabiolobato                 429          100.0          0.0                3.03
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.03153 is OK
- 10.21105/joss.02136 is OK
- 10.21105/joss.02594 is OK

MISSING DOIs

- 10.1109/secon.2016.7506650 may be a valid DOI for title: An empirical analysis of feature engineering for predictive modeling
- 10.5753/eniac.2019.9348 may be a valid DOI for title: Uma abordagem baseada em letras para a descoberta de conhecimento da música brasileira: o sertanejo como um estudo de caso

INVALID DOIs

- None
```

**Comment by kthyng** [comment]
Hi @fabiolobato and thanks for your submission. Unfortunately I am [desk rejecting](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) this due to the very small size. Please check out the docs for more detailed info about the imperfect but available proxies we use for estimating "substantial scholarly effort".

**Comment by kthyng** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
