### ISSUE TITLE
[PRE REVIEW]: Global-Chem: Collections of common small molecules and their SMILES/SMARTS to support diverse chemical communities

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4069]
**Submitting author:** @Sulstice (<a href="http://orcid.org/0000-0002-1342-9258">Suliman Sharif</a>)
**Repository:** <a href="https://github.com/Sulstice/global-chem" target ="_blank">https://github.com/Sulstice/global-chem</a>
**Version:** v1.0.2
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/15417bd21935a8acffaf3233fa8bd197/status.svg)](https://joss.theoj.org/papers/15417bd21935a8acffaf3233fa8bd197)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/15417bd21935a8acffaf3233fa8bd197"><img src="https://joss.theoj.org/papers/15417bd21935a8acffaf3233fa8bd197/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/15417bd21935a8acffaf3233fa8bd197/status.svg)](https://joss.theoj.org/papers/15417bd21935a8acffaf3233fa8bd197)
```

**Author instructions**

Thanks for submitting your paper to JOSS @Sulstice. **Currently, there isn't an JOSS editor assigned** to your paper.

@Sulstice if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
Wordcount for `paper.md` is 3890

**Comment by whedon** [comment]
PDF failed to compile for issue #4069 with the following error: 
```
 ORCID looks malformed
/app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:155:in `block in check_orcids': Problem with ORCID (0000-0002-1342-9258, 0000-0001-5559-1635, 0000-0003-4628-526X, 0000-0002-6383-1771, 0000-0001-8395-9353, 0000-0001-8287-6804) for Suliman Sharif,  Elena Yi Chow, Asuka Orr, Aarion Romany, Aziza Frank, Shaoqi Zhan, Ruibin Liu, Sunhwan Jo, Chris Burke, Alexander D. MacKerell Jr. (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:153:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:153:in `check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:90:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.15 s (282.1 files/s, 68058.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          33            652            164           5919
HTML                             1             58              0           2224
TeX                              1             39              0            368
Markdown                         3             86              0            315
YAML                             3             13              8             44
-------------------------------------------------------------------------------
SUM:                            41            848            172           8870
-------------------------------------------------------------------------------


Statistical information for the repository '8c6cea59998bf119cd1f95d1' was
gathered on 2022/01/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Suliman Sharif                  11           507            136            3.01
Sulstice                        71         13536           7183           96.94
Twilson0205                      1             7              0            0.03
jweiner12                        1             4              0            0.02

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Sul                        6735          100.0          0.4                2.75
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s41586-020-2117-z is OK
- 10.1021/acs.jcim.0c00675 is OK
- 10.5281/zenodo.591637 is OK
- 10.1002/jcc.20082 is OK
- 10.1002/jcc.20945 is OK
- 10.1016/j.bmc.2016.06.034 is OK
- 10.1021/ci00062a009 is OK
- 10.1021/ci00062a009 is OK
- 10.1021/om100106e is OK
- 10.1021/jm4017625 is OK
- 10.1016/j.jmgm.2004.03.016 is OK
- 10.1016/j.cbpa.2010.02.018 is OK
- 10.1021/acs.jmedchem.8b01153 is OK
- 10.1351/PAC-REP-12-03-05 is OK
- 10.2144/fsoa-2021-0062 is OK
- 10.1016/j.ejmech.2021.113206 is OK
- 10.1021/acs.jmedchem.7b01306 is OK
- 10.1021/cr800323s is OK
- 10.1016/j.envint.2019.05.045 is OK
- 10.1021/acsomega.1c00481 is OK
- 10.3390/ijms13021805 is OK
- 10.3390/ijms17091508 is OK
- 10.1186/1758-2946-3-37 is OK
- 10.1002/jcc.20035 is OK
- 10.1021/ja00214a001 is OK
- 10.1002/jcc.21367 is OK
- 10.1021/ci3003649 is OK
- 10.1002/jcc.26138 is OK
- 10.1021/ci3003649 is OK
- 10.1021/ci00062a009 is OK

MISSING DOIs

- 10.1073/pnas.98.2.381 may be a valid DOI for title: PubMed Central: The GenBank of the Published Literature.
- 10.5860/choice.37-4225 may be a valid DOI for title:  CRC Handbook of Chemistry and Physics: A Ready-Reference Book of Chemical and Physical Data

INVALID DOIs

- 10.1016/j.ejmech.2020.112836. is INVALID
```

**Comment by danielskatz** [comment]
👋 @Sulstice - this paper is far too long.  Please see https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain

Also, note that your paper does not compile. Please follow the [example paper](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography). In addition, you could work on the possibly missing DOIs that whedon suggests, but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` after making changes to the .md file or when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by Sulstice** [comment]
@whedon generate pdf

**Comment by Sulstice** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #4069 with the following error: 
```
 /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse': (d06f57944b23ca479ba90870/paper.md): mapping values are not allowed in this context at line 34 column 10 (Psych::SyntaxError)
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:390:in `parse'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:277:in `load'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:578:in `block in load_file'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `open'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `load_file'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:127:in `load_yaml'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by Sulstice** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04069/joss.04069/10.21105.joss.04069.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04069/joss.04069/10.21105.joss.04069.pdf) :page_facing_up: :point_left:

**Comment by Sulstice** [comment]
@danielskatz I would need to discuss this internally., but I believe since the paper is showing scientific results it can be in tandem published with another Journal. 

I need to fix my figures as well for whedon.

**Comment by Sulstice** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04069/joss.04069/10.21105.joss.04069.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04069/joss.04069/10.21105.joss.04069.pdf) :page_facing_up: :point_left:

**Comment by Sulstice** [comment]
@danielskatz I would like for this paper to be considered for JOSS review regardless of it's length.

Philosophically, chemical lists are an important subject and usually pretty tricky to obtain. I would trust the Open Source Software will remain open-source so that these lists are free for people to download especially as it grows. That is my intention when submitting the paper to this specific journal. 

The reason for the length of paper is describing the architecture (a python object graph system) and one of the applications as a test on top of other open source forcefield tools since it's not completely obvious yet what is capable from this dataset of using "Common" and "Rare" classifiers and what we can offer within this network as a feature.

**Comment by danielskatz** [comment]
@Sulstice - this submission can be considered by JOSS, but the paper needs to be shortened. Again, see Please see https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain and move other material into the documentation or elsewhere.

**Comment by Sulstice** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04069/joss.04069/10.21105.joss.04069.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04069/joss.04069/10.21105.joss.04069.pdf) :page_facing_up: :point_left:

**Comment by Sulstice** [comment]
@danielskatz It might be a little over but I shortened it 2000 something words.

**Comment by danielskatz** [comment]
thanks! - I'm not on-duty as AEiC this week, but the current AEiC should start the process of finding an editor soon

**Comment by kyleniemeyer** [comment]
@whedon invite @csoneson as editor

👋 Hi @csoneson, could you edit this one?

**Comment by whedon** [comment]
@csoneson has been invited to edit this submission.

**Comment by csoneson** [comment]
@whedon assign @csoneson as editor

**Comment by whedon** [comment]
OK, the editor is @csoneson

**Comment by csoneson** [comment]
👋🏻 @Sulstice - I'll handle your submission and start by looking for suitable reviewers. If you have suggestions, please mention them here (but don't tag them with `@`). Thanks!

**Comment by Sulstice** [comment]
Hey @csoneson, thanks for accepting. 

Perhaps these folk if they are available? 

- olivertomic (Don't know if he is still here with JOSS)
- richardjgowers
- lucydot

What do you think?

**Comment by csoneson** [comment]
👋🏻 @olivertomic, @RMeli - would you be interested in reviewing this submission for JOSS? 

Both @lucydot and @richardjgowers are currently JOSS editors and thus, I suspect, mostly busy with other submissions. Nevertheless, in case one of you would like to review this one, it's of course highly appreciated :)

**Comment by csoneson** [comment]
@Sulstice - while we are waiting for reviewers, could you fix some of the references in the paper that don't display properly? E.g. 
```E., W. M., & al., et. (2010). Privileged scaffolds for library design and drug discovery.```
and similar

**Comment by RMeli** [comment]
Hi @csoneson , I can review this submission.

**Comment by csoneson** [comment]
@RMeli - brilliant, thanks! Once we have secured one more reviewer I will open the dedicated review issue where you will find your review checklist etc.

**Comment by olivertomic** [comment]
@csoneson - right now I have a bit too much on my shoulders. Sorry, I'll have to decline this time.

**Comment by Sulstice** [comment]
@csoneson done!

**Comment by richardjgowers** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by csoneson** [comment]
👋🏻 @Sulstice - sorry for the delayed response. As you can see above a scope query has been initialized, which will allow the broader editorial team to take a look and comment on whether this submission is in scope for JOSS or not in its current form. We will get back to you shortly on this.

**Comment by Sulstice** [comment]
Got it, let me know if there is anything else I can do as well.

**Comment by kthyng** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
