### ISSUE TITLE
[PRE REVIEW]: Asimov: A framework for coordinating parameter estimation workflows

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4117]
**Submitting author:** @transientlunatic (<a href="http://orcid.org/0000-0003-3772-198X">Daniel Williams</a>)
**Repository:** <a href="https://git.ligo.org/asimov/asimov" target ="_blank">https://git.ligo.org/asimov/asimov</a>
**Version:** v0.3.3
**Editor:** @mbobra
**Reviewers:** @danehkar, @matthewfeickert
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/ef5eb6f46867ddf5b10667a8357cf199/status.svg)](https://joss.theoj.org/papers/ef5eb6f46867ddf5b10667a8357cf199)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/ef5eb6f46867ddf5b10667a8357cf199"><img src="https://joss.theoj.org/papers/ef5eb6f46867ddf5b10667a8357cf199/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/ef5eb6f46867ddf5b10667a8357cf199/status.svg)](https://joss.theoj.org/papers/ef5eb6f46867ddf5b10667a8357cf199)
```

**Author instructions**

Thanks for submitting your paper to JOSS @transientlunatic. **Currently, there isn't an JOSS editor assigned** to your paper.

@transientlunatic if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #4117 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #4117 with the following error: 
```
 /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse': (2b24a6279f2f1ab1b5d56b0d/paper/paper.md): found character that cannot start any token while scanning for the next token at line 43 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:390:in `parse'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:277:in `load'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:578:in `block in load_file'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `open'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `load_file'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:127:in `load_yaml'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev can you check what is wrong here? Perhaps @transientlunatic should remove the quotation symbols `"` from the title and replace them with `'`, and remove those in the author names?

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @mbobra as editor

**Comment by whedon** [comment]
@mbobra has been invited to edit this submission.

**Comment by transientlunatic** [comment]
> @openjournals/dev can you check what is wrong here? Perhaps @transientlunatic should remove the quotation symbols `"` from the title and replace them with `'`, and remove those in the author names?

Ahh, I'll try that just now. Apologies about this, it all compiled fine via the web-form and the docker container.

**Comment by transientlunatic** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #4117 with the following error: 
```
 /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse': (20ed9915ed490f6d108232e5/paper/paper.md): found character that cannot start any token while scanning for the next token at line 43 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:390:in `parse'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:277:in `load'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:578:in `block in load_file'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `open'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `load_file'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:127:in `load_yaml'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by transientlunatic** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by transientlunatic** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #4117 with the following error: 
```
 /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse': (21e5e6c8d7138d92fb3f8d42/paper/paper.md): found character that cannot start any token while scanning for the next token at line 43 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:390:in `parse'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:277:in `load'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:578:in `block in load_file'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `open'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `load_file'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:127:in `load_yaml'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by danielskatz** [comment]
FYI, for @Kevin-Mattheus-Moerman - the error message from whedon points out the line number and character where the error is: `found character that cannot start any token while scanning for the next token at line 43 column 1 (Psych::SyntaxError)`  there's a tab there, which is the problem.

**Comment by mbobra** [comment]
@whedon assign @mbobra as editor

**Comment by whedon** [comment]
OK, the editor is @mbobra

**Comment by mbobra** [comment]
@transientlunatic Thanks for your submission! If you have any suggestions for reviewers, please let me know here (you can give me the Github handle without @ mentioning them, e.g. mbobra instead of @mbobra).

**Comment by transientlunatic** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #4117 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:204:in `block in parse_authors': Author (Maria Luisa Chiofalo) is missing affiliation (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by transientlunatic** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04117/joss.04117/10.21105.joss.04117.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04117/joss.04117/10.21105.joss.04117.pdf) :page_facing_up: :point_left:

**Comment by transientlunatic** [comment]
Thanks @mbobra! I think I suggested dfm from the list of reviewers on the submission form, but I accept this is a slightly unusual piece of software since it's really designed to facilitate analyses rather than conduct them itself, so it may not be dfm's cup of tea!
I wasn't quite sure if you were open to suggestions outwith that list, if you are I can think about it and try and get back to you.

**Comment by mbobra** [comment]
@transientlunatic Yes, I am absolutely open to suggestions off that list!

**Comment by mbobra** [comment]
@transientlunatic Still working on it -- sorry it has taken so long!

**Comment by mbobra** [comment]
@whedon assign @danehkar as reviewer

**Comment by whedon** [comment]
OK, @danehkar is now a reviewer

**Comment by mbobra** [comment]
@whedon add @matthewfeickert as reviewer

**Comment by whedon** [comment]
OK, @matthewfeickert is now a reviewer

**Comment by mbobra** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4170.

**Comment by mbobra** [comment]
👋 @transientlunatic @danehkar @matthewfeickert See you over in #4170 where the actual review will take place!
