### ISSUE TITLE
[PRE REVIEW]: Lexedata: A Python toolbox to edit CLDF lexical datasets

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4123]
**Submitting author:** @Anaphory (<a href="http://orcid.org/0000-0002-8155-9089">Gereon Kaiping</a>)
**Repository:** <a href="https://github.com/Anaphory/lexedata/" target ="_blank">https://github.com/Anaphory/lexedata/</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/097f3e3a45cde3c54fb5ad51972af4d2/status.svg)](https://joss.theoj.org/papers/097f3e3a45cde3c54fb5ad51972af4d2)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/097f3e3a45cde3c54fb5ad51972af4d2"><img src="https://joss.theoj.org/papers/097f3e3a45cde3c54fb5ad51972af4d2/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/097f3e3a45cde3c54fb5ad51972af4d2/status.svg)](https://joss.theoj.org/papers/097f3e3a45cde3c54fb5ad51972af4d2)
```

**Author instructions**

Thanks for submitting your paper to JOSS @Anaphory. **Currently, there isn't an JOSS editor assigned** to your paper.

@Anaphory if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 433

**Comment by whedon** [comment]
PDF failed to compile for issue #4123 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:72:in `block in build_affiliation_string': Problem with affiliations for Natalia Chousou-Polydouri, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:71:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:71:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:205:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:205:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/sdata.2018.205 is OK
- 10.5281/zenodo.4804030 is OK
- 10.31235/osf.io/9s5hj is OK
- 10.1371/journal.pone.0205250 is OK
- 10.1371/journal.pone.0170046 is OK
- 10.1371/journal.pone.0180908 is OK
- 10.1073/pnas.1503793112 is OK
- 10.1126/science.1166858 is OK
- 10.21203/rs.3.rs-870835/v1 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.31 s (337.0 files/s, 67788.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          73           2105           1979          13421
reStructuredText                13            331            285           1165
JSON                             4              0              0            923
Markdown                         4            122              0            386
TeX                              3             18              0            201
SVG                              2              0              0            195
YAML                             3              7              5             74
INI                              1              4              0             41
DOS Batch                        1              8              1             26
make                             1              4              7              9
TOML                             1              0              0              6
-------------------------------------------------------------------------------
SUM:                           106           2599           2277          16447
-------------------------------------------------------------------------------


Statistical information for the repository 'cae314d1c4225388dda7b8e7' was
gathered on 2022/02/02.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Gereon A. Kaiping              382         12417           8129           28.69
Gereon Kaiping                 332         15257           8625           33.35
Melvin Samson Steige            68          3588           1956            7.74
Melvin Steiger                 533         11398           6517           25.02
Natalia Chousou-Poly            16            43             44            0.12
PaprikaSteiger                   5           579            309            1.24
Walter Fuchs                    39          1405           1317            3.80
natalia                          1            11             11            0.03

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Gereon A. Kaiping          6433           51.8          7.3                6.20
Gereon Kaiping             6130           40.2          4.9                5.53
Melvin Samson Steige       4495          125.3          7.0                4.96
Melvin Steiger              311            2.7         11.5                2.25
Walter Fuchs                110            7.8         19.1                6.36
natalia                      26          236.4          0.8                7.69
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #4123 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:72:in `block in build_affiliation_string': Problem with affiliations for Natalia Chousou-Polydouri, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:71:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:71:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:205:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:205:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by Kevin-Mattheus-Moerman** [comment]
@Anaphory It looks like you you should use `"2,3"` instead of `2,3` for the affiliations for `Natalia Chousou-Polydouri`. You can call the following here to update the paper: 
`@whedon generate pdf from branch joss-paper`

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @Bisaloo as editor

**Comment by whedon** [comment]
@Bisaloo has been invited to edit this submission.

**Comment by Anaphory** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #4123 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:72:in `block in build_affiliation_string': Problem with affiliations for Natalia Chousou-Polydouri, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:71:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:71:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:205:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:205:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by Anaphory** [comment]
@whedon generate pdf from branch joss-paper

**Comment by Anaphory** [comment]
We have looked through the list of reviewers and found the following handful of people who might have good insight on Lexedata.
# Suggested Reviewers
 - tresoldi
 - SimonGreenhill
 - richardlitt
 - adammichaelwood
 - sdruskat

**Comment by Bisaloo** [comment]
:wave: :wave: @Kevin-Mattheus-Moerman @Anaphory, yes, I can edit this submission.

@whedon assign me as editor

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Bisaloo as editor

**Comment by whedon** [comment]
OK, the editor is @Bisaloo

**Comment by Kevin-Mattheus-Moerman** [comment]
> :wave: :wave: @Kevin-Mattheus-Moerman @Anaphory, yes, I can edit this submission.
> 
> @whedon assign me as editor

The command to our bot had to come first. Anyway, thanks for your help.

**Comment by Bisaloo** [comment]
@Anaphory, before I can start looking for reviewers, could you please link to the docs from the repo (ideally, in the [repository details](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics) and in the README)? It will help potential reviewers to figure out if this submission is really within their area of expertise or not :slightly_smiling_face:

**Comment by Bisaloo** [comment]
Hi @lmaurits @xrotwang :wave: :wave:, you have been suggested to review [this paper](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04123/joss.04123/10.21105.joss.04123.pdf) and [python library](https://github.com/Anaphory/lexedata/) for JOSS. Looking at your work and GitHub profile, I agree you are a very good fit.

Would you be available to review this submission?

**Comment by Anaphory** [comment]
@Bisaloo Good idea! Repo details are updated, the README-updating PR is waiting for the workflows to finish so it can merge.

**Comment by Bisaloo** [comment]
@whedon add @xrotwang as reviewer

**Comment by whedon** [comment]
OK, @xrotwang is now a reviewer

**Comment by Bisaloo** [comment]
@xrotwang, amazing! Thanks for your help. Let me find a second reviewer and we can get started. I'll post instructions then but if you're already curious, you can read more about our process in our [online docs](https://joss.readthedocs.io/en/latest/index.html).

**Comment by Bisaloo** [comment]
Hi @peterdekker :wave:, the authors of this submission identified you as a potential review for this submission, would you be able to review this [paper](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04123/joss.04123/10.21105.joss.04123.pdf) and [python library](https://github.com/Anaphory/lexedata/) for [JOSS](https://joss.readthedocs.io/en/latest/)?

**Comment by Bisaloo** [comment]
@whedon add @peterdekker as reviewer

**Comment by whedon** [comment]
OK, @peterdekker is now a reviewer

**Comment by Bisaloo** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4140.
