### ISSUE TITLE
[PRE REVIEW]: smot: a python package and CLI tool for contextual phylogenetic subsampling

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4124]
**Submitting author:** @arendsee (<a href="http://orcid.org/0000-0002-5833-798X">Zebulun Arendsee</a>)
**Repository:** <a href="https://github.com/flu-crew/smot" target ="_blank">https://github.com/flu-crew/smot</a>
**Version:** v0.17.3
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/243645cbbc5074c24e30edb8af982673/status.svg)](https://joss.theoj.org/papers/243645cbbc5074c24e30edb8af982673)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/243645cbbc5074c24e30edb8af982673"><img src="https://joss.theoj.org/papers/243645cbbc5074c24e30edb8af982673/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/243645cbbc5074c24e30edb8af982673/status.svg)](https://joss.theoj.org/papers/243645cbbc5074c24e30edb8af982673)
```

**Author instructions**

Thanks for submitting your paper to JOSS @arendsee. **Currently, there isn't an JOSS editor assigned** to your paper.

@arendsee if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 2330

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.05 s (319.0 files/s, 84061.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          10            519            556           2175
Markdown                         3            126              0            392
TeX                              1             26              0            266
make                             1              1             29             83
YAML                             1              2              4             37
-------------------------------------------------------------------------------
SUM:                            16            674            589           2953
-------------------------------------------------------------------------------


Statistical information for the repository 'b3f7c2b5c450c15f620fb938' was
gathered on 2022/02/02.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Zebulun Arendsee                99          5527           2277          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Zebulun Arendsee           3250           58.8          7.8                8.43
```

**Comment by whedon** [comment]
PDF failed to compile for issue #4124 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:147:in `check_fields': Paper YAML header is missing expected fields: tags (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:89:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.12688/f1000research.10446.1 is OK
- 10.1093/molbev/msz053 is OK
- 10.1093/molbev/msw046 is OK

MISSING DOIs

- 10.1371/journal.pone.0009490 may be a valid DOI for title: FastTree 2–approximately maximum-likelihood trees for large alignments
- 10.1093/molbev/mst010 may be a valid DOI for title: MAFFT multiple sequence alignment software version 7: improvements in performance and usability
- 10.1128/jvi.00459-15 may be a valid DOI for title: Continual reintroduction of human pandemic H1N1 influenza A viruses into swine in the United States, 2009 to 2014
- 10.1371/journal.pcbi.1002947 may be a valid DOI for title: Viral phylodynamics
- 10.1126/science.1117727 may be a valid DOI for title: The tree-thinking challenge
- 10.22269/210921 may be a valid DOI for title: Tree thinking
- 10.1016/s0168-9525(03)00112-4 may be a valid DOI for title: Phylogeny for the faint of heart: a tutorial
- 10.1186/s12859-018-2164-8 may be a valid DOI for title: Treemmer: a tool to reduce large phylogenetic datasets with minimal loss of diversity
- 10.1186/1756-0500-6-145 may be a valid DOI for title: Treetrimmer: a method for phylogenetic dataset size reduction
- 10.1101/2021.02.13.431075 may be a valid DOI for title: Phylogenomic subsampling and the search for phylogenetically reliable loci
- 10.1093/molbev/msz053 may be a valid DOI for title: Phylogenetic clustering by linear integer programming (PhyCLIP)
- 10.1101/2021.01.21.427647 may be a valid DOI for title: DYNAMITE: a phylogenetic tool for identification of dynamic transmission epicenters
- 10.1186/s12864-018-4620-2 may be a valid DOI for title: TreeShrink: fast and accurate detection of outlier long branches in collections of phylogenetic trees
- 10.1093/bioinformatics/btq228 may be a valid DOI for title: DendroPy: a Python library for phylogenetic computing
- 10.1093/bioinformatics/btp163 may be a valid DOI for title: Biopython: freely available Python tools for computational molecular biology and bioinformatics
- 10.1128/mra.00673-19 may be a valid DOI for title: octoFLU: automated classification for the evolutionary origin of influenza A virus gene sequences detected in US swine
- 10.1016/j.softx.2020.100436 may be a valid DOI for title: TreeSwift: A massively scalable Python tree package
- 10.1093/molbev/msw046 may be a valid DOI for title: ETE 3: reconstruction, analysis, and visualization of phylogenomic data

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@arendsee can you work on those potentially missing DOI's? :point_up:

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev can you see what is wrong with the paper? Is it the use of `` `smot` `` in the title?

**Comment by arendsee** [comment]
@Kevin-Mattheus-Moerman Will do Kevin. The paper compiles fine in the preview service. The error message says something about a missing "tags" field in the metadata.

**Comment by danielskatz** [comment]
@arendsee - you might want to try adding one or more tags, as in the [example paper](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography)

**Comment by arendsee** [comment]
@danclewley Sure thing, I'll add tags in a bit.

**Comment by danielskatz** [comment]
Use the command `@whedon check references` to check the references again, and the command `@whedon generate pdf` after making changes to the .md file or when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by arendsee** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1371/journal.pone.0009490 is OK
- 10.1093/nar/gkw857 is OK
- 10.1128/mSphere.00275-16 is OK
- 10.1093/molbev/mst010 is OK
- 10.1126/science.1189132 is OK
- 10.1128/jvi.00459-15 is OK
- 10.1128/JVI.00459-15 is OK
- 10.1371/journal.pcbi.1002947 is OK
- 10.1126/science.1117727 is OK
- 10.22269/210921 is OK
- 10.1016/s0168-9525(03)00112-4 is OK
- 10.1186/s12859-018-2164-8 is OK
- 10.1186/1756-0500-6-145 is OK
- 10.1101/2021.02.13.431075 is OK
- 10.1093/molbev/msz053 is OK
- 10.1101/2021.01.21.427647 is OK
- 10.1186/s12864-018-4620-2 is OK
- 10.1093/bioinformatics/btq228 is OK
- 10.1093/bioinformatics/btp163 is OK
- 10.1128/mra.00673-19 is OK
- 10.12688/f1000research.10446.1 is OK
- 10.1093/molbev/msz053 is OK
- 10.1093/molbev/msw046 is OK
- 10.1016/j.softx.2020.100436 is OK
- 10.1111/2041-210X.12628 is OK
- 10.1093/molbev/msw046 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arendsee** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04124/joss.04124/10.21105.joss.04124.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04124/joss.04124/10.21105.joss.04124.pdf) :page_facing_up: :point_left:

**Comment by arendsee** [comment]
@tkanderson @amyvin2002 I'm tagging in my coauthors.

**Comment by Kevin-Mattheus-Moerman** [comment]
@marcosvital this looks like you might be able to edit this once you are available. Is that correct? If so, would you like us to wait or could I assign it to you already?

**Comment by kthyng** [comment]
Hi @Bisaloo! Is this a reasonable fit for you?

**Comment by whedon** [comment]
@Bisaloo has been invited to edit this submission.

**Comment by danielskatz** [comment]
👋 @Bisaloo - just a ping...

**Comment by Bisaloo** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @Bisaloo

**Comment by whedon** [comment]
OK, @Chjulian is now a reviewer

**Comment by Bisaloo** [comment]
Hi @marekborowiec :wave:, you signed up as a potential reviewer for JOSS. I think this submission could be relevant to your research interests:

> smot: a python package and CLI tool for contextual phylogenetic subsampling

Would you be available to review this [python package](https://github.com/flu-crew/smot) and [associated paper](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04124/joss.04124/10.21105.joss.04124.pdf) for JOSS? :relaxed:

**Comment by Bisaloo** [comment]
@arendsee, do you have any suggestions for a 2nd reviewer? If so, please mention them here in this thread (without tagging them with an @). [This list of people](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit?usp=sharing) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Comment by arendsee** [comment]
@Bisaloo maybe lskatz or kapsakcj

**Comment by marekborowiec** [comment]
@Bisaloo happy to do it but currently slammed. I can take a look next week!

**Comment by Bisaloo** [comment]
Yes, that would be perfect, there is no huge rush and we are usually pretty flexible with deadlines.

I'll go ahead and add you as reviewer then. I'll open the actual review issue shortly after and you'll be able to read more detailed instructions about the review process at JOSS there. Thanks!

**Comment by Bisaloo** [comment]
@editorialbot add @marekborowiec as reviewer

**Comment by Bisaloo** [comment]
@editorialbot start review

**Comment by kapsakcj** [comment]
Sorry for the late follow up - I appreciate the invite to review. Looks like other reviewers have already been selected, which is great.

I'm quite busy in the coming weeks and would not have been able to review for at least 2 weeks.

Best of luck on the review y'all!
