### ISSUE TITLE
[PRE REVIEW]: mxnorm: An R Package to Normalize Multiplexed Imaging Data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4168]
**Submitting author:** @ColemanRHarris (<a href="http://orcid.org/0000-0002-6325-0694">Coleman Harris</a>)
**Repository:** <a href="https://github.com/ColemanRHarris/mxnorm" target ="_blank">https://github.com/ColemanRHarris/mxnorm</a>
**Version:** v1.0.0
**Editor:** @osorensen
**Reviewers:** @askerdb, @tijeco
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/c18a1df622016c6ea8ed9e67dda73d07/status.svg)](https://joss.theoj.org/papers/c18a1df622016c6ea8ed9e67dda73d07)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/c18a1df622016c6ea8ed9e67dda73d07"><img src="https://joss.theoj.org/papers/c18a1df622016c6ea8ed9e67dda73d07/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/c18a1df622016c6ea8ed9e67dda73d07/status.svg)](https://joss.theoj.org/papers/c18a1df622016c6ea8ed9e67dda73d07)
```

**Author instructions**

Thanks for submitting your paper to JOSS @ColemanRHarris. **Currently, there isn't an JOSS editor assigned** to your paper.

@ColemanRHarris if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
PDF failed to compile for issue #4168 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by danielskatz** [comment]
@whedon check references from branch joss-paper

**Comment by danielskatz** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #4168 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:72:in `block in build_affiliation_string': Problem with affiliations for Coleman Harris, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:71:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:71:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:205:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:205:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1101/2021.07.16.452359 may be a valid DOI for title: Quantifying and correcting slide-to-slide variation in multiplexed immunofluorescence images
- 10.1038/s41374-020-0417-4 may be a valid DOI for title: Multiplexed ion beam imaging (MIBI) for characterization of the tumor microenvironment across tumor types
- 10.1016/j.cell.2021.11.031 may be a valid DOI for title: Differential pre-malignant programs and microenvironment chart distinct paths to malignancy in human colorectal polyps
- 10.1101/2021.03.15.435473 may be a valid DOI for title: MCMICRO: A scalable, modular image-processing pipeline for multiplexed tissue imaging
- 10.1093/bioinformatics/btab686 may be a valid DOI for title: FLINO: a new method for immunofluorescence bioimage normalization
- 10.1101/792770 may be a valid DOI for title: RESTORE: Robust intEnSiTy nORmalization mEthod for multiplexed imaging
- 10.1186/s13059-014-0550-8 may be a valid DOI for title: Moderated estimation of fold change and dispersion for RNA-seq data with DESeq2
- 10.1007/0-387-29362-0_23 may be a valid DOI for title: Limma: linear models for microarray data
- 10.1093/bioinformatics/btu638 may be a valid DOI for title: HTSeq—a Python framework to work with high-throughput sequencing data
- 10.1093/bioinformatics/btt656 may be a valid DOI for title: featureCounts: an efficient general purpose program for assigning sequence reads to genomic features
- 10.1101/2020.12.11.422048 may be a valid DOI for title: Toward reproducible, scalable, and robust data analysis across multiplex tissue imaging platforms
- 10.1101/2020.09.08.287516 may be a valid DOI for title: cytomapper: an R/Bioconductor package for visualization of highly multiplexed imaging data
- 10.1101/701680 may be a valid DOI for title: Giotto: a toolbox for integrative analysis and visualization of spatial expression data
- 10.1038/nm.3488 may be a valid DOI for title: Multiplexed ion beam imaging of human breast tumors
- 10.1101/2021.11.12.468357 may be a valid DOI for title: An end-to-end workflow for multiplexed image processing and analysis
- 10.1101/2021.02.19.431994 may be a valid DOI for title: Squidpy: a scalable framework for spatial single cell analysis
- 10.1093/bioinformatics/btab757 may be a valid DOI for title: spatialTIME and iTIME: R package and Shiny application for visualization and analysis of immunofluorescence data
- 10.1093/bioinformatics/bts034 may be a valid DOI for title: The sva package for removing batch effects and other unwanted variation in high-throughput experiments
- 10.1038/s41587-019-0113-3 may be a valid DOI for title: Efficient integration of heterogeneous single-cell transcriptomes using Scanorama

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @ColemanRHarris - note that your paper does not compile. Please follow the [example paper](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography). In addition, you could work on the possibly missing DOIs that whedon suggests, but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references from branch joss-paper` to check again, and the command `@whedon generate pdf from branch joss-paper` after making changes to the .md file or when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by danielskatz** [comment]
👋 @osorensen - Would you be able to edit this JOSS submission?

**Comment by danielskatz** [comment]
whedon invite @osorensen as editor

**Comment by whedon** [comment]
@osorensen has been invited to edit this submission.

**Comment by whedon** [comment]
OK, the editor is @osorensen

**Comment by ColemanRHarris** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04168/joss.04168/10.21105.joss.04168.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04168/joss.04168/10.21105.joss.04168.pdf) :page_facing_up: :point_left:

**Comment by ColemanRHarris** [comment]
@whedon check references from branch joss-paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/bioinformatics/btab877 is OK
- 10.1038/s41374-020-0417-4 is OK
- 10.1073/pnas.1300136110 is OK
- 10.1016/j.cell.2021.11.031 is OK
- 10.1002/cyto.a.24541 is OK
- 10.1101/2021.03.15.435473 is OK
- 10.1093/bioinformatics/btab686 is OK
- 10.1038/s42003-020-0828-1 is OK
- 10.1186/s13059-014-0550-8 is OK
- 10.1007/0-387-29362-0_23 is OK
- 10.1016/j.crmeth.2021.100053 is OK
- 10.1093/bioinformatics/btaa1061 is OK
- 10.1186/s13059-021-02286-2 is OK
- 10.1016/j.cell.2018.07.010 is OK
- 10.1038/nm.3488 is OK
- 10.1101/2021.11.12.468357 is OK
- 10.1101/2021.02.19.431994 is OK
- 10.1093/bioinformatics/btab757 is OK
- 10.1093/bioinformatics/bts034 is OK
- 10.1038/s41587-019-0113-3 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by ColemanRHarris** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04168/joss.04168/10.21105.joss.04168.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04168/joss.04168/10.21105.joss.04168.pdf) :page_facing_up: :point_left:

**Comment by osorensen** [comment]
@tijeco @kana4 @askerdb would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by askerdb** [comment]
I would be happy to review it!

**Comment by osorensen** [comment]
@whedon add @askerdb as reviewer

**Comment by whedon** [comment]
OK, @askerdb is now a reviewer

**Comment by tijeco** [comment]
I'd be happy to review it!

**Comment by osorensen** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4180.
