### ISSUE TITLE
[PRE REVIEW]: tidyhydat: Extract and Tidy Canadian Hydrometric Data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#509]
**Submitting author:** @boshek (<a href="http://orcid.org/0000-0002-9270-7884">Samuel Albers</a>)
**Repository:** <a href="https://github.com/ropensci/tidyhydat" target ="_blank">https://github.com/ropensci/tidyhydat</a>
**Version:** 0.3.0
**Editor:** @arfon
**Reviewer:** @arfon

**Author instructions**

Thanks for submitting your paper to JOSS @boshek. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@boshek if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #509 with the following error: 

 /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-453fa9fb981d/lib/whedon.rb:106:in `[]': no implicit conversion of String into Integer (TypeError)
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-453fa9fb981d/lib/whedon.rb:106:in `block in parse_affiliations'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-453fa9fb981d/lib/whedon.rb:105:in `each'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-453fa9fb981d/lib/whedon.rb:105:in `parse_affiliations'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-453fa9fb981d/lib/whedon.rb:92:in `parse_authors'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-453fa9fb981d/lib/whedon.rb:76:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-453fa9fb981d/lib/whedon/processor.rb:26:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-453fa9fb981d/lib/whedon/processor.rb:26:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-453fa9fb981d/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-453fa9fb981d/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

```

**Comment by arfon** [comment]
@openjournals/ropensci - has this package already on-boarded? If so, could you share the thread please?

**Comment by arfon** [comment]
Scrub that. I found it myself :-) https://github.com/ropensci/onboarding/issues/152

**Comment by arfon** [comment]
@boshek - please merge this PR so we can proceed https://github.com/ropensci/tidyhydat/pull/69

**Comment by boshek** [comment]
@arfon Merged. Thanks!

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #509 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16  100    16    0     0     39      0 --:--:-- --:--:-- --:--:--    39
Error producing PDF.
! LaTeX Error: File `fancyvrb.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.153 \newcommand

Looks like we failed to compile the PDF

```

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by whedon** [comment]
OK, the reviewer is @arfon

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/511. Feel free to close this issue now!
