### ISSUE TITLE
[PRE REVIEW]: Entrez - Call the NCBI E-utilities from Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#533]
**Submitting author:** @jordibc (<a href="http://orcid.org/0000-0002-9198-5380">Jordi Burguet-Castell</a>)
**Repository:** <a href="https://github.com/jordibc/entrez" target ="_blank">https://github.com/jordibc/entrez</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @jordibc. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@jordibc if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #533 with the following error: 

 /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon/author.rb:36:in `block in build_affiliation_string': Problem with affiliations for Jordi Burguet-Castell, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon/author.rb:35:in `each'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon/author.rb:35:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon/author.rb:11:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon.rb:97:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon.rb:97:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon.rb:95:in `each'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon.rb:95:in `parse_authors'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon.rb:76:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon/processor.rb:26:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon/processor.rb:26:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

```

**Comment by jordibc** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by jordibc** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #533 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0     69      0 --:--:-- --:--:-- --:--:--    69
Error reading bibliography ./paper.bib (line 1, column 9):
unexpected ","
expecting white space
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

```

**Comment by jordibc** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #533 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0     83      0 --:--:-- --:--:-- --:--:--    83
Error reading bibliography ./paper.bib (line 2, column 10):
unexpected "="
expecting space or ","
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

```

**Comment by jordibc** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00533/joss.00533/10.21105.joss.00533.pdf
```

**Comment by jordibc** [comment]
Good, I'm fine with the current status. Please let me know if there is anything I need to do from my side.

**Comment by arfon** [comment]
Hi @jordibc - many thanks for your submission to JOSS. Unfortunately this submission isn't acceptable to JOSS. As documented in our [submission criteria](http://joss.theoj.org/about#submission_requirements) we don't allow minor packages such as thin API clients which this looks to be.

**Comment by jordibc** [comment]
Hi @arfon , you are absolutely right, it escaped me. Thanks for pointing it out (and for your work on JOSS and the feedback!).
