### ISSUE TITLE
[PRE REVIEW]: bit: a git-based tool for the management of code and data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#534]
**Submitting author:** @jorgeboucas (<a href="http://orcid.org/0000-0002-9412-7592">Jorge Boucas</a>)
**Repository:** <a href="https://github.com/mpg-age-bioinformatics/bit" target ="_blank">https://github.com/mpg-age-bioinformatics/bit</a>
**Version:** 0.1.1
**Editor:** @acabunoc
**Reviewer:** @dvalters

**Author instructions**

Thanks for submitting your paper to JOSS @jorgeboucas. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@jorgeboucas if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #534 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:379:in `parse': (tmp/534/paper.md): did not find expected key while parsing a block mapping at line 2 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:379:in `parse_stream'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:327:in `parse'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:254:in `load'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:475:in `block in load_file'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:474:in `open'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:474:in `load_file'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon.rb:73:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon/processor.rb:26:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon/processor.rb:26:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

```

**Comment by arfon** [comment]
@acabunoc - would you be willing to edit this submission for JOSS?

**Comment by acabunoc** [comment]
@arfon happy to edit! I'll take a look later this week

**Comment by acabunoc** [comment]
@whedon assign @acabunoc as editor

**Comment by whedon** [comment]
OK, the editor is @acabunoc

**Comment by jorgeboucas** [comment]
@acabunoc thanks! I am here in case I am needed.

**Comment by acabunoc** [comment]
Hey @jorgeboucas! I took a quick look and I think we're good to start a review! Do you have any suggested reviewers? I like to have a few per submission 😄 

pinging @dvalters or @jsta -- would either of you be up for reviewing this? Raise a ✋ to let me know!

**Comment by dvalters** [comment]
@acabunoc sure ✋

**Comment by jorgeboucas** [comment]
maybe @paulklemm would like to join the party?

**Comment by paulklemm** [comment]
Sure I will help.

**Comment by jorgeboucas** [comment]
Hi @acabunoc, will 3 do it? 
@jsta we are taking your 🎉 as a show of hands ✋ - 😃

**Comment by jsta** [comment]
Unfortunately I am not available for this review. Best of luck tho!

**Comment by acabunoc** [comment]
What a showing! Thanks @paulklemm & @dvalters 😄
Here are the reviewer guidelines: http://joss.theoj.org/about#reviewer_guidelines

I'll take a quick look at your paper.md before we start the review

**Comment by acabunoc** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #534 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:379:in `parse': (tmp/534/paper.md): did not find expected key while parsing a block mapping at line 2 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:379:in `parse_stream'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:327:in `parse'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:254:in `load'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:475:in `block in load_file'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:474:in `open'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:474:in `load_file'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon.rb:73:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon/processor.rb:26:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon/processor.rb:26:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

```

**Comment by acabunoc** [comment]
@jorgeboucas could you merge [this PR](https://github.com/mpg-age-bioinformatics/bit/pull/5)? I _think_ it will fix the error @whedon's running into

**Comment by acabunoc** [comment]
@whedon assign @paulklemm as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @paulklemm

**Comment by acabunoc** [comment]
@whedon assign @dvalters as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @dvalters

**Comment by jorgeboucas** [comment]
@acabunoc merged. Thanks!

**Comment by jorgeboucas** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #534 with the following error: 

 /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon.rb:86:in `check_fields': Paper YAML header is missing expected fields: bibliography (RuntimeError)
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon.rb:74:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon/processor.rb:26:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon/processor.rb:26:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

```

**Comment by jorgeboucas** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00534/joss.00534/10.21105.joss.00534.pdf
```

**Comment by jorgeboucas** [comment]
@acabunoc `paper.md` functional now.

**Comment by acabunoc** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/549. Feel free to close this issue now!
