### ISSUE TITLE
[REVIEW]: GrainSizeTools: a Python script for grain size analysis and paleopiezometry based on grain size

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#863]
**Submitting author:** @marcoalopez (<a href="http://orcid.org/0000-0002-0261-9267">Marco A. Lopez-Sanchez</a>)
**Repository:** <a href="https://marcoalopez.github.io/GrainSizeTools/" target ="_blank">https://marcoalopez.github.io/GrainSizeTools/</a>
**Version:** v2.0
**Editor:** @lheagy
**Reviewer:** @jsta
**Archive:** Pending

## Status

[![status](http://joss.theoj.org/papers/677d076203e90d16eaaf301a05600815/status.svg)](http://joss.theoj.org/papers/677d076203e90d16eaaf301a05600815)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/677d076203e90d16eaaf301a05600815"><img src="http://joss.theoj.org/papers/677d076203e90d16eaaf301a05600815/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/677d076203e90d16eaaf301a05600815/status.svg)](http://joss.theoj.org/papers/677d076203e90d16eaaf301a05600815)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://marcoalopez.github.io/GrainSizeTools/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@jsta, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @lheagy know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [ ] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [ ] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://marcoalopez.github.io/GrainSizeTools/">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (v2.0)?
- [ ] **Authorship:** Has the submitting author (@marcoalopez) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @jsta it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #863 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `block in find': No such file or directory (Errno::ENOENT)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:57:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:32:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by lheagy** [comment]
:wave: Thanks @khaors and @jsta for being willing to review! In the main issue thread above, there is a checklist for each of you to help guide the review. Please let me know if you have any questions or if I can provide any clarification.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by lheagy** [comment]
:wave: Hi @khaors, @jsta, just checking in. When do you think you will have time to get started on the review? If possible, we would appreciate your input within the next two weeks. Thanks!

**Comment by jsta** [comment]
@lheagy Should the `repository url` link point to https://marcoalopez.github.io/GrainSizeTools/ or https://github.com/marcoalopez/GrainSizeTools ?

**Comment by marcoalopez** [comment]
Hi @jsta, thank you for this initial review. Regarding the **community guidelines**, I mention in the FAQ section https://github.com/marcoalopez/GrainSizeTools/blob/master/DOCS/FAQ.md the following: 

> ***Can I report bugs or submit ideas to improve the script?***  
Sure. If you have issues using the script, found a bug or see an error in the documentation please just let me know by dropping me an email or open an issue [here](https://github.com/marcoalopez/GrainSizeTools/issues) (you can find my email here: https://github.com/marcoalopez ). Feedback from users is always welcome and important to develop a better and reliable script. Lastly, you can also fork the project and develop your own based on the GST script since it is open source and free.

I guess this text has two problems: (1) it is not obvious to find the community guidelines in the FAQ, and (2) maybe it is too short or not very detailed. Any ideas on how to improve this and give it more visibility? Perhaps I could indicate this more explicitly on the main website.

PS. I fixed a typo in the original FAQ text I copied above. However, the meaning of the text remains the same as the original.

**Comment by marcoalopez** [comment]
Hi @jsta I've already added the community guidelines to the README and the website as suggested.

**Comment by marcoalopez** [comment]
Hi @lheagy, how can I redirect the ``repository URL`` to https://github.com/marcoalopez/GrainSizeTools and meet the required criteria by @jsta?

**Comment by lheagy** [comment]
Hi @marcoalopez: I have updated the link in the main issue thread above, so all of the links should now point to https://github.com/marcoalopez/GrainSizeTools/

**Comment by lheagy** [comment]
:wave: Hi @khaors, just checking in. When do you think you will have time to get started on this review? Thanks!

**Comment by lheagy** [comment]
Thanks @jsta for your review! 

:wave: Hi @khaors, would you be able to get started on the review soon? Thanks!

**Comment by marcoalopez** [comment]
Hi @lheagy, I have a question. I would like to launch a code update. It would be minor changes that add some new features (from v2.0 to v2.0.1). Could I do this now or should I wait for the review to finish? I'm not sure if the code should be "frozen" during the review process or it can be modified. Thanks!

**Comment by lheagy** [comment]
Hi @marcoalopez, not a problem, you can launch the update. Please just let me know when you have and I will update the version number on the review.

**Comment by marcoalopez** [comment]
Hi @lheagy, it's done. Thank you.

**Comment by lheagy** [comment]
Thanks @marcoalopez. A quick update, I have email @khaors yesterday and am waiting to hear back. We will give him a couple days to respond, and if not, figure out the next steps for proceeding with the submission

**Comment by marcoalopez** [comment]
Hi @lheagy, Any news about @khaors?

**Comment by lheagy** [comment]
Hi @marcoalopez: thanks for checking in. I haven't heard anything. I will check with the editorial board on how to proceed and get back to you.

**Comment by lheagy** [comment]
👋Hi @marcoalopez: I will take a look through your submission this weekend and see if I have any comments following up from @jsta's review and we can go from there. Thanks for your patience!

**Comment by marcoalopez** [comment]
You're welcome @lheagy, thank you very much for your help!

**Comment by lheagy** [comment]
Hi @marcoalopez, I generated a few issues with respect to licensing, packaging and installation. Please take a look when you have a chance and let me know if there is anything I can clarify! 
- marcoalopez/GrainSizeTools#6 
- marcoalopez/GrainSizeTools#8
- marcoalopez/GrainSizeTools#7

**Comment by marcoalopez** [comment]
Hi @lheagy, I have several questions that I would like to discuss before merging the proposed modifications with the master branch and modifying the script documentation. I have tested the modifications and everything seems to work fine. However, I think they add a bit of difficulty for the non-expert user, as I will try to explain below. In addition, these modifications would imply maintaining two different branches of the script since the changes introduced will produce a module error when running the GrainSizeTools.py file. In other words, the modifications proposed no longer allow to use the script as before.

So far all script users simply download and run it in an IDE and then interact with it (mainly because of the way it was designed and released). When introducing these modifications, people will have to install the script using the console via pip, import the module, and use the dot notation to interact with the functions. I know this is no big deal, but it's more complicated than just calling a small number of functions and getting the results. Keep in mind here that this script is mainly designed for people without previous experience in Python programming language (indeed most users are of this type in my experience), so my first intention is to keep things as simple as possible. Of course, I see other advantages in using PyPI and I would like that the script could be installed in this way. My doubts are that this would require maintaining two branches of the same script and rewriting most of the documentation. Perhaps the last point could be avoided by briefly explaining the dot notation and the structure of the script for more advanced users.  In contrast, I haven't found a way to avoid the maintenance of two branches and I'm a bit stuck at this point. Maybe I'm overthinking it.

**Comment by lheagy** [comment]
Hi @marcoalopez: thanks for your message. It is up to you, and feel free to disregard the pull request if this is not the direction you want to go. My word-of-caution here is that the current packaging doesn't allow GrainSizeTools to easily interoperate with other packages in the python ecosystem. For example, if I wanted to import grainsize tools into a workflow I have in a Jupyter notebook, that is not easily done.

There is a middle-ground you could consider - keep the script at the top level and package the rest of the utilities as a python e.g.
```
GrainSizeTools (repo-level) /
    setup.py   (installs everything under grain_size_tools)
    GrainSizeToolsScript.py
    grain_size_tools/ 
        tools.py
        ...
```
The setup.py would install everything under `grain_size_tools` (and make everything under `grain_size_tools` pip-installable). The script would the import from `grain_size_tools` and you can run it in an IDE. 

If this is of interest to you, and you have any questions about how you might approach this, I can make some notes and suggestions in the pull request. If not, no worries :)

**Comment by lheagy** [comment]
Hi @marcoalopez: sorry for my delayed response. 

Not a problem, it is totally up to you to decide the direction of the project :) Excellent, I will take a look at your notebooks!  

For sure, feel free to merge the pr if you like, you can change where the pr is being merged to by editing it
![image](https://user-images.githubusercontent.com/6361812/46158470-c1c70880-c232-11e8-9ae1-05f0d634f091.png)
and changing the branch
![image](https://user-images.githubusercontent.com/6361812/46158501-d4d9d880-c232-11e8-9b36-cffc6edef825.png)

Importing `*` is generally discouraged -- for example if you have
```python
import numpy as np
import matplotlib

import tools

def grain_size_tools_fct():
    .... 
```
in your GrainSizeTools_script, then importing `*` will bring in `np`, `matplotlib`, .... This is okay, but discouraged because it is a bit convoluted (it is better if the user knows exactly what functionality they are bringing in). 

However, if this is a beneficial first step, then as long as you keep in mind the drawbacks, it is not a bad way to progress.

**Comment by lheagy** [comment]
Hi again @marcoalopez, 

The notebook is a nice addition! 

I have gone through the rest of the checklist and there is one remaining items (and two minor items) to be addressed. The main item is testing. I didn't see a clear indication of testing (ideally automated testing, but even manually is okay for acceptance). I have summarized comments on testing here:
- marcoalopez/GrainSizeTools#10

The other two minor comments are with respect to the paper and the newly added notebook:
- marcoalopez/GrainSizeTools#11
- marcoalopez/GrainSizeTools#12

Please let me know if I can provide any clarification. Once these items are addressed, I think we can go-ahead with publication.

**Comment by lheagy** [comment]
Thanks for all of your work reviewing @jsta, and nice work @marcoalopez! Thanks for iterating with me and I hope you have found the review process beneficial. 

@marcoalopez: could you please archive the software on [zenodo](https://zenodo.org/) or similar and we can proceed with publication 🎉

**Comment by marcoalopez** [comment]
Hi @lheagy, thank you for your support as an editor and the review. I have learned many things in the process. I would like to say that I really think this is the way to go for the publication and revision of the software. So congratulations to the whole JOSS team for this great idea and keep going. I archive the software as it is now in GitHub repository on the following doi (figshare):

https://doi.org/10.6084/m9.figshare.1383130.v23

**Comment by lheagy** [comment]
@whedon set 10.6084/m9.figshare.1383130.v23 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.6084/m9.figshare.1383130.v23" target="_blank">10.6084/m9.figshare.1383130.v23</a> is the archive.

**Comment by lheagy** [comment]
@arfon, this submission is ready to be published. One quick question for you: do we want the version number in the doi? (e.g. `v23`)

Congrats on your submission @marcoalopez and many thanks @jsta for your effort reviewing 🎉!
