### ISSUE TITLE
[REVIEW]: q2-sample-classifier: machine-learning tools for microbiome classification and regression

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#934]
**Submitting author:** @nbokulich (<a href="http://orcid.org/0000-0002-1784-8935">Nicholas Bokulich</a>)
**Repository:** <a href="https://github.com/caporaso-lab/sample-classifier-ms" target ="_blank">https://github.com/caporaso-lab/sample-classifier-ms</a>
**Version:** 2018.6
**Editor:** @yochannah
**Reviewer:** @rasbt, @luizirber
**Archive:** Pending

## Status

[![status](http://joss.theoj.org/papers/d828a4ecf73eb6a147f8634e9054eeee/status.svg)](http://joss.theoj.org/papers/d828a4ecf73eb6a147f8634e9054eeee)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/d828a4ecf73eb6a147f8634e9054eeee"><img src="http://joss.theoj.org/papers/d828a4ecf73eb6a147f8634e9054eeee/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/d828a4ecf73eb6a147f8634e9054eeee/status.svg)](http://joss.theoj.org/papers/d828a4ecf73eb6a147f8634e9054eeee)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/caporaso-lab/sample-classifier-ms" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@rasbt & @luizirber, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @yochannah know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [ ] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [ ] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/caporaso-lab/sample-classifier-ms">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (2018.6)?
- [ ] **Authorship:** Has the submitting author (@nbokulich) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [ ] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [ ] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/caporaso-lab/sample-classifier-ms">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (2018.6)?
- [ ] **Authorship:** Has the submitting author (@nbokulich) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @rasbt, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00934/joss.00934/10.21105.joss.00934.pdf)

**Comment by rasbt** [comment]
@nbokulich @yochannah Just had a quick look at the pdf and the links link all to the manuscript repo rather than the software repo. I remember the issue came up in another review I did some time ago. Best way to address this is to put the manuscript file into the software repo that is being reviewed. E.g., you can put it into the docs subfolder.

**Comment by yochannah** [comment]
@rasbt Good spot! 

@nbokulich could you please put paper.md in the main https://github.com/qiime2/q2-sample-classifier repo? Thanks!

**Comment by nbokulich** [comment]
sorry for the oversight on my part @yochannah @rasbt

I have added the manuscript to the software repo [here](https://github.com/qiime2/q2-sample-classifier/tree/master/paper)... @yochannah is there some way to reassign the repository to correct the links in the proof? (sorry — I entered that information during submission so do not see a way to edit now)

**Comment by yochannah** [comment]
Thanks @nbokulich! 

@arfon, do we just need to edit the url for the github issue and regenerate the pdf to fix the repo URL, or is there a better way to go about this?

**Comment by arfon** [comment]
> @arfon, do we just need to edit the url for the github issue and regenerate the pdf to fix the repo URL, or is there a better way to go about this?

Yep, feel free to edit the issue at the top and then as Whedon to compile again.

**Comment by yochannah** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00934/joss.00934/10.21105.joss.00934.pdf)

**Comment by rasbt** [comment]
Regarding the checklist above:

>  Repository: Is the source code for this software available at the repository url?

this still has the wrong link, but I think we can ignore it since the paper PDF has the correct link now.

**Comment by rasbt** [comment]
Regarding 

> Version: Does the release version given match the GitHub release (2018.6)?

I see that the softw is at v2018.10 already. I guess the best thing to do is to revisit the version number references at the end, because they version numbers may change during the review stage as potential issues are being addressed

**Comment by rasbt** [comment]
> Authorship: Has the submitting author (@nbokulich) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

This looks good to me overall, however, I noticed that Benjamin D Kaehler and Gavin A Huttley haven't contributed via GitHub, and there are a few contributors who aren't listed on the paper if I see that correctly. I assume that the authorship has been discussed and handled reasonably and appropriately, but it would be nice, @nbokulich, if you could say a few things about that.

**Comment by rasbt** [comment]
@nbokulich 

regarding

> References: Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

Could you please add the DOIs to the paper

**Comment by rasbt** [comment]
The paper itself looks really great. Just found a few very minor formatting issues -- would be nice if you could address these (ref https://github.com/qiime2/q2-sample-classifier/issues/132)

**Comment by yochannah** [comment]
@rasbt Thanks for making a start on this! 👍 

@luizirber Have you had a chance to start looking the paper over yet?

**Comment by nbokulich** [comment]
Thank you @rasbt ! I have a few responses, and am working on a PR to address your concerns [here](https://github.com/qiime2/q2-sample-classifier/issues/132) and [here](https://github.com/qiime2/q2-sample-classifier/issues/133) (thank you for raising issues!)

> I see that the softw is at v2018.10 already. I guess the best thing to do is to revisit the version number references at the end, because they version numbers may change during the review stage as potential issues are being addressed

Sorry — we are on a quick release cycle right now. 2018.8 was released a week or two after I submitted this manuscript, and 2018.10 is the current dev version. I agree, we can update later since 2018.10 may be the stable release by the time manuscript review is finalized.

> This looks good to me overall, however, I noticed that Benjamin D Kaehler and Gavin A Huttley haven't contributed via GitHub, and there are a few contributors who aren't listed on the paper if I see that correctly

Thank you for asking. @BenKaehler helped write the paper and contributed to the source code, [this](https://github.com/qiime2/q2-sample-classifier/pull/101) is the most significant contribution (see the commit log) though attributions may have been mixed up since that commit was spliced from a separate PR raised by Ben. @GavinHuttley and @gregcaporaso provided useful discussions, material support, and helped write the manuscript (@gregcaporaso also wrote and reviewed the source code). @thermokarst and @ebolyen both wrote and/or reviewed significant amounts of source code, and helped write the manuscript. @jairideout declined authorship, since he felt that his contributions were minor, and he is acknowledged instead for his support. @q2d2 is a robot. Other contributors to the repo made their contributions after this manuscript was submitted; their work is ongoing and the subject of a separate paper that is in preparation. I would be happy to write up a formal contributions statement in the paper but this did not seem to adhere to journal format.

**Comment by luizirber** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00934/joss.00934/10.21105.joss.00934.pdf)

**Comment by nbokulich** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00934/joss.00934/10.21105.joss.00934.pdf)

**Comment by rasbt** [comment]
@nbokulich 

Thanks a lot for the detailed explanation.

> I would be happy to write up a formal contributions statement in the paper but this did not seem to adhere to journal format.

I don't think this is necessary for JOSS, but thanks for asking!!

**Comment by yochannah** [comment]
It makes sense for @luizirber to review the newly generated paper I think!

**Comment by yochannah** [comment]
Quick status check on this paper... How is everyone getting on?

**Comment by rasbt** [comment]
@yochannah  @nbokulich  Everything is fine from my side. The examples work and I just ran the unit tests -- except for some warnings in sklearn there are no issues :). So, from my side, it's good to go :)

**Comment by luizirber** [comment]
I just checked all my boxes. Some comments:
- version: This one I didn't check, but it was already discussed in this thread.
- tests: I didn't find in an easy place how to run the tests, so I ended up downloading the repo and running pytest on it. Is that the appropriate method? Either way, I think it's good to put it somewhere in the docs.
- Congrats on the tutorials and docs! They are really good =]

@yochannah good to go!

**Comment by nbokulich** [comment]
Thank you @luizirber and @rasbt for your reviews and feedback!

@luizirber — I have issued this PR to address your testing suggestion: https://github.com/qiime2/q2-sample-classifier/pull/138.

**Comment by rasbt** [comment]
> tests: I didn't find in an easy place how to run the tests, so I ended up downloading the repo and running pytest on it. Is that the appropriate method? Either way, I think it's good to put it somewhere in the docs.

Yes, that's what I did, too. The steps were not mentioned, but one could find them in the travis CI setup file. I agree with @luizirber  that it would not hurt to add a sentence about running the tests with pytest to the Readme file, though.

**Comment by yochannah** [comment]
Okay, I think the only thing left to do before we ping Arfon to say this is ready is to fix the version numbering and regenerated the paper. @nbokulich - is 2018.10 the correct version to point to?

**Comment by yochannah** [comment]
If we're all happy to wait until the release date I think that sounds reasonable!

**Comment by nbokulich** [comment]
We can just point to version 2018.8 (the current stable release).

**Comment by nbokulich** [comment]
@arfon — I have archived in zenodo. DOI: https://doi.org/10.5281/zenodo.1468878
Thank you!

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1468878 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1468878" target="_blank">10.5281/zenodo.1468878</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #934 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    14    0    14    0     0    190      0 --:--:-- --:--:-- --:--:--   191
/app/vendor/ruby-2.4.4/lib/ruby/2.4.0/open-uri.rb:37:in `open': no implicit conversion of nil into String (TypeError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/open-uri.rb:37:in `open'
	from /app/vendor/bundle/ruby/2.4.0/gems/bibtex-ruby-4.4.7/lib/bibtex/bibliography.rb:52:in `open'
	from /app/vendor/bundle/ruby/2.4.0/gems/bibtex-ruby-4.4.7/lib/bibtex/utilities.rb:27:in `open'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1b5849bd99c1/lib/whedon/bibtex.rb:24:in `generate_citations'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1b5849bd99c1/lib/whedon/processor.rb:214:in `generate_crossref'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1b5849bd99c1/lib/whedon/processor.rb:91:in `compile'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1b5849bd99c1/bin/whedon:76:in `compile'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1b5849bd99c1/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@nbokulich - could you update your `references.bib` to be `paper.bib` and update the `paper.md` file accordingly (to point to `paper.md`)?

**Comment by arfon** [comment]
@nbokulich - actually ignore me. I've just updated the @whedon bot to handle custom bibtex locations (i.e. files not called `paper.bib`)

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/26

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/26, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by nbokulich** [comment]
@arfon the "repository" link in the paper PDF points to the correct repo ([here](https://github.com/qiime2/q2-sample-classifier)), but the "software repository" link on the article details page points to the paper repo ([here](https://github.com/caporaso-lab/sample-classifier-ms)) that I originally used at the time of submission (sorry, my fault 😞). Can we get this fixed or has that ship sailed? Thank you!

**Comment by arfon** [comment]
@nbokulich - that's fixed now.

**Comment by nbokulich** [comment]
Thank you @arfon !
